// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "colormap.h"

/////////////////////////////////////////////////////////////////////////////
// CColormap

IMPLEMENT_DYNCREATE(CColormap, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CColormap properties

long CColormap::GetColor()
{
    long result;
    GetProperty(0x1, VT_I4, (void*)&result);
    return result;
}

void CColormap::SetColor(long propVal)
{
    SetProperty(0x1, VT_I4, propVal);
}

BOOL CColormap::GetHasFrame()
{
    BOOL result;
    GetProperty(0x2, VT_BOOL, (void*)&result);
    return result;
}

void CColormap::SetHasFrame(BOOL propVal)
{
    SetProperty(0x2, VT_BOOL, propVal);
}

CString CColormap::GetTitle()
{
    CString result;
    GetProperty(0x3, VT_BSTR, (void*)&result);
    return result;
}

void CColormap::SetTitle(LPCTSTR propVal)
{
    SetProperty(0x3, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CColormap operations

void CColormap::AboutBox()
{
    InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
