/* DO NOT EDIT THIS FILE - it is machine generated */
#line 30 "C:\\mytools2015\\parsergen\\Olm637\\Olm637.y"
#include "stdafx.h"
#include "Olm637parser.h"

#line 21 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"

int Olm637Parser::reduceAction(unsigned int prod) {

  switch(prod) {
  case 1: /* S -> a A d */
#line 38 "C:\\mytools2015\\parsergen\\Olm637\\Olm637.y"
    { m_dollardollar = getStackTop(1); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  }
  return 0;
}

#line 53 "C:\\mytools2015\\parsergen\\Olm637\\Olm637.y"

#line 31 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
