/* DO NOT EDIT THIS FILE - it is machine generated */
#pragma once

#include <LRparser.h>

#line 5 "C:\\Mytools2015\\ParserGen\\Olm637\\Olm637.y"
#include "Olm637symbol.h"

#define YYSTYPE int
class Olm637Parser : public LRparser {
private:
  static const ParserTables *Olm637Tables;
public:
  Olm637Parser(Scanner *lex=NULL) : LRparser(*Olm637Tables,lex) {
  }
private:
  YYSTYPE m_leftSide,*m_stacktop,m_userstack[256];
  YYSTYPE getStackTop(int fromtop)                { return m_stacktop[-fromtop];           }
  void userStackInit()                   override { m_stacktop = m_userstack;              }
  void userStackShiftSymbol(UINT symbol) override { m_stacktop++;                          } // push 1 element (garbage) on userstack
  void userStackPopSymbols( UINT count ) override { m_stacktop      -= count;              } // pop count symbols from userstack
  void userStackShiftLeftSide()          override { *(++m_stacktop) = m_leftSide;          } // push($$) on userstack
  void defaultReduce(       UINT prod  ) override { m_leftSide      = *m_stacktop;         } // $$ = $1
  int  reduceAction(        UINT prod  ) override;
};

#line 22 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"

