/* DO NOT EDIT THIS FILE - it is machine generated */
#pragma once
#include <Scanner.h>

#line 2 "C:\\Mytools2015\\UnixTools\\sqlbeauty\\Sql.lex"
#pragma once

 /* This part goes to SqlLex.h */

#include <Scanner.h>
#include <LrParser.h>

class SqlLex : public Scanner {
private:
  LRparser *m_parser; // redirect errors to parser
public:
  SqlLex(LRparser *parser=NULL);
  int getNextLexeme();
  void verror(const SourcePosition &pos, const TCHAR *format, va_list argptr);
  static void findBestHashMapSize();
};

#line 5 "C:\\mytools2015\\ParserGen\\lib\\lexgencpp.par"

