//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CalculatorApp.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDR_MENUCONTEXTHELP             130
#define IDD_DIALOGPREC                  131
#define IDR_ACCELERATORPRECISION        133
#define IDC_DISPLAY                     1000
#define IDC_RADIORADIANS                1010
#define IDC_RADIODEGREES                1011
#define IDC_RADIOGRADS                  1012
#define IDC_RADIOBIN                    1013
#define IDC_RADIOOCT                    1014
#define IDC_RADIODEC                    1015
#define IDC_RADIOHEX                    1016
#define IDC_RADIOBYTE                   1020
#define IDC_RADIOWORD                   1021
#define IDC_RADIODWORD                  1022
#define IDC_RADIOQWORD                  1023
#define IDC_RADIOOWORD                  1024
#define IDC_BUTTONADD                   1040
#define IDC_BUTTONSUB                   1041
#define IDC_BUTTONMULT                  1042
#define IDC_BUTTONDIV                   1043
#define IDC_BUTTONMOD                   1044
#define IDC_BUTTONRECIPROC              1045
#define IDC_BUTTONEQUAL                 1046
#define IDC_BUTTONSQUARE                1050
#define IDC_BUTTONPOW3                  1051
#define IDC_BUTTONPOW                   1052
#define IDC_BUTTONLN                    1060
#define IDC_BUTTONLOG                   1061
#define IDC_BUTTONSIN                   1062
#define IDC_BUTTONCOS                   1063
#define IDC_BUTTONTAN                   1064
#define IDC_BUTTONPI                    1065
#define IDC_BUTTONFAC                   1066
#define IDC_BUTTONDMS                   1067
#define IDC_BUTTON0                     1100
#define IDC_BUTTON1                     1101
#define IDC_BUTTON2                     1102
#define IDC_BUTTON3                     1103
#define IDC_BUTTON4                     1104
#define IDC_BUTTON5                     1105
#define IDC_BUTTON6                     1106
#define IDC_BUTTON7                     1107
#define IDC_BUTTON8                     1108
#define IDC_BUTTON9                     1109
#define IDC_BUTTONA                     1110
#define IDC_BUTTONB                     1111
#define IDC_BUTTONC                     1112
#define IDC_BUTTOND                     1113
#define IDC_BUTTONE                     1114
#define IDC_BUTTONF                     1115
#define IDC_BUTTONSIGN                  1116
#define IDC_BUTTONCOMMA                 1117
#define IDC_BUTTONEE                    1118
#define IDC_BUTTONCLEAR                 1120
#define IDC_BUTTONCE                    1121
#define IDC_BUTTONBACKSPACE             1122
#define IDC_BUTTONAND                   1130
#define IDC_BUTTONOR                    1131
#define IDC_BUTTONXOR                   1132
#define IDC_BUTTONNOT                   1133
#define IDC_BUTTONLSH                   1134
#define IDC_BUTTONINT                   1135
#define IDC_BUTTONLPAR                  1140
#define IDC_BUTTONRPAR                  1141
#define IDC_BUTTONMC                    1150
#define IDC_BUTTONMR                    1151
#define IDC_BUTTONMS                    1152
#define IDC_BUTTONMADD                  1153
#define IDC_CHECKINV                    1160
#define IDC_CHECKHYP                    1161
#define IDC_PARANTHESLEVEL              1162
#define IDC_MEMORYINDICATOR             1163
#define IDC_EDITPRECISION               1164
#define IDC_DEBUGCHAR                   1170
#define IDC_INFO                        1171
#define IDC_STATICRADIX                 1172
#define IDC_STATICOPSIZE                1173
#define IDC_STATICTRIGOMODE             1174
#define ID_FILE_QUIT                    32771
#define ID_CONTROL_WHATSTHIS            32772
#define ID_VIEW_RADIANS                 32810
#define ID_VIEW_DEGREES                 32811
#define ID_VIEW_GRADS                   32812
#define ID_VIEW_BIN                     32813
#define ID_VIEW_OCT                     32814
#define ID_VIEW_DEC                     32815
#define ID_VIEW_HEX                     32816
#define ID_VIEW_BYTE                    32820
#define ID_VIEW_WORD                    32821
#define ID_VIEW_DWORD                   32822
#define ID_VIEW_QWORD                   32823
#define ID_VIEW_OWORD                   32824
#define ID_VIEW_DIGITGROUPING           32830
#define ID_VIEW_PRECISION               32831
#define ID_HELP_ABOUT                   32832
#define ID_ADD                          32840
#define ID_SUB                          32841
#define ID_MULT                         32842
#define ID_DIV                          32843
#define ID_MOD                          32844
#define ID_RECIPROC                     32845
#define ID_EQUAL                        32846
#define ID_SQUARE                       32850
#define ID_POW3                         32851
#define ID_POW                          32852
#define ID_LN                           32860
#define ID_LOG                          32861
#define ID_SIN                          32862
#define ID_COS                          32863
#define ID_TAN                          32864
#define ID_PI                           32865
#define ID_FAC                          32866
#define ID_DMS                          32867
#define ID_NUMBER0                      32900
#define ID_NUMBER1                      32901
#define ID_NUMBER2                      32902
#define ID_NUMBER3                      32903
#define ID_NUMBER4                      32904
#define ID_NUMBER5                      32905
#define ID_NUMBER6                      32906
#define ID_NUMBER7                      32907
#define ID_NUMBER8                      32908
#define ID_NUMBER9                      32909
#define ID_NUMBERA                      32910
#define ID_NUMBERB                      32911
#define ID_NUMBERC                      32912
#define ID_NUMBERD                      32913
#define ID_NUMBERE                      32914
#define ID_NUMBERF                      32915
#define ID_SIGN                         32916
#define ID_COMMA                        32917
#define ID_EE                           32918
#define ID_CLEAR                        32920
#define ID_CE                           32921
#define ID_BACK                         32922
#define ID_AND                          32930
#define ID_OR                           32931
#define ID_XOR                          32932
#define ID_NOT                          32933
#define ID_LSH                          32934
#define ID_INT                          32935
#define ID_LPAR                         32940
#define ID_RPAR                         32941
#define ID_SHOWINFO                     32950
#define ID_GOTOPRECISION                32960

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32972
#define _APS_NEXT_CONTROL_VALUE         1175
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
