//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CalculatorApp.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CALCULATOR_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDR_MENU2                       130
#define IDD_DIALOGPREC                  131
#define IDC_CURSOR1                     132
#define IDR_ACCELERATORPRECISION        133
#define IDC_DISPLAY                     1000
#define IDC_ACCELERATORTABEL            1001
#define IDC_BUTTONCLEAR                 1002
#define IDC_BUTTON0                     1003
#define IDC_BUTTON1                     1004
#define IDC_BUTTON2                     1005
#define IDC_BUTTON3                     1006
#define IDC_BUTTON4                     1007
#define IDC_BUTTON5                     1008
#define IDC_BUTTON6                     1009
#define IDC_BUTTON7                     1010
#define IDC_BUTTON8                     1011
#define IDC_BUTTON9                     1012
#define IDC_BUTTONA                     1013
#define IDC_BUTTONB                     1014
#define IDC_BUTTONC                     1015
#define IDC_BUTTOND                     1016
#define IDC_BUTTONE                     1017
#define IDC_BUTTONF                     1018
#define IDC_BUTTONSIGN                  1019
#define IDC_BUTTONCOMMA                 1020
#define IDC_BUTTONDIV                   1021
#define IDC_BUTTONMULT                  1022
#define IDC_BUTTONSUB                   1023
#define IDC_BUTTONADD                   1024
#define IDC_BUTTONCE                    1025
#define IDC_BUTTONBACKSPACE             1026
#define IDC_BUTTONMC                    1027
#define IDC_BUTTONMR                    1028
#define IDC_BUTTONMS                    1029
#define IDC_BUTTONMADD                  1030
#define IDC_BUTTONMOD                   1031
#define IDC_BUTTONOR                    1032
#define IDC_BUTTONLSH                   1033
#define IDC_BUTTONEQUAL                 1034
#define IDC_BUTTONAND                   1035
#define IDC_BUTTONXOR                   1036
#define IDC_BUTTONNOT                   1037
#define IDC_BUTTONINT                   1038
#define IDC_BUTTONPI                    1039
#define IDC_BUTTONRPAR                  1040
#define IDC_BUTTONLPAR                  1041
#define IDC_BUTTONEE                    1042
#define IDC_BUTTONPOW                   1043
#define IDC_BUTTONLN                    1044
#define IDC_BUTTONLOG                   1045
#define IDC_BUTTONFAC                   1046
#define IDC_BUTTONPOW3                  1047
#define IDC_BUTTONRECIPROC              1048
#define IDC_BUTTONSQUARE                1049
#define IDC_BUTTONSIN                   1050
#define IDC_BUTTONCOS                   1051
#define IDC_BUTTONTAN                   1052
#define IDC_BUTTONDMS                   1053
#define IDC_RADIODEGREES                1054
#define IDC_RADIORADIANS                1055
#define IDC_RADIOGRADS                  1056
#define IDC_RADIOHEX                    1057
#define IDC_RADIODEC                    1058
#define IDC_RADIOOCT                    1059
#define IDC_RADIOBIN                    1060
#define IDC_CHECKINV                    1061
#define IDC_CHECKHYP                    1062
#define IDC_PARANTHESLEVEL              1063
#define IDC_MEMORYINDICATOR             1064
#define IDC_EDITPRECISION               1065
#define IDC_RADIOQWORD                  1066
#define IDC_RADIODWORD                  1067
#define IDC_RADIOWORD                   1068
#define IDC_RADIOBYTE                   1069
#define IDC_DEBUGCHAR                   1070
#define IDC_INFO                        1071
#define ID_FILE_QUIT                    32771
#define ID_CONTROL_WHATSTHIS            32772
#define ID_VIEW_HEX                     32780
#define ID_VIEW_DEC                     32781
#define ID_VIEW_OCT                     32782
#define ID_VIEW_BIN                     32783
#define ID_VIEW_RADIANS                 32784
#define ID_VIEW_GRADS                   32785
#define ID_VIEW_DEGREES                 32786
#define ID_VIEW_BYTE                    32787
#define ID_VIEW_WORD                    32788
#define ID_VIEW_DWORD                   32789
#define ID_VIEW_QWORD                   32790
#define ID_VIEW_DIGITGROUPING           32791
#define ID_VIEW_PRECISION               32792
#define ID_HELP_ABOUT                   32793
#define ID_ADD                          32800
#define ID_SUB                          32801
#define ID_MULT                         32802
#define ID_DIV                          32803
#define ID_MOD                          32804
#define ID_SQUARE                       32805
#define ID_POW3                         32806
#define ID_POW                          32807
#define ID_LN                           32808
#define ID_LOG                          32809
#define ID_SIN                          32810
#define ID_COS                          32811
#define ID_TAN                          32812
#define ID_PI                           32813
#define ID_RECIPROC                     32814
#define ID_FAC                          32815
#define ID_DMS                          32816
#define ID_SIGN                         32817
#define ID_NUMBER0                      32818
#define ID_NUMBER1                      32819
#define ID_NUMBER2                      32820
#define ID_NUMBER3                      32821
#define ID_NUMBER4                      32822
#define ID_NUMBER5                      32823
#define ID_NUMBER6                      32824
#define ID_NUMBER7                      32825
#define ID_NUMBER8                      32826
#define ID_NUMBER9                      32827
#define ID_NUMBERA                      32828
#define ID_NUMBERB                      32829
#define ID_NUMBERC                      32830
#define ID_NUMBERD                      32831
#define ID_NUMBERE                      32832
#define ID_NUMBERF                      32833
#define ID_COMMA                        32834
#define ID_EQUAL                        32835
#define ID_CE                           32836
#define ID_CLEAR                        32837
#define ID_BACK                         32838
#define ID_EE                           32839
#define ID_AND                          32840
#define ID_OR                           32841
#define ID_XOR                          32842
#define ID_NOT                          32843
#define ID_LSH                          32844
#define ID_INT                          32845
#define ID_LPAR                         32846
#define ID_RPAR                         32847
#define ID_SHOWINFO                     32848
#define ID_GOTOPRECISION                32849

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
