//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ShowGraf.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_BITMAP_POLYNOMIAL           103
#define IDB_BITMAP_EXPO_FUNCTION        104
#define IDB_BITMAP_POTENS_FUNCTION      105
#define IDB_BITMAP_CUSTOM_FUNCTION      106
#define IDR_MENU_FUNCTION_DIALOG        110
#define IDR_MENU_PARAMETRIC_DIALOG      111
#define IDR_MENU_ISOCURVE_DIALOG        112
#define IDR_MENU_DIFFEQUATION_DIALOG    113
#define IDR_MAINFRAME                   128
#define IDR_DUMMYTOOLBAR                129
#define IDD_SHOWGRAFVIEW                130
#define IDD_DATAGRAPH_DIALOG            131
#define IDD_FUNCTIONGRAPH_DIALOG        132
#define IDD_PARAMETRICGRAPH_DIALOG      133
#define IDD_ISOCURVEGRAPH_DIALOG        134
#define IDD_DIFFEQUATIONGRAPH_DIALOG    135
#define IDD_DEGREE_DIALOG               136
#define IDD_FITTHREAD_DIALOG            137
#define IDD_INTERVAL_DIALOG             138
#define IDD_ROLLSIZE_DIALOG             139
#define IDR_ACCELERATOR_FUNCTION        140
#define IDR_ACCELERATOR_PARAMETRIC      141
#define IDR_ACCELERATOR_ISOCURVE        142
#define IDR_ACCELERATOR_DIFFEQUATION    143
#define IDR_ACCELERATOR_INTERVAL        144
#define IDR_ACCELERATOR_FITTING         145
#define IDR_MENUSELECTGRAF              150
#define IDC_SYSTEMPANEL                 1001
#define IDC_BUTTONPANEL                 1002
#define IDC_STATICDASH                  1011
#define IDC_STATICSTEPS                 1012
#define IDC_STATICINTERVAL              1013
#define IDC_STATICEXPRLABEL             1014
#define IDC_STATICEQUALZERO             1015
#define IDC_STATICXINTERVAL             1016
#define IDC_STATICYINTERVAL             1017
#define IDC_STATICDASH2                 1018
#define IDC_EDITSTEPS                   1019
#define IDC_EDITROLLSIZE                1020
#define IDC_EDITEXPR                    1021
#define IDC_EDITXFROM                   1022
#define IDC_EDITXTO                     1023
#define IDC_EDITYFROM                   1024
#define IDC_EDITYTO                     1025
#define IDC_EDITNAME                    1026
#define IDC_STATICEPS                   1069
#define IDC_EDITCELLSIZE                1070
#define IDC_EDITMAXERROR                1071
#define IDC_BUTTONADDEQ                 1072
#define IDC_COMBOSTYLE                  1073
#define IDC_BUTTONCOLOR                 1074
#define IDC_BUTTONRESTART               1075
#define IDC_BUTTONSTEP                  1076
#define IDC_BUTTONSOLVE                 1077
#define IDC_BUTTONSTOP                  1078
#define IDC_BUTTONPLOT                  1079
#define IDC_DATALIST                    1080
#define IDC_SPINDEGREE                  1081
#define IDC_EDITDEGREE                  1082
#define IDC_STATICCELLSIZE              1084
#define IDC_STATICBOUNDINGBOX           1085
#define IDC_LISTERRORS                  1093
#define IDC_STATICADJUSTSET             1095
#define IDC_STATICEXPRXLABEL            1096
#define IDC_STATICEXPRYLABEL            1097
#define IDC_EDITEXPRX                   1098
#define IDC_EDITEXPRY                   1099
#define IDC_STATICTINTERVAL             1100
#define IDC_EDITTFROM                   1101
#define IDC_EDITTTO                     1102
#define ID_FILE_SAVEAS                  32771
#define ID_FILE_EXIT                    32772
#define ID_VIEW_GRID                    32781
#define ID_VIEW_ROLLAVERAGE             32782
#define ID_VIEW_SETROLLSIZE             32783
#define ID_VIEW_SCALE_X_LINEAR          32790
#define ID_VIEW_SCALE_X_LOGARITHMIC     32791
#define ID_VIEW_SCALE_X_NORMALDIST      32792
#define ID_VIEW_SCALE_X_DATETIME        32793
#define ID_EDIT_FINDMATCHINGPARENTESIS  32794
#define ID_EDIT_NEXTERROR               32795
#define ID_EDIT_PREVERROR               32796
#define ID_VIEW_SCALE_Y_LINEAR          32800
#define ID_VIEW_SCALE_Y_LOGARITHMIC     32801
#define ID_VIEW_SCALE_Y_NORMALDIST      32802
#define ID_VIEW_SCALE_Y_DATETIME        32803
#define ID_VIEW_SCALE_RESETSCALE        32810
#define ID_VIEW_STYLE_CURVE             32820
#define ID_VIEW_STYLE_COLUMN            32821
#define ID_VIEW_STYLE_POINT             32822
#define ID_VIEW_STYLE_CROSS             32823
#define ID_VIEW_INTERVAL                32830
#define ID_VIEW_RETAINASPECTRATIO       32831
#define ID_VIEW_REFRESHFILES            32832
#define ID_TOOLS_FIT_POLYNOMIAL         32840
#define ID_TOOLS_FIT_EXPO_FUNCTION      32841
#define ID_TOOLS_FIT_POTENS_FUNCTION    32842
#define ID_TOOLS_FIT_CUSTOM_FUNCTION    32843
#define ID_TOOLS_PLOTFUNCTION           32850
#define ID_TOOLS_PARAMETRICCURVE        32851
#define ID_TOOLS_IMPLICITDEFINEDCURVE   32852
#define ID_TOOLS_DIFFERENTIALEQUATIONS  32853
#define ID_OPTIONS_IGNOREERRORS         32860
#define ID_OPTIONS_DEGREES              32861
#define ID_OPTIONS_RADIANS              32862
#define ID_OPTIONS_GRADS                32863
#define ID_HELP_ABOUT                   32870
#define ID_SELECTMENU_DELETE            32880
#define ID_SELECTMENU_EDIT              32881
#define ID_SELECTMENU_HIDE              32882
#define ID_SELECTMENU_SHOW              32883
#define ID_INDICATOR_POSITION           32890
#define ID_GOTO_XINTERVAL               32900
#define ID_GOTO_YINTERVAL               32901
#define ID_GOTO_TINTERVAL               32902
#define ID_GOTO_NAME                    32903
#define ID_GOTO_EXPR                    32904
#define ID_GOTO_EXPRX                   32905
#define ID_GOTO_EXPRY                   32906
#define ID_GOTO_STEP                    32907
#define ID_GOTO_CELLSIZE                32908
#define ID_GOTO_STYLE                   32909
#define ID_GOTO_MAXERROR                32910

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         32920
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           153
#endif
#endif
