//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ShowGraf.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_BITMAP_POLYNOMIAL           103
#define IDB_BITMAP_EXPO_FUNCTION        104
#define IDB_BITMAP_POTENS_FUNCTION      105
#define IDB_BITMAP_CUSTOM_FUNCTION      106
#define IDR_MAINFRAME                   128
#define IDR_DUMMYTOOLBAR                129
#define IDD_SHOWGRAFVIEW                130
#define IDD_DATAGRAPH_DIALOG            131
#define IDR_FUNCTION                    132
#define IDR_PARAMETRICCURVE             133
#define IDR_ISOCURVE                    134
#define IDR_DIFFEQUATION                135
#define IDD_DEGREE_DIALOG               136
#define IDR_CUSTOMFIT                   137
#define IDR_INTERVAL                    138
#define IDD_ROLLINGAVG_DIALOG           139
#define IDR_MENUSELECTGRAF              150
#define IDC_SYSTEMPANEL                 1001
#define IDC_BUTTONPANEL                 1002
#define IDC_STATICDASH                  1011
#define IDC_STATICSTEPS                 1012
#define IDC_STATICINTERVAL              1013
#define IDC_STATICEXPRLABEL             1014
#define IDC_STATICEQUALZERO             1015
#define IDC_STATICXINTERVAL             1016
#define IDC_STATICYINTERVAL             1017
#define IDC_STATICDASH2                 1018
#define IDC_EDITSTEPS                   1019
#define IDC_CHECKENABLEROLLINGAVG       1020
#define IDC_EDITROLLINGQUEUESIZE        1021
#define IDC_EDITROLLINGQUEUESIZESPIN    1022
#define IDC_EDITEXPR                    1030
#define IDC_EDITXFROM                   1040
#define IDC_EDITXTO                     1041
#define IDC_EDITYFROM                   1042
#define IDC_EDITYTO                     1043
#define IDC_EDITNAME                    1044
#define IDC_STATICEPS                   1060
#define IDC_EDITCELLSIZE                1070
#define IDC_EDITMAXERROR                1071
#define IDC_BUTTONADDEQ                 1072
#define IDC_COMBOSTYLE                  1073
#define IDC_BUTTONCOLOR                 1074
#define IDC_CHECKCREATELISTFILE         1075
#define IDC_BUTTONRESTART               1076
#define IDC_BUTTONSTEP                  1077
#define IDC_BUTTONSOLVE                 1078
#define IDC_BUTTONSTOP                  1079
#define IDC_BUTTONPLOT                  1080
#define IDC_DATALIST                    1081
#define IDC_SPINDEGREE                  1082
#define IDC_EDITDEGREE                  1083
#define IDC_STATICCELLSIZE              1084
#define IDC_STATICBOUNDINGBOX           1085
#define IDC_LISTERRORS                  1093
#define IDC_STATICADJUSTSET             1095
#define IDC_STATICEXPRXLABEL            1096
#define IDC_STATICEXPRYLABEL            1097
#define IDC_EDITEXPRX                   1098
#define IDC_EDITEXPRY                   1099
#define IDC_STATICTINTERVAL             1100
#define IDC_EDITTFROM                   1101
#define IDC_EDITTTO                     1102
#define IDC_STATICCOMMONLABEL           1103
#define IDC_EDITCOMMON                  1104
#define IDC_BUTTON_HELP                 1110
#define IDC_BUTTON_HELPX                1111
#define IDC_BUTTON_HELPY                1112
#define ID_FILE_SAVEAS                  32771
#define ID_FILE_EXIT                    32772
#define ID_EDIT_FINDMATCHINGPARENTESIS  32794
#define ID_EDIT_NEXTERROR               32795
#define ID_EDIT_PREVERROR               32796
#define ID_X_SCALE_LINEAR               32800
#define ID_X_SCALE_LOGARITHMIC          32801
#define ID_X_SCALE_NORMALDIST           32802
#define ID_X_SCALE_DATETIME             32803
#define ID_X_SHOWVALUES                 32804
#define ID_X_SHOWVALUEMARKS             32805
#define ID_X_SHOWGRIDLINES              32806
#define ID_Y_SCALE_LINEAR               32810
#define ID_Y_SCALE_LOGARITHMIC          32811
#define ID_Y_SCALE_NORMALDIST           32812
#define ID_Y_SCALE_DATETIME             32813
#define ID_Y_SHOWVALUES                 32814
#define ID_Y_SHOWVALUEMARKS             32815
#define ID_Y_SHOWGRIDLINES              32816
#define ID_BOTH_SCALE_LINEAR            32820
#define ID_BOTH_SCALE_LOGARITHMIC       32821
#define ID_BOTH_SCALE_NORMALDIST        32822
#define ID_BOTH_SCALE_DATETIME          32823
#define ID_BOTH_SHOWVALUES              32824
#define ID_BOTH_SHOWVALUEMARKS          32825
#define ID_BOTH_SHOWGRIDLINES           32826
#define ID_VIEW_SCALE_RESETSCALE        32830
#define ID_VIEW_STYLE_CURVE             32840
#define ID_VIEW_STYLE_COLUMN            32841
#define ID_VIEW_STYLE_POINT             32842
#define ID_VIEW_STYLE_CROSS             32843
#define ID_VIEW_INTERVAL                32850
#define ID_VIEW_ROLLINGAVG              32851
#define ID_VIEW_RETAINASPECTRATIO       32852
#define ID_VIEW_REFRESHFILES            32853
#define ID_TOOLS_FIT_POLYNOMIAL         32860
#define ID_TOOLS_FIT_EXPO_FUNCTION      32861
#define ID_TOOLS_FIT_POTENS_FUNCTION    32862
#define ID_TOOLS_FIT_CUSTOM_FUNCTION    32863
#define ID_TOOLS_PLOTFUNCTION           32870
#define ID_TOOLS_PARAMETRICCURVE        32871
#define ID_TOOLS_IMPLICITDEFINEDCURVE   32872
#define ID_TOOLS_DIFFERENTIALEQUATIONS  32873
#define ID_FIND_ZEROES                  32880
#define ID_FIND_MINIMUM                 32881
#define ID_FIND_MAXIMUM                 32882
#define ID_FIND_INTERSECTION            32883
#define ID_OPTIONS_IGNOREERRORS         32900
#define ID_OPTIONS_DEGREES              32901
#define ID_OPTIONS_RADIANS              32902
#define ID_OPTIONS_GRADS                32903
#define ID_HELP_ABOUT                   32920
#define ID_SELECTMENU_DELETE            32950
#define ID_SELECTMENU_EDIT              32951
#define ID_SELECTMENU_HIDE              32952
#define ID_SELECTMENU_SHOW              32953
#define ID_SELECTMENU_STYLE_CURVE       32954
#define ID_SELECTMENU_STYLE_POINT       32955
#define ID_SELECTMENU_STYLE_CROSS       32956
#define ID_INDICATOR_POSITION           32970
#define ID_GOTO_XINTERVAL               33000
#define ID_GOTO_YINTERVAL               33001
#define ID_GOTO_TINTERVAL               33002
#define ID_GOTO_NAME                    33003
#define ID_GOTO_EXPR                    33004
#define ID_GOTO_EXPRX                   33005
#define ID_GOTO_EXPRY                   33006
#define ID_GOTO_STEP                    33007
#define ID_GOTO_CELLSIZE                33008
#define ID_GOTO_STYLE                   33009
#define ID_GOTO_COMMON                  33010
#define ID_GOTO_MAXERROR                33011
#define ID_MSG_PUSHDRAGTOOL             33100
#define ID_MSG_PUSHMOVEPOINTTOOL        33101
#define ID_MSG_POPMOUSETOOL             33102
#define ID_MSG_SEARCHZEROESININTERVAL   33103
#define ID_MSG_SEARCHMAXININTERVAL      33104
#define ID_MSG_SEARCHMINININTERVAL      33105
#define ID_MSG_SEARCHINTERSECTIONSININTERVAL 33105

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         33111
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           153
#endif
#endif
