/* DO NOT EDIT THIS FILE - it is machine generated */

#line 33 "C:\\Mytools2015\\ParserGen\\Olm627\\Olm627.y"
#include "stdafx.h"
#include "Olm627Parser.h"
#line 20 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
#line 23 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
#pragma warning(disable : 4060) // warning C4060: switch statement contains no 'case' or 'default' labels

int Olm627Parser::reduceAction(unsigned int prod) {
  switch(prod) {
  }
#line 30 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
  return 0;
}

#line 55 "C:\\Mytools2015\\ParserGen\\Olm627\\Olm627.y"
#line 33 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
