#define _EOI_      0
#define STRING     1
#define ICON       2
#define FCON       3
#define TYPE       4
#define STRUCT     5
#define ENUM       6
#define RETURN     7
#define GOTO       8
#define IF         9
#define ELSE       10
#define SWITCH     11
#define CASE       12
#define DEFAULT    13
#define BREAK      14
#define CONTINUE   15
#define WHILE      16
#define DO         17
#define FOR        18
#define LC         19
#define RC         20
#define SEMI       21
#define ELLIPSIS   22
#define COMMA      23
#define EQUAL      24
#define ASSIGNOP   25
#define QUEST      26
#define COLON      27
#define OROR       28
#define ANDAND     29
#define OR         30
#define XOR        31
#define AND        32
#define EQUOP      33
#define RELOP      34
#define SHIFTOP    35
#define PLUS       36
#define MINUS      37
#define STAR       38
#define DIVOP      39
#define SIZEOF     40
#define UNOP       41
#define INCOP      42
#define LB         43
#define RB         44
#define LP         45
#define RP         46
#define STRUCTOP   47
#define TTYPE      48
#define CLASS      49
#define NAME       50
#define DEFINE     51
#define HASHMARK   52
