//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HexView.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_HEXVIETYPE                  129
#define IDD_DIALOGFIND                  130
#define IDD_DIALOGFINDNEXTPREV          131
#define IDD_DIALOGLINESIZE              132
#define IDD_DIALOGENTERADDR             133
#define IDR_ACCELERATORFIND             134
#define IDR_ACCELERATORNEXTPREV         135
#define IDR_ACCELERATORLINESIZE         136
#define IDR_ACCELERATORENTERADDR        137
#define IDR_MENUSPECIALCHAR             138
#define IDC_EDITLINESIZE                1000
#define IDC_EDITADDRESS                 1001
#define IDC_COMBOFINDWHAT               1002
#define IDC_RADIOUP                     1003
#define IDC_RADIODOWN                   1004
#define IDC_FINDNEXT                    1005
#define IDC_BUTTONSPECIALCHAR           1006
#define IDC_STATICBYTESEQUENCE          1007
#define IDC_STATICRADIXNAME             1008
#define IDC_STATICDIRECTIONFRAME        1009
#define IDC_STATICADDRLABEL             1011
#define IDC_PROGRESSFIND                1012
#define IDC_STATICFINDLABEL             1014
#define IDC_EDITFINDWHAT                1015
#define IDC_CHECKFITLINES               1016
#define IDC_STATICLINESIZE              1017
#define IDC_PCTPROGRESS                 1018
#define ID_INDICATOR_POSITION           32780
#define ID_INDICATOR_READONLY           32781
#define ID_INDICATOR_DEBUG              32782
#define ID_FILE_OPENFORUPDATE           32790
#define ID_FILE_CLOSEDOC                32791
#define ID_FILE_SAVEDOC                 32792
#define ID_FILE_SAVEDOC_AS              32793
#define ID_EDIT_ALLOWEDIT               32800
#define ID_EDIT_FIND_NEXT               32801
#define ID_EDIT_FIND_PREV               32802
#define ID_EDIT_GOTOADDRESS             32803
#define ID_EDIT_REFRESHFILE             32804
#define ID_VIEW_DATAOCT                 32810
#define ID_VIEW_DATADEC                 32811
#define ID_VIEW_DATAHEX3POS             32812
#define ID_VIEW_DATAHEX2POS             32813
#define ID_VIEW_SHOWASCII               32814
#define ID_VIEW_DATAHEXUPPERCASE        32815
#define ID_VIEW_SHOWADDR                32816
#define ID_VIEW_ADDROCT                 32817
#define ID_VIEW_ADDRDEC                 32818
#define ID_VIEW_ADDRHEX                 32819
#define ID_VIEW_ADDRHEXUPPERCASE        32820
#define ID_VIEW_ADDRSEPARATORS          32821
#define ID_VIEW_LINESIZE                32822
#define ID_VIEW_COLORS_DATATEXT         32823
#define ID_VIEW_COLORS_DATABACK         32824
#define ID_VIEW_COLORS_ASCIITEXT        32825
#define ID_VIEW_COLORS_ASCIIBACK        32826
#define ID_VIEW_COLORS_ADDRTEXT         32827
#define ID_VIEW_COLORS_ADDRBACK         32828
#define ID_VIEW_WRAPENDOFLINE           32829
#define ID_ACTIVATE_SETTINGS            32840
#define ID_GOTO_FINDWHAT                32841
#define ID_GOTO_EDITADDRESS             32842
#define ID_GOTO_LINESIZE                32843
#define ID_SPECIALCHAR_BACKSPACE        32850
#define ID_SPECIALCHAR_TAB              32851
#define ID_SPECIALCHAR_NEWLINE          32852
#define ID_SPECIALCHAR_FORMFEED         32853
#define ID_SPECIALCHAR_CARRIAGERETURN   32854
#define ID_SPECIALCHAR_ESCCHARACTER     32855
#define ID_SPECIALCHAR_OCTNUMBER        32856
#define ID_SPECIALCHAR_DECNUMBER        32857
#define ID_SPECIALCHAR_HEXNUMBER        32858
#define ID_SPECIALCHAR_BACKSLASH        32859
#define ID_CHARLEFT                     32870
#define ID_CHARRIGHT                    32871
#define ID_CTRLCHARLEFT                 32872
#define ID_CTRLCHARRIGHT                32873
#define ID_LINEUP                       32874
#define ID_LINEDOWN                     32875
#define ID_HOME                         32876
#define ID_END                          32877
#define ID_CTRLHOME                     32878
#define ID_CTRLEND                      32879
#define ID_PAGELEFT                     32880
#define ID_PAGERIGHT                    32881
#define ID_PAGEUP                       32882
#define ID_PAGEDOWN                     32883
#define ID_SHIFT_CHARLEFT               32890
#define ID_SHIFT_CHARRIGHT              32891
#define ID_SHIFT_CTRLCHARLEFT           32892
#define ID_SHIFT_CTRLCHARRIGHT          32893
#define ID_SHIFT_LINEUP                 32894
#define ID_SHIFT_LINEDOWN               32895
#define ID_SHIFT_HOME                   32896
#define ID_SHIFT_END                    32897
#define ID_SHIFT_CTRLHOME               32898
#define ID_SHIFT_CTRLEND                32899
#define ID_SHIFT_PAGELEFT               32900
#define ID_SHIFT_PAGERIGHT              32901
#define ID_SHIFT_PAGEUP                 32902
#define ID_SHIFT_PAGEDOWN               32903

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32908
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
