/* DO NOT EDIT THIS FILE - it is machine generated */
#line 47 "C:\\mytools2015\\Lib\\Src\\Expression\\Expression.y"
#include "pch.h"
#include <Math/Real.h>
#include <Math/Expression/ExpressionParser.h>

#pragma warning(disable:4312)


#line 33 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"

#pragma warning(disable : 4312)

typedef short TableType;

/****************************************************************************\
* Bitset containing 1-bits for compressed states and 0-bits for              *
* uncompressed states. Used by ParserTable to determine how to               *
* interpret the entry in the action-table                                    *
* Number of bytes in bitset = (statecount-1)/8+1                             *
\****************************************************************************/
static const BYTE compressedSet[20] = { 0xc6,0x1e,0xef,0xff,0xff,0xff,0xff,0xbf,0xff,0x3f,0x00,0x10,0x04,0x16,0x04,0xc2,0x3a,0x21,0x20,0x60
}; // Size of table:20 bytes.

/****************************************************************************\
* The action matrix holds the parse action(state,terminal)                   *
* Used in LRParser::parserStep().                                            *
* 2 different formats are used:Compressed and Uncompressed.                  *
*                                                                            *
* Compressed:When there is only 1 possible action in the state.              *
*            or all actions are reduce by the same production.               *
*   If bit 16 (0x8000) is 0, there is only one possible action which is      *
*   encoded as:                                                              *
*      #define   act0001  (void*)((action << 16) | (token&0x7fff)            *
*   State index------+               |                |                      *
*   Highorder 16 bits = action-------+                |                      *
*   Loworder  15 bits = legal token-------------------+                      *
*                                                                            *
*   If bit 16 is 1, the loworder 15 bits is an index.                        *
*      #define   act0002  (void*)((action<<16)  |  0x8000 | (index&0x7fff))  *
*   State index------+               |                |        |             *
*   Highorder 16 bits = action-------+                |        |             *
*   Indicates that this is a multi-item-action-state--+        |             *
*   Loworder  15 bits = index into compressedLasets------------+             *
*                                                                            *
* compressedLasets contains all unique legal lookahead-sets for all          *
* multi-item-action-states.                                                  *
* Number of bytes in each bitset = (terminalcount-1)/8+1                     *
*                                                                            *
* Uncompressed states:                                                       *
*      TableType act0004[] =      { 3, 1, 2, 2,-2, 6, 1 };                   *
*   State index------+              |  |  |                                  *
*   Number of pairs in list---------+  |  |                                  *
*   Legal input symbol-----------------+  |                                  *
*   Action--------------------------------+                                  *
*                                                                            *
* If any uncompressed state has the same actionarray as a previous           *
* generated uncompressed state, a #define is generated to save space.        *
*                                                                            *
*                                                                            *
*   action = getAction(current state, current inputSymbol);                  *
*                                                                            *
*   action <  0   - Reduce by production p, p == -action.                    *
*   action == 0   - Accept. Reduce by production 0.                          *
*   action >  0   - Go to state s (=action),                                 *
*                   and push [s,input,pos] to parser stack.                  *
*                   Then read next symbol from input.                        *
*   action == _ParserError - not found (=unexpected input).                  *
\****************************************************************************/
static const BYTE compressedLasets[44] = {
  /*  0  59 tokens */  0x16,0x4c,0xc0,0xe0,0xff,0xff,0xff,0xff,0xff,0x7f,0x01
  /*  1  20 tokens */ ,0x81,0xb3,0xdf,0x1e,0x00,0x00,0x00,0x00,0x00,0x80,0x02
  /*  2  21 tokens */ ,0xc1,0xb3,0xdf,0x1e,0x00,0x00,0x00,0x00,0x00,0x80,0x02
  /*  3   6 tokens */ ,0x01,0x31,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x80,0x02
}; // Size of table:44 bytes.

#define act0001 (void*)0x00000000    /* reduce by 0 on EOI                       */
#define act0002 (void*)0xffff0000    /* reduce by 1 on EOI                       */
#define act0006 (void*)0xfffb8000    /* reduce by 5 on tokens in set[0]          */
#define act0007 (void*)0x005c0007    /* shift to 92 on SEMI                      */
#define act0009 (void*)0xfff1800b    /* reduce by 15 on tokens in set[1]         */
#define act0010 (void*)0xfff0800b    /* reduce by 16 on tokens in set[1]         */
#define act0011 (void*)0x005e004e    /* shift to 94 on LPAR                      */
#define act0012 (void*)0x005f004e    /* shift to 95 on LPAR                      */
#define act0016 (void*)0xffe9800b    /* reduce by 23 on tokens in set[1]         */
#define act0017 (void*)0xffe8800b    /* reduce by 24 on tokens in set[1]         */
#define act0018 (void*)0xffe7800b    /* reduce by 25 on tokens in set[1]         */
#define act0019 (void*)0xffe6800b    /* reduce by 26 on tokens in set[1]         */
#define act0021 (void*)0x0068004e    /* shift to 104 on LPAR                     */
#define act0022 (void*)0x0069004e    /* shift to 105 on LPAR                     */
#define act0023 (void*)0x006a004e    /* shift to 106 on LPAR                     */
#define act0024 (void*)0x006b0050    /* shift to 107 on LB                       */
#define act0025 (void*)0xffde004e    /* reduce by 34 on LPAR                     */
#define act0026 (void*)0xffdd004e    /* reduce by 35 on LPAR                     */
#define act0027 (void*)0xffdc004e    /* reduce by 36 on LPAR                     */
#define act0028 (void*)0xffdb004e    /* reduce by 37 on LPAR                     */
#define act0029 (void*)0xffda004e    /* reduce by 38 on LPAR                     */
#define act0030 (void*)0xffd9004e    /* reduce by 39 on LPAR                     */
#define act0031 (void*)0xffd8004e    /* reduce by 40 on LPAR                     */
#define act0032 (void*)0xffd7004e    /* reduce by 41 on LPAR                     */
#define act0033 (void*)0xffd6004e    /* reduce by 42 on LPAR                     */
#define act0034 (void*)0xffd5004e    /* reduce by 43 on LPAR                     */
#define act0035 (void*)0xffd4004e    /* reduce by 44 on LPAR                     */
#define act0036 (void*)0xffd3004e    /* reduce by 45 on LPAR                     */
#define act0037 (void*)0xffd2004e    /* reduce by 46 on LPAR                     */
#define act0038 (void*)0xffd1004e    /* reduce by 47 on LPAR                     */
#define act0039 (void*)0xffd0004e    /* reduce by 48 on LPAR                     */
#define act0040 (void*)0xffcf004e    /* reduce by 49 on LPAR                     */
#define act0041 (void*)0xffce004e    /* reduce by 50 on LPAR                     */
#define act0042 (void*)0xffcd004e    /* reduce by 51 on LPAR                     */
#define act0043 (void*)0xffcc004e    /* reduce by 52 on LPAR                     */
#define act0044 (void*)0xffcb004e    /* reduce by 53 on LPAR                     */
#define act0045 (void*)0xffca004e    /* reduce by 54 on LPAR                     */
#define act0046 (void*)0xffc9004e    /* reduce by 55 on LPAR                     */
#define act0047 (void*)0xffc8004e    /* reduce by 56 on LPAR                     */
#define act0048 (void*)0xffc7004e    /* reduce by 57 on LPAR                     */
#define act0049 (void*)0xffc6004e    /* reduce by 58 on LPAR                     */
#define act0050 (void*)0xffc5004e    /* reduce by 59 on LPAR                     */
#define act0051 (void*)0xffc4004e    /* reduce by 60 on LPAR                     */
#define act0052 (void*)0xffc3004e    /* reduce by 61 on LPAR                     */
#define act0053 (void*)0xffc2004e    /* reduce by 62 on LPAR                     */
#define act0054 (void*)0xffc1004e    /* reduce by 63 on LPAR                     */
#define act0055 (void*)0xffc0004e    /* reduce by 64 on LPAR                     */
#define act0056 (void*)0xffbf004e    /* reduce by 65 on LPAR                     */
#define act0057 (void*)0xffbe004e    /* reduce by 66 on LPAR                     */
#define act0058 (void*)0xffbd004e    /* reduce by 67 on LPAR                     */
#define act0059 (void*)0xffbc004e    /* reduce by 68 on LPAR                     */
#define act0060 (void*)0xffbb004e    /* reduce by 69 on LPAR                     */
#define act0061 (void*)0xffba004e    /* reduce by 70 on LPAR                     */
#define act0063 (void*)0xffaf004e    /* reduce by 81 on LPAR                     */
#define act0064 (void*)0xffae004e    /* reduce by 82 on LPAR                     */
#define act0065 (void*)0xffad004e    /* reduce by 83 on LPAR                     */
#define act0066 (void*)0xffac004e    /* reduce by 84 on LPAR                     */
#define act0067 (void*)0xffab004e    /* reduce by 85 on LPAR                     */
#define act0068 (void*)0xffaa004e    /* reduce by 86 on LPAR                     */
#define act0069 (void*)0xffa9004e    /* reduce by 87 on LPAR                     */
#define act0070 (void*)0xffa8004e    /* reduce by 88 on LPAR                     */
#define act0071 (void*)0xffa7004e    /* reduce by 89 on LPAR                     */
#define act0072 (void*)0xffa6004e    /* reduce by 90 on LPAR                     */
#define act0073 (void*)0xffa5004e    /* reduce by 91 on LPAR                     */
#define act0074 (void*)0xffa48016    /* reduce by 92 on tokens in set[2]         */
#define act0075 (void*)0xffa3800b    /* reduce by 93 on tokens in set[1]         */
#define act0076 (void*)0xfffe0000    /* reduce by 2 on EOI                       */
#define act0077 (void*)0xfffa8000    /* reduce by 6 on tokens in set[0]          */
#define act0092 (void*)0xfff98000    /* reduce by 7 on tokens in set[0]          */
#define act0098 (void*)0xffef800b    /* reduce by 17 on tokens in set[1]         */
#define act0105 (void*)0x004a0002    /* shift to 74 on NAME                      */
#define act0106 (void*)0x004a0002    /* shift to 74 on NAME                      */
#define act0108 (void*)0xffb18021    /* reduce by 79 on tokens in set[3]         */
#define act0114 (void*)0xfff2800b    /* reduce by 14 on tokens in set[1]         */
#define act0121 (void*)0xffb38021    /* reduce by 77 on tokens in set[3]         */
#define act0126 (void*)0xffec800b    /* reduce by 20 on tokens in set[1]         */
#define act0127 (void*)0xffb08021    /* reduce by 80 on tokens in set[3]         */
#define act0129 (void*)0xffe5800b    /* reduce by 27 on tokens in set[1]         */
#define act0131 (void*)0x008b0009    /* shift to 139 on TO                       */
#define act0132 (void*)0x005d0006    /* shift to 93 on ASSIGN                    */
#define act0133 (void*)0x008c0009    /* shift to 140 on TO                       */
#define act0136 (void*)0xffee800b    /* reduce by 18 on tokens in set[1]         */
#define act0141 (void*)0x0093004e    /* shift to 147 on LPAR                     */
#define act0149 (void*)0xffed800b    /* reduce by 19 on tokens in set[1]         */
#define act0157 (void*)0xffe1800b    /* reduce by 31 on tokens in set[1]         */
#define act0158 (void*)0xffe4800b    /* reduce by 28 on tokens in set[1]         */

static const TableType act0000[] = {  59,   1,  75,   2,  74,   4,  21,  10,  22,  11,  23
                                        ,  14,  62,  22,  15,  23,  14,  29,  26,  30,  27
                                        ,  31,  28,  32,  29,  33,  30,  34,  31,  35,  32
                                        ,  36,  33,  37,  72,  38,  34,  39,  36,  40,  37
                                        ,  41,  38,  42,  39,  43,  54,  44,  56,  45,  57
                                        ,  46,  60,  47,  61,  48,  25,  49,  35,  50,  40
                                        ,  51,  41,  52,  42,  53,  43,  54,  44,  55,  45
                                        ,  56,  73,  57,  46,  58,  47,  59,  48,  60,  49
                                        ,  61,  50,  62,  51,  63,  52,  64,  53,  65,  70
                                        ,  66,  69,  67,  71,  68,  67,  69,  55,  70,  58
                                        ,  71,  59,  72,  68,  73,  63,  74,  64,  75,  65
                                        ,  76,  24,  77,  66,  78,  13,  80,  20};
static const TableType act0004[] = {  13,   0,  -3,  15,  84,  16,  88,  17,  89,  18,  86
                                        ,  19,  87,  20,  85,  22,  78,  23,  79,  25,  80
                                        ,  26,  81,  27,  82,  28,  83};
static const TableType act0005[] = {   3,   0,  -4,  12,  91,  13,  90};
static const TableType act0008[] = {  14,   0, -17,   6,  93,  15, -17,  16, -17,  17, -17
                                        ,  18, -17,  19, -17,  20, -17,  22, -17,  23, -17
                                        ,  25, -17,  26, -17,  27, -17,  28, -17};
static const TableType act0014[] = {  58,   1,  75,   2,  74,   4,  21,  10,  22,  11,  23
                                        ,  22,  15,  23,  14,  29,  26,  30,  27,  31,  28
                                        ,  32,  29,  33,  30,  34,  31,  35,  32,  36,  33
                                        ,  37,  72,  38,  34,  39,  36,  40,  37,  41,  38
                                        ,  42,  39,  43,  54,  44,  56,  45,  57,  46,  60
                                        ,  47,  61,  48,  25,  49,  35,  50,  40,  51,  41
                                        ,  52,  42,  53,  43,  54,  44,  55,  45,  56,  73
                                        ,  57,  46,  58,  47,  59,  48,  60,  49,  61,  50
                                        ,  62,  51,  63,  52,  64,  53,  65,  70,  66,  69
                                        ,  67,  71,  68,  67,  69,  55,  70,  58,  71,  59
                                        ,  72,  68,  73,  63,  74,  64,  75,  65,  76,  24
                                        ,  77,  66,  78, 100,  80,  20};
static const TableType act0096[] = {  13,  15,  84,  16,  88,  17,  89,  18,  86,  19,  87
                                        ,  20,  85,  22,  78,  23,  79,  25,  80,  26,  81
                                        ,  27,  82,  28,  83,  79, 126};
static const TableType act0097[] = {   3,  12,  91,  13,  90,  79, 127};
static const TableType act0099[] = {  20,   0, -21,   7, -21,   8, -21,   9, -21,  12, -21
                                        ,  13, -21,  15, -21,  16, -21,  17, -21,  18, -21
                                        ,  19, -21,  20, -21,  22, -21,  23, -21,  25,  80
                                        ,  26,  81,  27,  82,  28,  83,  79, -21,  81, -21};
static const TableType act0101[] = {  20,   0, -22,   7, -22,   8, -22,   9, -22,  12, -22
                                        ,  13, -22,  15, -22,  16, -22,  17, -22,  18, -22
                                        ,  19, -22,  20, -22,  22, -22,  23, -22,  25,  80
                                        ,  26,  81,  27,  82,  28,  83,  79, -22,  81, -22};
static const TableType act0102[] = {   3,  12,  91,  13,  90,  81, 129};
static const TableType act0103[] = {  12,  15,  84,  16,  88,  17,  89,  18,  86,  19,  87
                                        ,  20,  85,  22,  78,  23,  79,  25,  80,  26,  81
                                        ,  27,  82,  28,  83};
static const TableType act0109[] = {  20,   0,  -9,   7,  -9,   8,  -9,   9,  -9,  12,  -9
                                        ,  13,  -9,  15,  -9,  16,  -9,  17,  -9,  18,  -9
                                        ,  19,  -9,  20,  -9,  22,  -9,  23,  -9,  25,  80
                                        ,  26,  81,  27,  82,  28,  83,  79,  -9,  81,  -9};
static const TableType act0110[] = {  20,   0, -10,   7, -10,   8, -10,   9, -10,  12, -10
                                        ,  13, -10,  15, -10,  16, -10,  17, -10,  18, -10
                                        ,  19, -10,  20, -10,  22, -10,  23, -10,  25,  80
                                        ,  26,  81,  27,  82,  28,  83,  79, -10,  81, -10};
static const TableType act0111[] = {  20,   0, -11,   7, -11,   8, -11,   9, -11,  12, -11
                                        ,  13, -11,  15, -11,  16, -11,  17, -11,  18, -11
                                        ,  19, -11,  20, -11,  22, -11,  23, -11,  25, -11
                                        ,  26, -11,  27, -11,  28,  83,  79, -11,  81, -11};
static const TableType act0112[] = {  20,   0, -12,   7, -12,   8, -12,   9, -12,  12, -12
                                        ,  13, -12,  15, -12,  16, -12,  17, -12,  18, -12
                                        ,  19, -12,  20, -12,  22, -12,  23, -12,  25, -12
                                        ,  26, -12,  27, -12,  28,  83,  79, -12,  81, -12};
static const TableType act0113[] = {  20,   0, -13,   7, -13,   8, -13,   9, -13,  12, -13
                                        ,  13, -13,  15, -13,  16, -13,  17, -13,  18, -13
                                        ,  19, -13,  20, -13,  22, -13,  23, -13,  25, -13
                                        ,  26, -13,  27, -13,  28,  83,  79, -13,  81, -13};
static const TableType act0115[] = {  12,   0, -71,   8, -71,  12, -71,  13, -71,  22,  78
                                        ,  23,  79,  25,  80,  26,  81,  27,  82,  28,  83
                                        ,  79, -71,  81, -71};
static const TableType act0116[] = {  12,   0, -72,   8, -72,  12, -72,  13, -72,  22,  78
                                        ,  23,  79,  25,  80,  26,  81,  27,  82,  28,  83
                                        ,  79, -72,  81, -72};
static const TableType act0117[] = {  12,   0, -73,   8, -73,  12, -73,  13, -73,  22,  78
                                        ,  23,  79,  25,  80,  26,  81,  27,  82,  28,  83
                                        ,  79, -73,  81, -73};
static const TableType act0118[] = {  12,   0, -74,   8, -74,  12, -74,  13, -74,  22,  78
                                        ,  23,  79,  25,  80,  26,  81,  27,  82,  28,  83
                                        ,  79, -74,  81, -74};
static const TableType act0119[] = {  12,   0, -75,   8, -75,  12, -75,  13, -75,  22,  78
                                        ,  23,  79,  25,  80,  26,  81,  27,  82,  28,  83
                                        ,  79, -75,  81, -75};
static const TableType act0120[] = {  12,   0, -76,   8, -76,  12, -76,  13, -76,  22,  78
                                        ,  23,  79,  25,  80,  26,  81,  27,  82,  28,  83
                                        ,  79, -76,  81, -76};
static const TableType act0122[] = {   6,   0, -78,   8, -78,  12, -78,  13,  90,  79, -78
                                        ,  81, -78};
static const TableType act0123[] = {   8,   7,  -8,   9,  -8,  22,  78,  23,  79,  25,  80
                                        ,  26,  81,  27,  82,  28,  83};
static const TableType act0124[] = {   7,  22,  78,  23,  79,  25,  80,  26,  81,  27,  82
                                        ,  28,  83,  79, 136};
static const TableType act0125[] = {   7,   8, 137,  22,  78,  23,  79,  25,  80,  26,  81
                                        ,  27,  82,  28,  83};
static const TableType act0128[] = {   7,  22,  78,  23,  79,  25,  80,  26,  81,  27,  82
                                        ,  28,  83,  79, 126};
static const TableType act0130[] = {   3,   8, 138,  12,  91,  13,  90};
static const TableType act0134[] = {   2,   8, 142,  81, 141};
static const TableType act0135[] = {   8,   8, -33,  22,  78,  23,  79,  25,  80,  26,  81
                                        ,  27,  82,  28,  83,  81, -33};
static const TableType act0143[] = {   7,  22,  78,  23,  79,  25,  80,  26,  81,  27,  82
                                        ,  28,  83,  79, 149};
static const TableType act0144[] = {   7,   8, 150,  22,  78,  23,  79,  25,  80,  26,  81
                                        ,  27,  82,  28,  83};
static const TableType act0145[] = {   7,  22,  78,  23,  79,  25,  80,  26,  81,  27,  82
                                        ,  28,  83,  79, 151};
static const TableType act0146[] = {   7,  22,  78,  23,  79,  25,  80,  26,  81,  27,  82
                                        ,  28,  83,  79, 152};
static const TableType act0148[] = {   8,   8, -32,  22,  78,  23,  79,  25,  80,  26,  81
                                        ,  27,  82,  28,  83,  81, -32};
static const TableType act0153[] = {   7,  22,  78,  23,  79,  25,  80,  26,  81,  27,  82
                                        ,  28,  83,  79, 157};
static const TableType act0154[] = {   7,  22,  78,  23,  79,  25,  80,  26,  81,  27,  82
                                        ,  28,  83,  79, 158};
static const TableType act0155[] = {  20,   0, -29,   7, -29,   8, -29,   9, -29,  12, -29
                                        ,  13, -29,  15, -29,  16, -29,  17, -29,  18, -29
                                        ,  19, -29,  20, -29,  22,  78,  23,  79,  25,  80
                                        ,  26,  81,  27,  82,  28,  83,  79, -29,  81, -29};
static const TableType act0156[] = {  20,   0, -30,   7, -30,   8, -30,   9, -30,  12, -30
                                        ,  13, -30,  15, -30,  16, -30,  17, -30,  18, -30
                                        ,  19, -30,  20, -30,  22,  78,  23,  79,  25,  80
                                        ,  26,  81,  27,  82,  28,  83,  79, -30,  81, -30};

// Total size of uncompressed actNNNN tables:2268 bytes.

#define act0003 act0000 /* Saved 240 bytes */
#define act0013 act0000 /* Saved 240 bytes */
#define act0015 act0014 /* Saved 236 bytes */
#define act0020 act0000 /* Saved 240 bytes */
#define act0062 act0000 /* Saved 240 bytes */
#define act0078 act0014 /* Saved 236 bytes */
#define act0079 act0014 /* Saved 236 bytes */
#define act0080 act0014 /* Saved 236 bytes */
#define act0081 act0014 /* Saved 236 bytes */
#define act0082 act0014 /* Saved 236 bytes */
#define act0083 act0014 /* Saved 236 bytes */
#define act0084 act0014 /* Saved 236 bytes */
#define act0085 act0014 /* Saved 236 bytes */
#define act0086 act0014 /* Saved 236 bytes */
#define act0087 act0014 /* Saved 236 bytes */
#define act0088 act0014 /* Saved 236 bytes */
#define act0089 act0014 /* Saved 236 bytes */
#define act0090 act0000 /* Saved 240 bytes */
#define act0091 act0000 /* Saved 240 bytes */
#define act0093 act0014 /* Saved 236 bytes */
#define act0094 act0014 /* Saved 236 bytes */
#define act0095 act0014 /* Saved 236 bytes */
#define act0100 act0014 /* Saved 236 bytes */
#define act0104 act0000 /* Saved 240 bytes */
#define act0107 act0014 /* Saved 236 bytes */
#define act0137 act0014 /* Saved 236 bytes */
#define act0138 act0014 /* Saved 236 bytes */
#define act0139 act0014 /* Saved 236 bytes */
#define act0140 act0014 /* Saved 236 bytes */
#define act0142 act0014 /* Saved 236 bytes */
#define act0147 act0014 /* Saved 236 bytes */
#define act0150 act0014 /* Saved 236 bytes */
#define act0151 act0014 /* Saved 236 bytes */
#define act0152 act0014 /* Saved 236 bytes */

static const void *action[159] = {
   act0000,act0001,act0002,act0003,act0004,act0005,act0006,act0007,act0008,act0009
  ,act0010,act0011,act0012,act0013,act0014,act0015,act0016,act0017,act0018,act0019
  ,act0020,act0021,act0022,act0023,act0024,act0025,act0026,act0027,act0028,act0029
  ,act0030,act0031,act0032,act0033,act0034,act0035,act0036,act0037,act0038,act0039
  ,act0040,act0041,act0042,act0043,act0044,act0045,act0046,act0047,act0048,act0049
  ,act0050,act0051,act0052,act0053,act0054,act0055,act0056,act0057,act0058,act0059
  ,act0060,act0061,act0062,act0063,act0064,act0065,act0066,act0067,act0068,act0069
  ,act0070,act0071,act0072,act0073,act0074,act0075,act0076,act0077,act0078,act0079
  ,act0080,act0081,act0082,act0083,act0084,act0085,act0086,act0087,act0088,act0089
  ,act0090,act0091,act0092,act0093,act0094,act0095,act0096,act0097,act0098,act0099
  ,act0100,act0101,act0102,act0103,act0104,act0105,act0106,act0107,act0108,act0109
  ,act0110,act0111,act0112,act0113,act0114,act0115,act0116,act0117,act0118,act0119
  ,act0120,act0121,act0122,act0123,act0124,act0125,act0126,act0127,act0128,act0129
  ,act0130,act0131,act0132,act0133,act0134,act0135,act0136,act0137,act0138,act0139
  ,act0140,act0141,act0142,act0143,act0144,act0145,act0146,act0147,act0148,act0149
  ,act0150,act0151,act0152,act0153,act0154,act0155,act0156,act0157,act0158
}; // Size of table:1272 bytes.

/****************************************************************************\
* The successor matrix is used when the parser has reduced by prod A -> alfa *
* Used by LRParser to find newstate = successor(state,A).                    *
*                                                                            *
*                  succ0007[] = { 3, 5,3 , 6,2, 8,5 };                       *
*   Current state-------+         |  | |                                     *
*   Number of pairs in list ------+  | |                                     *
*   NonTerminal A--------------------+ |                                     *
*   Go to this state-------------------+                                     *
\****************************************************************************/
static const TableType succ0000[] = { 16,  83,   1,  84,   2,  85,   3,  86,   4,  87,   5
                                        ,  88,   6,  89,   7,  90,   8,  91,   9,  92,  10
                                        ,  93,  11,  94,  12,  95,  16,  96,  17,  97,  18
                                        ,  98,  19};
static const TableType succ0003[] = { 14,  84,  76,  86,   4,  87,   5,  88,  77,  89,   7
                                        ,  90,   8,  91,   9,  92,  10,  93,  11,  94,  12
                                        ,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0013[] = { 11,  86,  96,  87,  97,  90,  98,  91,   9,  92,  10
                                        ,  93,  11,  94,  12,  95,  16,  96,  17,  97,  18
                                        ,  98,  19};
static const TableType succ0014[] = { 10,  86,  99,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0015[] = { 10,  86, 101,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0020[] = { 11,  86, 103,  87, 102,  90,  98,  91,   9,  92,  10
                                        ,  93,  11,  94,  12,  95,  16,  96,  17,  97,  18
                                        ,  98,  19};
static const TableType succ0062[] = { 11,  86, 103,  87, 108,  90,  98,  91,   9,  92,  10
                                        ,  93,  11,  94,  12,  95,  16,  96,  17,  97,  18
                                        ,  98,  19};
static const TableType succ0078[] = { 10,  86, 109,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0079[] = { 10,  86, 110,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0080[] = { 10,  86, 111,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0081[] = { 10,  86, 112,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0082[] = { 10,  86, 113,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0083[] = { 10,  86, 114,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0084[] = { 10,  86, 115,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0085[] = { 10,  86, 116,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0086[] = { 10,  86, 117,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0087[] = { 10,  86, 118,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0088[] = { 10,  86, 119,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0089[] = { 10,  86, 120,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0090[] = { 11,  86, 103,  87, 121,  90,  98,  91,   9,  92,  10
                                        ,  93,  11,  94,  12,  95,  16,  96,  17,  97,  18
                                        ,  98,  19};
static const TableType succ0091[] = { 11,  86, 103,  87, 122,  90,  98,  91,   9,  92,  10
                                        ,  93,  11,  94,  12,  95,  16,  96,  17,  97,  18
                                        ,  98,  19};
static const TableType succ0093[] = { 10,  86, 123,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0094[] = { 10,  86, 124,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0095[] = { 10,  86, 125,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0100[] = { 10,  86, 128,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0104[] = { 11,  86, 103,  87, 130,  90,  98,  91,   9,  92,  10
                                        ,  93,  11,  94,  12,  95,  16,  96,  17,  97,  18
                                        ,  98,  19};
static const TableType succ0105[] = {  2,  89, 131,  90, 132};
static const TableType succ0106[] = {  2,  89, 133,  90, 132};
static const TableType succ0107[] = { 11,  86, 135,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19
                                        ,  99, 134};
static const TableType succ0137[] = { 10,  86, 143,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0138[] = { 10,  86, 144,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0139[] = { 10,  86, 145,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0140[] = { 10,  86, 146,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0142[] = { 10,  86, 148,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0147[] = { 10,  86, 153,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0150[] = { 10,  86, 154,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0151[] = { 10,  86, 155,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};
static const TableType succ0152[] = { 10,  86, 156,  90,  98,  91,   9,  92,  10,  93,  11
                                        ,  94,  12,  95,  16,  96,  17,  97,  18,  98,  19};

// Total size of all succNNNN tables:1676 bytes.

static const TableType *successor[159] = {
   succ0000,NULL    ,NULL    ,succ0003,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL
  ,NULL    ,NULL    ,NULL    ,succ0013,succ0014,succ0015,NULL    ,NULL    ,NULL    ,NULL
  ,succ0020,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL
  ,NULL    ,NULL    ,succ0062,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0078,succ0079
  ,succ0080,succ0081,succ0082,succ0083,succ0084,succ0085,succ0086,succ0087,succ0088,succ0089
  ,succ0090,succ0091,NULL    ,succ0093,succ0094,succ0095,NULL    ,NULL    ,NULL    ,NULL
  ,succ0100,NULL    ,NULL    ,NULL    ,succ0104,succ0105,succ0106,succ0107,NULL    ,NULL
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0137,succ0138,succ0139
  ,succ0140,NULL    ,succ0142,NULL    ,NULL    ,NULL    ,NULL    ,succ0147,NULL    ,NULL
  ,succ0150,succ0151,succ0152,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL
}; // Size of pointertable:1272 bytes.

/****************************************************************************\
* The productionLength[] array is indexed by production number and holds     *
* the number of symbols on the right side of each production.                *
\****************************************************************************/
static const unsigned char productionLength[94] = {
  /*   0 */    1,   1,   2,   1,   1,   1,   2,   2,   3,   3,
  /*  10 */    3,   3,   3,   3,   3,   1,   1,   1,   4,   6,
  /*  20 */    3,   2,   2,   1,   1,   1,   1,   3,   8,   7,
  /*  30 */    7,   7,   3,   1,   1,   1,   1,   1,   1,   1,
  /*  40 */    1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
  /*  50 */    1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
  /*  60 */    1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
  /*  70 */    1,   3,   3,   3,   3,   3,   3,   3,   3,   2,
  /*  80 */    3,   1,   1,   1,   1,   1,   1,   1,   1,   1,
  /*  90 */    1,   1,   1,   1
}; // Size of table:96 bytes.

/****************************************************************************\
* The leftSide[] array is indexed by production number, and holds the        *
* nonTerminal symbol on the left side of each production.                    *
\****************************************************************************/
static const TableType leftSide[94] = {
  /*   0 */   82,  83,  83,  84,  84,  85,  85,  88,  89,  86,
  /*  10 */   86,  86,  86,  86,  86,  86,  91,  91,  91,  91,
  /*  20 */   91,  91,  91,  91,  91,  91,  91,  91,  95,  96,
  /*  30 */   97,  98,  99,  99,  93,  93,  93,  93,  93,  93,
  /*  40 */   93,  93,  93,  93,  93,  93,  93,  93,  93,  93,
  /*  50 */   93,  93,  93,  93,  93,  93,  93,  93,  93,  93,
  /*  60 */   93,  93,  93,  93,  93,  93,  93,  93,  93,  93,
  /*  70 */   93,  87,  87,  87,  87,  87,  87,  87,  87,  87,
  /*  80 */   87,  94,  94,  94,  94,  94,  94,  94,  94,  94,
  /*  90 */   94,  94,  90,  92
}; // Size of table:188 bytes.

/****************************************************************************\
* The rightSide[] matrix is indexed by production number and holds           *
* the right side symbols of each production.                                 *
* Compressed and only used for debugging.                                    *
\****************************************************************************/
static const TableType rightSideTable[171] = {
  /*   0 */   83
  /*   1 */ , 84
  /*   2 */ , 85, 84
  /*   3 */ , 86
  /*   4 */ , 87
  /*   5 */ , 88
  /*   6 */ , 85, 88
  /*   7 */ , 89,  7
  /*   8 */ , 90,  6, 86
  /*   9 */ , 86, 22, 86
  /*  10 */ , 86, 23, 86
  /*  11 */ , 86, 25, 86
  /*  12 */ , 86, 26, 86
  /*  13 */ , 86, 27, 86
  /*  14 */ , 86, 28, 86
  /*  15 */ , 91
  /*  16 */ , 92
  /*  17 */ , 90
  /*  18 */ , 93, 78, 86, 79
  /*  19 */ , 94, 78, 86,  8, 86, 79
  /*  20 */ , 78, 86, 79
  /*  21 */ , 23, 86
  /*  22 */ , 22, 86
  /*  23 */ , 95
  /*  24 */ , 96
  /*  25 */ , 97
  /*  26 */ , 98
  /*  27 */ , 80, 87, 81
  /*  28 */ ,  4, 78, 87,  8, 86,  8, 86, 79
  /*  29 */ , 10, 78, 89,  9, 86, 79, 86
  /*  30 */ , 11, 78, 89,  9, 86, 79, 86
  /*  31 */ , 76, 80, 99, 81, 78, 86, 79
  /*  32 */ , 99,  8, 86
  /*  33 */ , 86
  /*  34 */ , 48
  /*  35 */ , 29
  /*  36 */ , 30
  /*  37 */ , 31
  /*  38 */ , 32
  /*  39 */ , 33
  /*  40 */ , 34
  /*  41 */ , 35
  /*  42 */ , 36
  /*  43 */ , 38
  /*  44 */ , 49
  /*  45 */ , 39
  /*  46 */ , 40
  /*  47 */ , 41
  /*  48 */ , 42
  /*  49 */ , 50
  /*  50 */ , 51
  /*  51 */ , 52
  /*  52 */ , 53
  /*  53 */ , 54
  /*  54 */ , 55
  /*  55 */ , 57
  /*  56 */ , 58
  /*  57 */ , 59
  /*  58 */ , 60
  /*  59 */ , 61
  /*  60 */ , 62
  /*  61 */ , 63
  /*  62 */ , 64
  /*  63 */ , 43
  /*  64 */ , 69
  /*  65 */ , 44
  /*  66 */ , 45
  /*  67 */ , 70
  /*  68 */ , 71
  /*  69 */ , 46
  /*  70 */ , 47
  /*  71 */ , 86, 15, 86
  /*  72 */ , 86, 20, 86
  /*  73 */ , 86, 18, 86
  /*  74 */ , 86, 19, 86
  /*  75 */ , 86, 16, 86
  /*  76 */ , 86, 17, 86
  /*  77 */ , 87, 13, 87
  /*  78 */ , 87, 12, 87
  /*  79 */ , 14, 87
  /*  80 */ , 78, 87, 79
  /*  81 */ , 73
  /*  82 */ , 74
  /*  83 */ , 75
  /*  84 */ , 77
  /*  85 */ , 68
  /*  86 */ , 72
  /*  87 */ , 66
  /*  88 */ , 65
  /*  89 */ , 67
  /*  90 */ , 37
  /*  91 */ , 56
  /*  92 */ ,  2
  /*  93 */ ,  1
}; // Size of table:344 bytes.

/****************************************************************************\
* The symbolName[] array is indexed by symbol and holds                      *
* the name of each symbol (terminal or nonTerminal).                         *
* Used for debugging.                                                        *
\****************************************************************************/
static const TCHAR *symbolName[100] = {
  /*   0 */ _T("EOI"),
  /*   1 */ _T("NUMBER"),
  /*   2 */ _T("NAME"),
  /*   3 */ _T("TYPEBOOL"),
  /*   4 */ _T("IIF"),
  /*   5 */ _T("STMTLIST"),
  /*   6 */ _T("ASSIGN"),
  /*   7 */ _T("SEMI"),
  /*   8 */ _T("COMMA"),
  /*   9 */ _T("TO"),
  /*  10 */ _T("INDEXEDSUM"),
  /*  11 */ _T("INDEXEDPRODUCT"),
  /*  12 */ _T("SYMOR"),
  /*  13 */ _T("SYMAND"),
  /*  14 */ _T("SYMNOT"),
  /*  15 */ _T("EQ"),
  /*  16 */ _T("GE"),
  /*  17 */ _T("GT"),
  /*  18 */ _T("LE"),
  /*  19 */ _T("LT"),
  /*  20 */ _T("NE"),
  /*  21 */ _T("SUM"),
  /*  22 */ _T("PLUS"),
  /*  23 */ _T("MINUS"),
  /*  24 */ _T("PRODUCT"),
  /*  25 */ _T("PROD"),
  /*  26 */ _T("QUOT"),
  /*  27 */ _T("MOD"),
  /*  28 */ _T("POW"),
  /*  29 */ _T("ACOS"),
  /*  30 */ _T("ACOSH"),
  /*  31 */ _T("ACOT"),
  /*  32 */ _T("ACSC"),
  /*  33 */ _T("ASEC"),
  /*  34 */ _T("ASIN"),
  /*  35 */ _T("ASINH"),
  /*  36 */ _T("ATAN"),
  /*  37 */ _T("ATAN2"),
  /*  38 */ _T("ATANH"),
  /*  39 */ _T("COS"),
  /*  40 */ _T("COSH"),
  /*  41 */ _T("COT"),
  /*  42 */ _T("CSC"),
  /*  43 */ _T("SEC"),
  /*  44 */ _T("SIN"),
  /*  45 */ _T("SINH"),
  /*  46 */ _T("TAN"),
  /*  47 */ _T("TANH"),
  /*  48 */ _T("ABS"),
  /*  49 */ _T("CEIL"),
  /*  50 */ _T("ERF"),
  /*  51 */ _T("EXP"),
  /*  52 */ _T("EXP10"),
  /*  53 */ _T("EXP2"),
  /*  54 */ _T("FAC"),
  /*  55 */ _T("FLOOR"),
  /*  56 */ _T("HYPOT"),
  /*  57 */ _T("GAMMA"),
  /*  58 */ _T("GAUSS"),
  /*  59 */ _T("INVERF"),
  /*  60 */ _T("LN"),
  /*  61 */ _T("LOG10"),
  /*  62 */ _T("LOG2"),
  /*  63 */ _T("NORM"),
  /*  64 */ _T("PROBIT"),
  /*  65 */ _T("CHI2DIST"),
  /*  66 */ _T("CHI2DENS"),
  /*  67 */ _T("LINCGAMMA"),
  /*  68 */ _T("ROOT"),
  /*  69 */ _T("SIGN"),
  /*  70 */ _T("SQR"),
  /*  71 */ _T("SQRT"),
  /*  72 */ _T("BINOMIAL"),
  /*  73 */ _T("MAX"),
  /*  74 */ _T("MIN"),
  /*  75 */ _T("NORMRAND"),
  /*  76 */ _T("POLY"),
  /*  77 */ _T("RAND"),
  /*  78 */ _T("LPAR"),
  /*  79 */ _T("RPAR"),
  /*  80 */ _T("LB"),
  /*  81 */ _T("RB"),
  /*  82 */ _T("start"),
  /*  83 */ _T("function"),
  /*  84 */ _T("final_expr"),
  /*  85 */ _T("assignStmtList"),
  /*  86 */ _T("expr"),
  /*  87 */ _T("boolExpr"),
  /*  88 */ _T("assignStmt"),
  /*  89 */ _T("assign"),
  /*  90 */ _T("name"),
  /*  91 */ _T("unary"),
  /*  92 */ _T("number"),
  /*  93 */ _T("function1"),
  /*  94 */ _T("function2"),
  /*  95 */ _T("conditionalExpr"),
  /*  96 */ _T("sumExpr"),
  /*  97 */ _T("productExpr"),
  /*  98 */ _T("polyExpr"),
  /*  99 */ _T("exprList")
}; // Total size of strings:780 bytes, size of pointertable:800 bytes.

static const ParserShortTables ExpressionTables_s(compressedSet, compressedLasets
                                                 ,action, successor, productionLength, leftSide
                                                 ,rightSideTable, symbolName
                                                 ,82, 100, 94, 159);

const ParserTables *ExpressionTables = &ExpressionTables_s;
// Size of ExpressionTables_s: 88 bytes. Size of ExpressionTables:8 bytes


// Total size of table data:8.856 bytes.

