//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PartyMaker.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDI_MAINFRAME                   102
#define IDI_CHECKFILESICON              103
#define IDI_READFILESICON               104
#define IDD_MAINDIALOG                  129
#define IDD_SEARCHDIALOG                130
#define IDD_MUSICDIRDIALOG              131
#define IDD_CHANGEORDERDIALOG           133
#define IDD_MAXCHOISEDIALOG             134
#define IDD_PASSWORDDIALOG              135
#define IDD_CHANGEPASSWORDDIALOG        136
#define IDD_CHECKFILESDIALOG            137
#define IDD_SLIDERCONTROLDIALOG         138
#define IDD_PROGRESSDIALOG              139
#define IDD_EDITTAGDIALOG               140
#define IDD_INFODIALOG                  141
#define IDD_SELECTATTRIBUTEDIALOG       142
#define IDR_FOLDERIMAGES                143
#define IDC_CURSORMOVE                  144
#define IDR_MAINFRAME                   145
#define IDR_CONTEXTMENU                 146
#define IDR_CHANGEORDERMENU             147
#define IDR_EDITTAGMENU                 148
#define IDR_CHANGEORDER_ACCELERATOR     150
#define IDR_SEARCH_ACCELERATOR          151
#define IDR_MUSICDIR_ACCELERATOR        152
#define IDR_EDITTAG_ACCELERATOR         154
#define IDR_CHECKFILES_ACCELERATOR      155
#define IDR_SEARCHMENU                  157
#define IDD_SHOWDUPLICATESDIALOG        158
#define IDR_SHOWDUPLICATES_ACCELERATOR  159
#define IDD_SELECTDIRANDLISTNAMEDIALOG  162
#define IDR_SELECTDIRANDLISTNAME_ACCELERATOR 163
#define IDC_ALLMEDIA                    1001
#define IDC_CURRENT                     1002
#define IDC_MEDIAQUEUEFRAME             1003
#define IDC_SEARCHBUTTON                1004
#define IDC_PAUSEBUTTON                 1005
#define IDC_NEXTBUTTON                  1006
#define IDC_VOLUMESLIDER                1007
#define IDC_SEARCHTEXT                  1008
#define IDC_LISTRESULT                  1009
#define IDC_CHOOSE                      1010
#define IDC_PASSWORD                    1011
#define IDC_OLDPASSWORDEDIT             1012
#define IDC_NEWPASSWORDEDIT             1013
#define IDC_NEWPASSWORDEDIT2            1014
#define IDC_EDITLIST                    1015
#define IDC_MAXCHOISEEDIT               1016
#define IDC_CHECKSTATUS                 1017
#define IDC_PROGRESSCHECK               1018
#define IDC_STATICMESSAGE               1019
#define IDC_STATICERRORS                1020
#define IDC_PLAYERCONTROLSLIDER         1021
#define IDC_STATICTEXT                  1022
#define IDC_DIRLIST                     1023
#define IDC_NEWBUTTON                   1024
#define IDC_DELETEBUTTON                1025
#define IDC_DIRTREE                     1026
#define IDC_DRIVECOMBO                  1027
#define IDC_DIREDIT                     1028
#define IDC_QUEUE                       1029
#define IDC_STATICDIRNAME               1030
#define IDC_SHOWERRORS                  1031
#define IDC_GENRECOMBO                  1032
#define IDC_MEDIAPLAYER                 1033
#define IDC_ATTRIBUTELIST               1034
#define IDC_READONLYATTRIBUTELIST       1035
#define IDC_DEFAULTSETTINGBUTTON        1036
#define IDC_STATICOUNT                  1037
#define IDC_STATICREADONLYLABEL         1038
#define IDC_STATICREADWRITELABEL        1039
#define IDC_DUPLICATELIST               1040
#define IDC_STATETEXT                   1041
#define IDC_CHECKFILTERBYSIZE           1042
#define IDC_NAMEEDIT                    1043
#define IDC_CHECKRECURSIVE              1044
#define IDC_CHECKFILTERBYDURATION       1045
#define ID_FILE_NEXTNUMBER              32771
#define ID_FILE_PAUSE                   32772
#define ID_FILE_EDITORDER               32773
#define ID_FILE_PASSWORDPROTECT         32774
#define ID_FILE_GENERATEPLAYLISTFROMDIR 32775
#define ID_FILE_EXIT                    32776
#define ID_EDIT_DELETE                  32777
#define ID_EDIT_MODIFYINFO              32778
#define ID_EDIT_SHOWINFO                32779
#define ID_EDIT_SHOWLOG                 32780
#define ID_EDIT_SHOWERRORS              32781
#define ID_EDIT_RANDOM                  32782
#define ID_OPTIONS_BALANCE              32783
#define ID_OPTIONS_SPEED                32784
#define ID_OPTIONS_KATALOG              32785
#define ID_OPTIONS_RESCANCATALOG        32786
#define ID_OPTIONS_AUTOSELECT           32787
#define ID_OPTIONS_ALLOWDUPLICATES      32788
#define ID_OPTIONS_CONFIRMCHOISE        32789
#define ID_OPTIONS_MAXCHOISE            32790
#define ID_OPTIONS_COLORS               32791
#define ID_OPTIONS_COLORS_BACKGROUND    32792
#define ID_OPTIONS_COLORS_CURRENTTRACK  32793
#define ID_OPTIONS_COLORS_MEDIAQUEUE    32794
#define ID_OPTIONS_CHANGEPASSWORD       32795
#define ID_OPTIONS_CHECKFILES           32796
#define ID_HELP_ABOUTPARTYMAKER         32797
#define ID_SHOWCOUNT                    32798
#define ID_CONTEXTMENU_REMOVE           32799
#define ID_CONTEXTMENU_INFO             32800
#define ID_BUTTON32803                  32801
#define ID_BUTTON32804                  32802
#define ID_ADDMEDIAFILE                 32803
#define ID_EDIT_ADDATTRIBUTE            32804
#define ID_EDIT_EDIT                    32805
#define ID_GOTO_DRIVE                   32806
#define ID_GOTO_SEARCHTEXT              32807
#define ID_GOTO_READWRITELIST           32808
#define ID_GOTO_READONLYLIST            32809
#define ID_GOTO_LISTNAME                32810
#define ID_GOTO_DIR                     32811
#define ID_SORT_BY_TITLE                32812
#define ID_SORT_BY_ARTIST               32813
#define ID_SORT_BY_ALBUM                32814
#define ID_FIND_DUPLICATES              32815
#define ID_SHOW_STATEMESSAGE            32816

// Next default values for new objects
// 
#if defined(APSTUDIO_INVOKED)
#if !defined(APSTUDIO_READONLY_SYMBOLS)
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32816
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
