white:Kg1,Qa1,Re1,Bg3,Ba8,Nb6,Nh6,d2,f2,c5,e5;
black:Ke6,Nf8,c4,e4,h4,c6,d7,e7,f7;
PlayerInTurn:white;
History

EndHistory
Settings
ShowFieldNames:1
ShowLegalMoves:1
ShowPlayerToMoMove:1
AnimateMoves:1
AnimateCheckmate:1
ComputerIsWhite:0
Validate:1
Level:6
WhiteLevel:4
BlackLevel:4
HistoryFormat:0
EndSettings
