//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinDiff.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_WINDIFFVIEW                 129
#define IDD_DIALOGFIND                  130
#define IDD_DIALOGREGEX                 131
#define IDD_DIALOGCOLUMNS               132
#define IDD_DIALOGZOOM                  133
#define IDD_DIALOGTABSIZE               134
#define IDD_DIALOGENTERFORMATNAME       135
#define IDD_DIALOGLISTFORMATNAMES       136
#define IDD_DIALOGGOTO                  137
#define IDR_MENUCOLUMNS                 138
#define IDR_MENUDELIMITERESCAPESYMBOLS  139
#define IDR_MENUREGSYMBOLS              140
#define IDR_ACCELERATORFIND             141
#define IDR_ACCELERATORREGEX            142
#define IDR_ACCELERATORCOLUMNS          143
#define IDR_ACCELERATORZOOM             144
#define IDR_TOOLBARZOOM                 145
#define IDB_ARROW                       146
#define IDD_DIALOGENTEROPTIONSNAME      148
#define IDD_DIALOGORGANIZEOPTIONS       149
#define IDC_DIFF                        1000
#define IDC_NAME                        1001
#define IDC_INFO                        1002
#define IDC_SCROLLBARH                  1003
#define IDC_SCROLLBARV                  1004
#define IDC_FINDNEXT                    1005
#define IDC_COMBOFINDWHAT               1006
#define IDC_CHECKMATCHCASE              1007
#define IDC_CHECKMATCHWHOLEWORD         1008
#define IDC_CHECKUSEREGEX               1009
#define IDC_RADIOUP                     1010
#define IDC_RADIODOWN                   1011
#define IDC_EDITTABSIZE                 1012
#define IDC_EDITFROM                    1013
#define IDC_EDITTO                      1014
#define IDC_RADIODELIMITED              1015
#define IDC_RADIOFIXEDWIDTH             1016
#define IDC_EDITFIELDDELIMITER          1017
#define IDC_EDITTEXTQUALIFIER           1018
#define IDC_EDITNAME                    1019
#define IDC_EDITSAMPLE                  1020
#define IDC_LISTCOLUMNS                 1021
#define IDC_BUTTONADD                   1022
#define IDC_BUTTONDELETE                1023
#define IDC_STATICFIELDDELIMITER        1024
#define IDC_STATICTEXTQUALIFIER         1025
#define IDC_LISTFORMATNAMES             1026
#define IDC_BUTTONDELIMITERMENU         1027
#define IDC_BUTTONREGSYMBOLSMENU        1028
#define IDC_COMBOREGEX                  1029
#define IDC_CHECKIGNORECASE             1031
#define IDC_CHECKLIMITDIFF              1033
#define IDC_CHECKLIMITNONDIFF           1034
#define IDC_CHECKMULTIPLEDELIMITERS     1035
#define IDC_EDITLINENUMBER              1036
#define IDC_STATICCOPYRIGHT             1037
#define IDC_COMBOOPTIONSNAME            1039
#define IDC_LISTOPTIONNAMES             1040
#define IDC_BUTTONRENAME                1041
#define IDC_BUTTONMOVEUP                1043
#define IDC_BUTTONMOVEDOWN              1044
#define IDC_EDIT2LINES                  1045
#define ID_INDICATOR_POSITION           32771
#define ID_INDICATOR_DELETEDLINES       32772
#define ID_INDICATOR_CHANGEDLINES       32773
#define ID_INDICATOR_INSERTEDLINES      32774
#define ID_INDICATOR_DEBUG              32775
#define ID_ACTIVATEPARTNER              32776
#define ID_FILE_OPEN_PANEL0             32780
#define ID_FILE_OPEN_PANEL1             32781
#define ID_EDIT_SELECTALL               32782
#define ID_EDIT_FIND_NEXT               32783
#define ID_EDIT_FIND_PREV               32784
#define ID_EDIT_PREV_DIFF               32785
#define ID_EDIT_NEXT_DIFF               32786
#define ID_EDIT_SHOWDETAILS             32787
#define ID_EDIT_GOTO                    32788
#define ID_EDIT_SWAPPANELS              32789
#define ID_EDIT_REFRESHFILES            32790
#define ID_VIEW_SHOWWHITESPACE          32791
#define ID_VIEW_FONT                    32792
#define ID_VIEW_TABSIZE                 32793
#define ID_VIEW_NAMEFONTSIZE_100        32794
#define ID_VIEW_NAMEFONTSIZE_125        32795
#define ID_VIEW_NAMEFONTSIZE_150        32796
#define ID_VIEW_NAMEFONTSIZE_175        32797
#define ID_VIEW_NAMEFONTSIZE_200        32798
#define ID_VIEW_SHOW1000SEPARATOR       32799
#define ID_VIEW_HIGHLIGHTCOMPAREEQUAL   32800
#define ID_OPTIONS_IGNOREBLANKS         32820
#define ID_OPTIONS_IGNORECASE           32821
#define ID_OPTIONS_IGNORESTRINGS        32822
#define ID_OPTIONS_IGNORECOMMENTS       32823
#define ID_OPTIONS_IGNORECOLUMNS        32824
#define ID_OPTIONS_IGNOREREGEX          32825
#define ID_OPTIONS_DEFINECOLUMNS        32826
#define ID_OPTIONS_DEFINEREGEX          32827
#define ID_OPTIONS_STRIPCOMMENTS        32828
#define ID_OPTIONS_SAVEOPTIONS          32829
#define ID_OPTIONS_LOADOPTIONS          32830
#define ID_OPTIONS_LOADOPTIONS1         32831
#define ID_OPTIONS_LOADOPTIONS2         32832
#define ID_OPTIONS_LOADOPTIONS3         32833
#define ID_OPTIONS_LOADOPTIONS4         32834
#define ID_OPTIONS_LOADOPTIONS5         32835
#define ID_OPTIONS_LOADOPTIONS6         32836
#define ID_OPTIONS_LOADOPTIONS7         32837
#define ID_OPTIONS_LOADOPTIONS8         32838
#define ID_OPTIONS_LOADOPTIONS9         32839
#define ID_OPTIONS_ORGANIZEOPTIONS      32840
#define ID_CHARLEFT                     32850
#define ID_CHARRIGHT                    32851
#define ID_CTRLCHARLEFT                 32852
#define ID_CTRLCHARRIGHT                32853
#define ID_LINEUP                       32854
#define ID_LINEDOWN                     32855
#define ID_PAGEUP                       32856
#define ID_PAGEDOWN                     32857
#define ID_HOME                         32858
#define ID_END                          32859
#define ID_CTRLHOME                     32860
#define ID_CTRLEND                      32861
#define ID_DELIMESCSYMBOL_TAB           32870
#define ID_DELIMESCSYMBOL_SPACE         32871
#define ID_DELIMESCSYMBOL_CR            32872
#define ID_DELIMESCSYMBOL_NEWLINE       32873
#define ID_DELIMESCSYMBOL_FORM          32874
#define ID_DELIMESCSYMBOL_BACK          32875
#define ID_DELIMESCSYMBOL_ESC           32876
#define ID_DELIMESCSYMBOL_UNICODE       32877
#define ID_DELIMESCSYMBOL_BACKSLASH     32878
#define ID_DELIMESCSYMBOL_CTRL          32879
#define ID_DELIMESCSYMBOL_OCT           32880
#define ID_DELIMESCSYMBOL_HEX           32881
#define ID_DELIMESCSYMBOL_ANYCHAR       32882
#define ID_REGSYMBOLS_ANYCHAR           32890
#define ID_REGSYMBOLS_CHARINRANGE       32891
#define ID_REGSYMBOLS_CHARNOTINRANGE    32892
#define ID_REGSYMBOLS_BEGINNINGOFLINE   32893
#define ID_REGSYMBOLS_ENDOFLINE         32894
#define ID_REGSYMBOLS_0ORMORE           32895
#define ID_REGSYMBOLS_1ORMORE           32896
#define ID_REGSYMBOLS_0OR1              32897
#define ID_REGSYMBOLS_OR                32898
#define ID_REGSYMBOLS_GROUP             32899
#define ID_GOTOCOLUMNFROM               32910
#define ID_GOTOCOLUMNTO                 32911
#define ID_GOTOFIELDDELIMITER           32912
#define ID_GOTOTEXTQUALIFIER            32913
#define ID_GOTOSAMPLE                   32914
#define ID_GOTOCOLUMNLIST               32915
#define ID_GOTOFINDWHAT                 32916
#define ID_GOTOREGEX                    32917
#define ID_FORMAT_NEW                   32918
#define ID_DUMPFLAGS                    32920

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32922
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
