#pragma once

#include <MFCUtil/FunctionImageParamPersistentData.h>

#define TYPE_FUNCTIONR2R1SURFACE   FUNCTIONDOMAINRANGE(2, 1)
#define TYPE_ISOSURFACE            FUNCTIONDOMAINRANGE(3, 1)
#define TYPE_PARAMETRICR1R3SURFACE FUNCTIONDOMAINRANGE(1, 3)
#define TYPE_PARAMETRICR2R3SURFACE FUNCTIONDOMAINRANGE(2, 3)
