/* DO NOT EDIT THIS FILE - it is machine generated */

#include "stdafx.h"
#include "olm641parser.h"



#pragma warning(disable : 4060)

int Olm641Parser::reduceAction(unsigned int prod) {
  switch(prod) {
  case 1: /* S -> a b A E */
    { debug(_T("reduce by a b A E pos of A is (%d,%d)\n"),getPos(3).getLineNumber(),getPos(3).getColumn()); }
    break;
  case 11: /* E -> epsilon */
    { _tprintf(_T("reduce by E -> eps yypos(0):(%d,%d)\n"), getPos(0).getLineNumber(),getPos(0).getColumn()); }
    break;
  }
  return 0;
}



