//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D3FunctionPlotter.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDR_FUNC2DSURFACE               129
#define IDR_PARAMETRICSURFACE           130
#define IDR_ISOSURFACE                  131
#define IDR_PROFILE                     132
#define IDB_TESTBITMAP                  191
#define IDB_CIRCLEARROWBITMAP           200
#define IDB_LEFTRIGHTARROWBITMAP        201
#define IDB_BLACKSQUAREBITMAP           202
#define IDB_ROTATECORNERBITMAP          203
#define IDC_BUTTON_DUMMY                1020
#define IDC_STATIC_3DPANEL              1021
#define IDC_STATIC_INFOPANEL            1022
#define IDC_STATIC_FUNCTION             1070
#define IDC_EDIT_EXPR                   1071
#define IDC_STATIC_XINTERVAL            1072
#define IDC_EDIT_XFROM                  1073
#define IDC_STATIC_DASH1                1074
#define IDC_EDIT_XTO                    1075
#define IDC_STATIC_YINTERVAL            1076
#define IDC_EDIT_YFROM                  1077
#define IDC_STATIC_DASH2                1078
#define IDC_EDIT_YTO                    1079
#define IDC_STATIC_ZINTERVAL            1080
#define IDC_EDIT_ZFROM                  1081
#define IDC_STATIC_DASH3                1082
#define IDC_EDIT_ZTO                    1083
#define IDC_STATIC_POINTCOUNT           1090
#define IDC_EDIT_POINTS                 1091
#define IDC_STATIC_STEPCOUNT            1091
#define IDC_STATIC_F3D                  1092
#define IDC_STATIC_EQUAL_ZERO           1093
#define IDC_STATIC_CELLSIZE             1094
#define IDC_EDIT_CELLSIZE               1095
#define IDC_CHECK_TETRAHEDRAL           1096
#define IDC_CHECK_TETRAOPTIMIZE4        1097
#define IDC_CHECK_ORIGINOUTSIDE         1098
#define IDC_CHECK_ADAPTIVECELLSIZE      1099
#define IDC_CHECK_DOUBLESIDED           1110
#define IDC_CHECK_MACHINECODE           1111
#define IDC_CHECK_INCLUDETIME           1112
#define IDC_STATIC_TIMEINTERVAL         1113
#define IDC_EDIT_TIMEFROM               1114
#define IDC_STATIC_DASH4                1115
#define IDC_EDIT_TIMETO                 1116
#define IDC_STATIC_FRAMECOUNT           1117
#define IDC_EDIT_FRAMECOUNT             1118
#define IDC_CHECK_DEBUGPOLYGONIZER      1119
#define IDC_COMBO_EXPR_HELP             1130
#define IDC_BUTTON_HELP                 1131
#define IDC_STATIC_BOUNDINGBOX          1140
#define IDC_STATIC_DEBUG3DFRAME         1141
#define IDC_SLIDER_DEGREE               1142
#define IDC_STATIC_DEGREE               1143
#define IDC_EDIT_EDGECOUNT              1150
#define IDC_EDIT_DEGREES                1151
#define IDC_RADIO_ROTATE                1152
#define IDC_RADIO_STRETCH               1153
#define IDC_CHECK_ROTATESMOOTH          1154
#define IDC_CHECK_NORMALSMOOTH          1155
#define IDC_BUTTON_REFRESH              1156
#define IDC_RADIO_ROTATEXAXIS           1157
#define IDC_RADIO_ROTATEYAXIS           1158
#define IDC_STATIC_FUNCTIONX            1170
#define IDC_BUTTON_HELPX                1171
#define IDC_EDIT_EXPRX                  1172
#define IDC_EDITCOMMON                  1173
#define IDC_STATICCOMMON                1174
#define IDC_STATIC_FUNCTIONY            1180
#define IDC_BUTTON_HELPY                1181
#define IDC_EDIT_EXPRY                  1182
#define IDC_STATIC_FUNCTIONZ            1190
#define IDC_BUTTON_HELPZ                1191
#define IDC_EDIT_EXPRZ                  1192
#define IDC_STATIC_TINTERVAL            1200
#define IDC_EDIT_TFROM                  1201
#define IDC_EDIT_TTO                    1202
#define IDC_STATIC_SINTERVAL            1210
#define IDC_EDIT_SFROM                  1211
#define IDC_EDIT_STO                    1212
#define IDC_STATIC_TSTEPCOUNT           1213
#define IDC_EDIT_TSTEPCOUNT             1214
#define IDC_STATIC_SSTEPCOUNT           1215
#define IDC_EDIT_SSTEPCOUNT             1216
#define IDC_STATIC_PROFILEIMAGE2D       1220
#define IDC_STATIC_PROFILEIMAGE3D       1221
#define IDC_STATIC_INFO                 1222
#define ID_FILE_SAVESTATE               32771
#define ID_FILE_LOADSTATE               32772
#define ID_FILE_NEXTTRY                 32773
#define ID_FILE_FUNCTIONSURFACE         32774
#define ID_FILE_PARAMETRICSURFACE       32775
#define ID_FILE_ISOSURFACE              32776
#define ID_FILE_PROFILESURFACE          32777
#define ID_FILE_READ3DPOINTSFROMFILE    32778
#define ID_FILE_EXIT                    32779
#define ID_VIEW_SHOW3DINFO              32788
#define ID_DEBUG_GO                     32790
#define ID_DEBUG_SINGLESTEP             32791
#define ID_DEBUG_STEPCUBE               32792
#define ID_DEBUG_BREAKONNEXTLEVEL       32793
#define ID_EDIT_FINDMATCHINGPARENTESIS  32800
#define ID_RESETPOSITIONS               32810
#define ID_OBJECT_EDITFUNCTION          32820
#define ID_ADDBOXOBJECT                 32821
#define ID_FILE_SELECTFROMFONT          32870
#define ID_EDIT_DELETE                  32871
#define ID_EDIT_CONNECT                 32872
#define ID_EDIT_INVERTNORMALS           32873
#define ID_EDIT_MIRROR_HORIZONTAL       32874
#define ID_EDIT_MIRROR_VERTICAL         32875
#define ID_VIEW_SHOWPOINTS              32876
#define ID_VIEW_SHOWNORMALS             32877
#define ID_VIEW_AUTO_UPDATE_3D          32878
#define ID_TOOLS_LINE                   32879
#define ID_TOOLS_BEZIERCURVE            32880
#define ID_TOOLS_RECTANGLE              32881
#define ID_TOOLS_POLYGON                32882
#define ID_TOOLS_ELLIPSE                32883
#define ID_TOOLS_SELECT                 32884
#define ID_GOTO_EXPR                    33110
#define ID_GOTO_EXPRX                   33111
#define ID_GOTO_EXPRY                   33112
#define ID_GOTO_EXPRZ                   33113
#define ID_GOTO_CELLSIZE                33115
#define ID_GOTO_XINTERVAL               33120
#define ID_GOTO_YINTERVAL               33121
#define ID_GOTO_ZINTERVAL               33122
#define ID_GOTO_TINTERVAL               33123
#define ID_GOTO_SINTERVAL               33124
#define ID_GOTO_TIMEINTERVAL            33125
#define ID_GOTO_POINTCOUNT              33126
#define ID_GOTO_TSTEPCOUNT              33127
#define ID_GOTO_SSTEPCOUNT              33128
#define ID_GOTO_FRAMECOUNT              33129
#define ID_GOTO_COMMON                  33130
#define ID_FILE_READOBJ                 33257
#define ID_FILE_READOBJFILE             33258
#define ID_MSG_RENDER                   33300
#define ID_MSG_THREADRUNNING            33301
#define ID_MSG_KILLTHREAD               33302

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        207
#define _APS_NEXT_COMMAND_VALUE         33275
#define _APS_NEXT_CONTROL_VALUE         1233
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
