/* DO NOT EDIT THIS FILE - it is machine generated */
#line 131 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
#include "stdafx.h"
#include "SqlParser.h"
#include <SqlApi.h>
#include <io.h>


#line 21 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"

int SqlParser::reduceAction(unsigned int prod) {

  switch(prod) {
  case 0: /* start -> stmt */
#line 140 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_tree.m_root = getStackTop(0); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 10: /* update_stmt -> UPDATE name SET assign_list opt_where */
#line 154 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), UPDATE, getStackTop(3), getStackTop(1), getStackTop(0), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 11: /* assign_list -> assign_list COMMA assign */
#line 157 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), COMMA, getStackTop(2), getStackTop(0), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 13: /* assign -> name EQUAL expr */
#line 161 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), EQUAL, getStackTop(2), getStackTop(0), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 14: /* insert_stmt -> INSERT INTO name LPAR name_list RPAR VALUES LPAR opt_expr_list RPAR opt_access */
#line 166 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), INSERT,
    																		getStackTop(8),
    																		newNode( getPos(5), COLUMN, getStackTop(6), NULL ),
    																		newNode( getPos(7), VALUES, getStackTop(2), NULL ),
    																		getStackTop(0),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 15: /* insert_stmt -> INSERT INTO name VALUES LPAR opt_expr_list RPAR opt_access */
#line 176 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), INSERT,
    																		getStackTop(5),
    																		newNode( getPos(4), COLUMN, NULL     ),
    																		newNode( getPos(4), VALUES, getStackTop(2), NULL ),
    																		getStackTop(0),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 16: /* insert_stmt -> INSERT INTO name LPAR name_list RPAR LPAR select_stmt RPAR opt_access */
#line 186 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), INSERT,
    																		getStackTop(7),
    																		newNode( getPos(5), COLUMN, getStackTop(5), NULL ),
    																		getStackTop(2),
    																		getStackTop(0),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 17: /* insert_stmt -> INSERT INTO name LPAR select_stmt RPAR opt_access */
#line 196 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), INSERT,
    																		getStackTop(4), 
    																		newNode( getPos(4), COLUMN, NULL ),
    																		getStackTop(2),
    																		getStackTop(0),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 18: /* insert_stmt -> INSERT INTO name LPAR name_list RPAR select_stmt */
#line 206 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), INSERT,
    																		getStackTop(4),
    																		newNode( getPos(5), COLUMN, getStackTop(2), NULL ),
    																		getStackTop(0),
    																		newNode( getPos(), ACCESSS, NULL	     ),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 19: /* insert_stmt -> INSERT INTO name select_stmt */
#line 216 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), INSERT,
    																		getStackTop(1), 
    																		newNode( getPos(3), COLUMN, NULL   ),
    																		getStackTop(0), 
    																		newNode( getPos(), ACCESSS, NULL	   ),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 21: /* name_list -> name_list COMMA name */
#line 226 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), COMMA, getStackTop(2), getStackTop(0), NULL );       }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 22: /* opt_expr_list -> epsilon */
#line 229 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = NULL; }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 24: /* delete_stmt -> DELETESYM FROM name opt_where opt_access */
#line 233 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), DELETESYM, getStackTop(2), getStackTop(1), getStackTop(0), NULL );     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 25: /* select_stmt -> select_stmt UNION opt_all select_stmt */
#line 236 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), UNION        , getStackTop(3), getStackTop(0), getStackTop(1), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 26: /* select_stmt -> select_stmt INTERSECT select_stmt */
#line 237 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), INTERSECT    , getStackTop(2), getStackTop(0), NULL );     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 27: /* select_stmt -> select_stmt SETDIFFERENCE select_stmt */
#line 238 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), SETDIFFERENCE, getStackTop(2), getStackTop(0), NULL );     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 28: /* select_stmt -> LPAR select_stmt RPAR */
#line 239 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = getStackTop(1);                                                    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 30: /* simple_select -> SELECT opt_alldistinct select_list opt_into FROM from_table_list opt_where opt_groupby opt_having opt_orderby opt_access opt_lockmode */
#line 257 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), SELECT,
    																		getStackTop(10),
    																		getStackTop(9),
    																		getStackTop(8),
    																		newNode( getPos(5), FROM, getStackTop(6), NULL ),
    																		getStackTop(5),
    																		getStackTop(4),
    																		getStackTop(3),
    																		getStackTop(2),
    																		getStackTop(1),
    																		getStackTop(0),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 31: /* opt_all -> epsilon */
#line 272 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = NULL;                                     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 32: /* opt_all -> ALL */
#line 273 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), ALL, NULL );           }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 33: /* opt_alldistinct -> epsilon */
#line 276 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(0), ALL, NULL );	         }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 34: /* opt_alldistinct -> ALL */
#line 277 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), ALL, NULL );	         }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 35: /* opt_alldistinct -> DISTINCT */
#line 278 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), DISTINCT, NULL );      }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 36: /* select_list -> select_list COMMA select_elem */
#line 281 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), COMMA, getStackTop(2), getStackTop(0), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 38: /* select_elem -> STAR */
#line 285 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), STAR, NULL );          }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 39: /* select_elem -> name DOT STAR */
#line 286 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), DOT,
    																		getStackTop(2),
    																		newNode( getPos(3), STAR, NULL ),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 41: /* opt_into -> epsilon */
#line 294 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(0), INTO,NULL );           }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 42: /* opt_into -> INTO hostvar_list */
#line 295 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), INTO, getStackTop(0), NULL );      }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 43: /* hostvar_list -> hostvar_list COMMA hostindi_var */
#line 298 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), COMMA, getStackTop(2), getStackTop(0), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 45: /* hostindi_var -> hostvar opt_indicator */
#line 303 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = getStackTop(1); } /*  newNode( HOSTVAR, $1, $2, NULL ); } */
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 49: /* from_table_list -> from_table_list COMMA from_table */
#line 312 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), COMMA, getStackTop(2), getStackTop(0), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 52: /* from_table -> name name */
#line 317 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), DOT, getStackTop(1), getStackTop(0), NULL );   }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 53: /* from_table -> LPAR from_table opt_join_type JOIN from_table ON search_condition RPAR */
#line 320 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), JOIN, getStackTop(6), getStackTop(5), getStackTop(3), getStackTop(1), NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 54: /* opt_join_type -> epsilon */
#line 324 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(0), INNER, NULL ); 	     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 55: /* opt_join_type -> INNER */
#line 325 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), INNER, NULL ); 	     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 56: /* opt_join_type -> LEFT */
#line 326 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), LEFT , NULL ); 	     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 57: /* opt_where -> epsilon */
#line 329 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(0), WHERE, NULL ); 	     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 58: /* opt_where -> WHERE search_condition */
#line 330 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), WHERE, getStackTop(0), NULL );     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 59: /* opt_having -> epsilon */
#line 333 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(0), HAVING, NULL );	     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 60: /* opt_having -> HAVING search_condition */
#line 334 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), HAVING, getStackTop(0), NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 61: /* opt_groupby -> epsilon */
#line 337 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(0), GROUP, NULL ); 	     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 62: /* opt_groupby -> GROUP BY expr_list */
#line 338 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), GROUP, getStackTop(0), NULL );     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 63: /* opt_orderby -> epsilon */
#line 341 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(0), ORDER, NULL ); 	     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 64: /* opt_orderby -> ORDER BY order_elem_list */
#line 342 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), ORDER, getStackTop(0), NULL );     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 65: /* order_elem_list -> order_elem_list COMMA order_elem */
#line 345 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), COMMA, getStackTop(2), getStackTop(0), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 67: /* order_elem -> expr opt_ascdesc */
#line 349 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), BY, getStackTop(1), getStackTop(0), NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 68: /* opt_ascdesc -> epsilon */
#line 352 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(0), ASCENDING , NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 69: /* opt_ascdesc -> ASCENDING */
#line 353 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), ASCENDING , NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 70: /* opt_ascdesc -> DESCENDING */
#line 354 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), DESCENDING, NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 71: /* opt_access -> epsilon */
#line 357 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(0), ACCESSS, NULL	 );      }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 72: /* opt_access -> FOR access_mode ACCESSS */
#line 358 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), ACCESSS, getStackTop(1), NULL );   }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 73: /* opt_access -> access_mode ACCESSS */
#line 359 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), ACCESSS, getStackTop(1), NULL );   }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 74: /* access_mode -> BROWSE */
#line 362 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), BROWSE    , NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 75: /* access_mode -> STABLE */
#line 363 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), STABLE    , NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 76: /* access_mode -> REPEATABLE */
#line 364 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), REPEATABLE, NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 77: /* opt_lockmode -> epsilon */
#line 367 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode ( getPos(0), MODE, NULL	 );      }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 78: /* opt_lockmode -> INSYM lockmode MODE */
#line 368 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode ( getPos(2), MODE, getStackTop(1), NULL );     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 79: /* opt_lockmode -> lockmode MODE */
#line 369 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode ( getPos(1), MODE, getStackTop(1), NULL );     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 80: /* lockmode -> SHARE */
#line 372 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), SHARE	, NULL );        }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 81: /* lockmode -> EXCLUSIVE */
#line 373 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), EXCLUSIVE , NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 82: /* search_condition -> search_condition OR search_condition */
#line 376 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), OR , getStackTop(2), getStackTop(0), NULL);    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 83: /* search_condition -> search_condition AND search_condition */
#line 377 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), AND, getStackTop(2), getStackTop(0), NULL);    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 84: /* search_condition -> NOT boolean_primary */
#line 378 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), NOT, getStackTop(0), NULL );	     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 87: /* boolean_primary -> LPAR search_condition RPAR */
#line 383 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = getStackTop(1); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 88: /* predicate -> par_expr_list rel_op par_expr_list */
#line 386 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), getStackTop(1)->token(), getStackTop(2), getStackTop(0), NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 89: /* predicate -> EXISTS LPAR select_stmt RPAR */
#line 388 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), EXISTS, getStackTop(1), NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 90: /* predicate -> par_expr_list BETWEEN par_expr_list AND par_expr_list */
#line 391 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), BETWEEN, getStackTop(4), getStackTop(2), getStackTop(0), NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 91: /* predicate -> par_expr_list NOT BETWEEN par_expr_list AND par_expr_list */
#line 394 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), NOT,
    																		newNode( getPos(3), BETWEEN, getStackTop(5), getStackTop(2), getStackTop(0), NULL ),
    																		NULL );
    																}
    /* actually only 1 single expr. but this gives shift/reduce-conflicts. We check it in the compiler */
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 92: /* predicate -> par_expr_list INSYM LPAR set_expr RPAR */
#line 399 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), INSYM, getStackTop(4), getStackTop(1), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 93: /* predicate -> par_expr_list NOT INSYM LPAR set_expr RPAR */
#line 401 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), NOT,
    																		newNode( getPos(3), INSYM, getStackTop(5), getStackTop(1), NULL ),
    																		NULL );
    																}
    /* actually only 1 single expr. but this gives shift/reduce-conflicts. We check it in the compiler */
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 94: /* predicate -> par_expr_list LIKE expr */
#line 406 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), LIKE, getStackTop(2), getStackTop(0), NULL );  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 95: /* predicate -> par_expr_list NOT LIKE expr */
#line 407 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), NOT,
    																		newNode( getPos(3), LIKE, getStackTop(3), getStackTop(0), NULL),
    																		NULL );
    																}
    /* actually only 1 single expr. but this gives shift/reduce-conflicts. We check it in the compiler */
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 96: /* predicate -> par_expr_list IS NULLVAL */
#line 412 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), ISNULL, getStackTop(2), NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 97: /* predicate -> par_expr_list IS NOT NULLVAL */
#line 413 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(3), NOT,
    																		newNode( getPos(2), ISNULL, getStackTop(3), NULL ),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 101: /* rel_op -> RELOPLE */
#line 428 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), RELOPLE,NULL);				}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 102: /* rel_op -> RELOPLT */
#line 429 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), RELOPLT,NULL);				}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 103: /* rel_op -> RELOPGE */
#line 430 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), RELOPGE,NULL);				}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 104: /* rel_op -> RELOPGT */
#line 431 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), RELOPGT,NULL);				}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 105: /* rel_op -> EQUAL */
#line 432 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), EQUAL  ,NULL);				}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 106: /* rel_op -> NOTEQ */
#line 433 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), NOTEQ  ,NULL);				}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 107: /* expr_list -> expr_list COMMA expr */
#line 436 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), COMMA, getStackTop(2), getStackTop(0), NULL );	}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 109: /* expr -> expr PLUS expr */
#line 440 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), PLUS  , getStackTop(2), getStackTop(0), NULL );	}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 110: /* expr -> expr MINUS expr */
#line 441 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), MINUS , getStackTop(2), getStackTop(0), NULL );	}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 111: /* expr -> expr CONCAT expr */
#line 442 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), CONCAT, getStackTop(2), getStackTop(0), NULL);	}
    /* need to be here to avoid shift/reduce-conflicts */
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 112: /* expr -> expr STAR expr */
#line 444 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), MULT  , getStackTop(2), getStackTop(0), NULL );	}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 113: /* expr -> expr DIVOP expr */
#line 445 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), DIVOP , getStackTop(2), getStackTop(0), NULL );	}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 114: /* expr -> expr MODOP expr */
#line 446 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), MODOP , getStackTop(2), getStackTop(0), NULL );	}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 115: /* expr -> expr EXPO expr */
#line 447 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), EXPO  , getStackTop(2), getStackTop(0), NULL );	}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 116: /* expr -> MINUS unary */
#line 448 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), MINUS , getStackTop(0), NULL );		}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 117: /* expr -> PLUS unary */
#line 449 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = getStackTop(0); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 127: /* unary -> CURRENTDATE */
#line 461 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), CURRENTDATE, NULL );      }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 128: /* unary -> CURRENTTIME */
#line 462 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), CURRENTTIME, NULL );      }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 129: /* unary -> CURRENTTIMESTAMP */
#line 463 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), CURRENTTIMESTAMP, NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 130: /* unary -> NULLVAL */
#line 464 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), NULLVAL, NULL );		    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 131: /* unary -> LPAR expr RPAR */
#line 465 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = getStackTop(1);                                          }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 132: /* unary -> CAST LPAR expr AS type_def RPAR */
#line 466 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), CAST, getStackTop(3), getStackTop(1), NULL );     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 133: /* unary -> LPAR select_stmt RPAR */
#line 467 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = getStackTop(1);                                          }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 134: /* unary -> SUBSTRING LPAR expr FROM expr FOR expr RPAR */
#line 468 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(  getPos(1), SUBSTRING, getStackTop(5), getStackTop(3), getStackTop(1), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 135: /* unary -> SUBSTRING LPAR expr COMMA expr COMMA expr RPAR */
#line 469 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    {m_dollardollar = newNode(  getPos(1), SUBSTRING, getStackTop(5), getStackTop(3), getStackTop(1), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 136: /* unary -> TYPEDATE LPAR expr COMMA expr COMMA expr RPAR */
#line 470 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), TYPEDATE , getStackTop(5), getStackTop(3), getStackTop(1), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 137: /* unary -> TYPETIME LPAR expr COMMA expr COMMA expr RPAR */
#line 471 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), TYPETIME , getStackTop(5), getStackTop(3), getStackTop(1), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 138: /* unary -> TYPETIMESTAMP LPAR expr COMMA expr COMMA expr COMMA expr COMMA expr COMMA expr RPAR */
#line 474 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), TYPETIMESTAMP, getStackTop(11), getStackTop(9), getStackTop(7), getStackTop(5), getStackTop(3), getStackTop(1), NULL );
                                                                    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 139: /* unary -> COUNT LPAR count_arg RPAR */
#line 476 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), COUNT, getStackTop(1), NULL); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 140: /* unary -> min_max_sum LPAR opt_alldistinct expr RPAR */
#line 477 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), getStackTop(4)->token(), getStackTop(2), getStackTop(1), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 141: /* min_max_sum -> MIN */
#line 480 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), MIN,NULL); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 142: /* min_max_sum -> MAX */
#line 481 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), MAX,NULL); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 143: /* min_max_sum -> SUM */
#line 482 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), SUM,NULL); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 144: /* count_arg -> opt_alldistinct expr */
#line 485 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), getStackTop(1)->token(), getStackTop(0), NULL );    }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 145: /* count_arg -> STAR */
#line 486 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), STAR,NULL);				 }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 147: /* tab_col -> name DOT name */
#line 490 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode ( getPos(2), DOT, getStackTop(2), getStackTop(0), NULL );      }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 148: /* declare_stmt -> DECLARE name CURSOR FOR select_stmt */
#line 493 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode ( getPos(1), DECLARE, getStackTop(3), getStackTop(0), NULL );  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 149: /* fetch_stmt -> FETCH name INTO hostvar_list */
#line 496 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), FETCH, getStackTop(2), getStackTop(0), NULL );     }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 150: /* create_stmt -> CREATE TABLE name LIKE name */
#line 499 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), CREATE,
    																		newNode(getPos(2), TABLE,NULL),
    																		newNode(getPos(4), LIKE,NULL),
    																		getStackTop(2),
    																		getStackTop(0),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 151: /* create_stmt -> CREATE TABLE name LPAR col_def_list COMMA PRIMARY KEY LPAR keyfield_list RPAR RPAR */
#line 509 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), CREATE,
    																		newNode(getPos(2), TABLE,NULL),
    																		newNode(getPos(7), KEY, getStackTop(2), NULL ),
    																		getStackTop(9),
    																		getStackTop(7),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 152: /* create_stmt -> CREATE opt_unique INDEX name ON name LPAR keyfield_list RPAR */
#line 517 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), CREATE,
    																		newNode(getPos(3), INDEX,NULL),
    																		getStackTop(7),
    																		getStackTop(5),
    																		getStackTop(3),
    																		getStackTop(1),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 153: /* opt_unique -> epsilon */
#line 527 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(0), NOT,
    																		newNode(getPos(0), UNIQUE,NULL),
    																		NULL);
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 154: /* opt_unique -> UNIQUE */
#line 531 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), UNIQUE,NULL);
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 155: /* keyfield_list -> keyfield_list COMMA keyfield */
#line 535 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), COMMA, getStackTop(2), getStackTop(0), NULL );       }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 157: /* keyfield -> name opt_ascdesc */
#line 539 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), COLUMN, getStackTop(1), getStackTop(0), NULL );      }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 158: /* col_def_list -> col_def_list COMMA col_def */
#line 542 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(2), COMMA, getStackTop(2), getStackTop(0), NULL );       }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 160: /* col_def -> name type_def opt_not_null opt_defaultvalue */
#line 546 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), COLUMN, getStackTop(3), getStackTop(2), getStackTop(1), getStackTop(0), NULL ); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 161: /* type_def -> opt_sign TYPECHAR */
#line 549 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(2), TYPECHAR	   , getStackTop(1),     NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 162: /* type_def -> opt_sign TYPECHAR LPAR number_const RPAR */
#line 550 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(2), TYPECHAR	   , getStackTop(4), getStackTop(1), NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 163: /* type_def -> opt_sign TYPESHORT */
#line 551 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(2), TYPESHORT	   , getStackTop(1),     NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 164: /* type_def -> opt_sign TYPEINT */
#line 552 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(2), TYPEINT 	   , getStackTop(1),     NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 165: /* type_def -> opt_sign TYPELONG */
#line 553 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(2), TYPELONG	   , getStackTop(1),     NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 166: /* type_def -> TYPEFLOAT */
#line 554 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), TYPEFLOAT	   ,         NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 167: /* type_def -> TYPEDOUBLE */
#line 555 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), TYPEDOUBLE   ,         NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 168: /* type_def -> TYPEDATE */
#line 556 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), TYPEDATE	   ,         NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 169: /* type_def -> TYPETIME */
#line 557 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), TYPETIME	   ,         NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 170: /* type_def -> TYPETIMESTAMP */
#line 558 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), TYPETIMESTAMP,         NULL);  }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 171: /* type_def -> TYPEVARCHAR LPAR number_const RPAR */
#line 559 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), TYPEVARCHAR  , getStackTop(1),     NULL);	 }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 172: /* opt_sign -> epsilon */
#line 562 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(0), SIGNED,NULL);	                 }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 173: /* opt_sign -> SIGNED */
#line 563 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), SIGNED,NULL);	                 }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 174: /* opt_sign -> UNSIGNED */
#line 564 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), UNSIGNED,NULL);                }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 175: /* opt_not_null -> epsilon */
#line 567 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(0), NULLVAL,NULL);                 } /* default null allowed */
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 176: /* opt_not_null -> NOT NULLVAL */
#line 568 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), NOT,
    																		newNode(getPos(2), NULLVAL,NULL),
    																		NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 177: /* opt_defaultvalue -> epsilon */
#line 574 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(0), DEFAULT, NULL);                }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 178: /* opt_defaultvalue -> DEFAULT constant */
#line 575 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode(getPos(1), DEFAULT, getStackTop(0), NULL);            }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 181: /* constant -> PLUS number_const */
#line 580 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = getStackTop(0);                                              }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 182: /* constant -> MINUS number_const */
#line 581 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), NUMBER, -getStackTop(0)->number());       }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 186: /* drop_stmt -> DROP TABLE name */
#line 587 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), DROP,
    																		newNode(getPos(2), TABLE	, NULL),
    																		getStackTop(0), NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 187: /* drop_stmt -> DROP INDEX name */
#line 591 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), DROP,
    																		newNode(getPos(2), INDEX	, NULL),
    																		getStackTop(0), NULL );
    																}
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 188: /* explain_stmt -> EXPLAIN stmt */
#line 597 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), EXPLAIN, getStackTop(0), NULL	);           }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 189: /* name -> NAME */
#line 600 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), NAME, getText());               }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 190: /* hostvar -> HOSTVAR */
#line 603 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), HOSTVAR, getText());            }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 191: /* param -> PARAM */
#line 606 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), PARAM, getText());              }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 192: /* number_const -> NUMBER */
#line 609 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), NUMBER, _ttof(getText()));      }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 193: /* string_const -> STRING */
#line 612 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), STRING, getText());             }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 194: /* date_const -> DATECONST */
#line 615 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), DATECONST, ttoDate(getText())); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 195: /* time_const -> TIMECONST */
#line 618 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), TIMECONST, ttoTime(getText())); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  case 196: /* timestamp_const -> TIMESTAMPCONST */
#line 621 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
    { m_dollardollar = newNode( getPos(1), TIMESTAMPCONST, ttoTimestamp(getText())); }
#line 26 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
    break;
  }
  return 0;
}

#line 626 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
Date SqlParser::ttoDate(const TCHAR *str) {
  try {
    return Date(str+1);
  } catch(Exception e) {
    error(getPos(),_T("%s"), e.what());
    return Date();
  }
}

Time SqlParser::ttoTime(const TCHAR *str) {
  try {
    return Time(str+1);
  } catch(Exception e) {
    error(getPos(), _T("%s"), e.what());
    return Time();
  }
}

Timestamp SqlParser::ttoTimestamp(const TCHAR *str) {
  try {
    return Timestamp(str+1);
  } catch(Exception e) {
    error(getPos(), _T("%s"), e.what());
    return Timestamp();
  }
}

void SqlParser::verror(const SourcePosition &pos, const TCHAR *format, va_list argptr) {
  m_tree.vAppendError(pos,SQL_SYNTAX_ERROR, format, argptr);
}

void SqlParser::parse(const SourcePosition &pos, const String &stmt) {
  LexStringStream stream(stmt);
  SqlLex lex(this);
  lex.newStream(&stream,pos);
  setScanner(&lex);
//  setdebug(true);
//  lex.setdebug(true);
  LRparser::parse();
}

SyntaxNode *SqlParser::newNode(const SourcePosition &pos, int token, ...) {
  va_list argptr;
  va_start(argptr,token);
  SyntaxNode *p = m_tree.vFetchTokenNode(token,argptr);
  va_end(argptr);
  p->setpos(pos);
  return p;
}

#line 31 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"
