/* DO NOT EDIT THIS FILE - it is machine generated */
#line 131 "C:\\mytools2015\\Dbase\\SqlParse\\Sql.y"
#include "stdafx.h"
#include "SqlParser.h"
#include <SqlApi.h>
#include <io.h>


#line 33 "C:\\mytools2015\\parsergen\\lib\\parsergencpp.par"

#pragma warning(disable : 4312)

typedef short TableType;

/****************************************************************************\
* Bitset containing 1-bits for compressed states and 0-bits for              *
* uncompressed states. Used by ParserTable to determine how to               *
* interpret the entry in the action-table                                    *
* Number of bytes in bitset = (statecount-1)/8+1                             *
\****************************************************************************/
static const BYTE compressedSet[50] = {
   0xde,0xbf,0x06,0x9e,0xff,0x2d,0x0d,0xfe,0xbf,0xff,0xff,0x3b,0x8b,0x02,0xbc,0x00,0xf0,0xa3,0x9e,0x89
  ,0x26,0x3c,0x50,0xde,0xd4,0x04,0xf2,0x23,0x80,0xc4,0xff,0xac,0x17,0x43,0xc1,0xf5,0x29,0xd9,0x0f,0x76
  ,0xd5,0x00,0xfe,0xff,0x5d,0x3e,0x1f,0x76,0x71,0x9b
}; // Size of table:52 bytes.

/****************************************************************************\
* The action matrix holds the parse action(state,terminal)                   *
* Used in LRParser::parserStep().                                            *
* 2 different formats are used:Compressed and Uncompressed.                  *
*                                                                            *
* Compressed:When there is only 1 possible action in the state.              *
*            or all actions are reduce by the same production.               *
*   If bit 16 (0x8000) is 0, there is only one possible action which is      *
*   encoded as:                                                              *
*      #define   act0001  (void*)((action << 16) | (token&0x7fff)            *
*   State index------+               |                |                      *
*   Highorder 16 bits = action-------+                |                      *
*   Loworder  15 bits = legal token-------------------+                      *
*                                                                            *
*   If bit 16 is 1, the loworder 15 bits is an index.                        *
*      #define   act0002  (void*)((action<<16)  |  0x8000 | (index&0x7fff))  *
*   State index------+               |                |        |             *
*   Highorder 16 bits = action-------+                |        |             *
*   Indicates that this is a multi-item-action-state--+        |             *
*   Loworder  15 bits = index into compressedLasets------------+             *
*                                                                            *
* compressedLasets contains all unique legal lookahead-sets for all          *
* multi-item-action-states.                                                  *
* Number of bytes in each bitset = (terminalcount-1)/8+1                     *
*                                                                            *
* Uncompressed states:                                                       *
*      TableType act0004[] =      { 3, 1, 2, 2,-2, 6, 1 };                   *
*   State index------+              |  |  |                                  *
*   Number of pairs in list---------+  |  |                                  *
*   Legal input symbol-----------------+  |                                  *
*   Action--------------------------------+                                  *
*                                                                            *
* If any uncompressed state has the same actionarray as a previous           *
* generated uncompressed state, a #define is generated to save space.        *
*                                                                            *
*                                                                            *
*   action = getAction(current state, current inputSymbol);                  *
*                                                                            *
*   action <  0   - Reduce by production p, p == -action.                    *
*   action == 0   - Accept. Reduce by production 0.                          *
*   action >  0   - Go to state s (=action),                                 *
*                   and push [s,input,pos] to parser stack.                  *
*                   Then read next symbol from input.                        *
*   action == _ParserError - not found (=unexpected input).                  *
\****************************************************************************/
static const BYTE compressedLasets[266] = {
  /*  0   5 tokens */  0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x0e,0x00,0x40,0x00
  /*  1  64 tokens */ ,0x01,0x3c,0x40,0x24,0x3e,0xde,0xc0,0x7e,0xe8,0xff,0xff,0xff,0xff,0x01
  /*  2  25 tokens */ ,0xfe,0x80,0x3a,0x00,0x00,0x00,0x13,0x80,0x01,0xc0,0x01,0xc0,0x21,0x01
  /*  3   2 tokens */ ,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x04,0x00,0x00,0x00,0x00,0x20,0x00
  /*  4   3 tokens */ ,0x00,0x00,0x00,0x00,0x04,0x04,0x00,0x00,0x00,0x00,0x10,0x00,0x00,0x00
  /*  5  41 tokens */ ,0x01,0x3c,0x00,0x24,0x3e,0x8c,0x80,0x52,0x40,0x00,0xde,0xff,0xdf,0x00
  /*  6  43 tokens */ ,0x81,0x3c,0x00,0x24,0x3e,0x8d,0x80,0x52,0x40,0x00,0xde,0xff,0xdf,0x00
  /*  7   3 tokens */ ,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x40,0x00,0x10,0x00,0x00,0x00
  /*  8   3 tokens */ ,0x01,0x00,0x00,0x00,0x04,0x00,0x00,0x00,0x00,0x00,0x10,0x00,0x00,0x00
  /*  9   2 tokens */ ,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x10,0x00,0x40,0x00
  /* 10  17 tokens */ ,0x01,0x20,0x00,0x20,0x3a,0x00,0x80,0x52,0x00,0x00,0x0e,0x30,0x40,0x00
  /* 11   8 tokens */ ,0x01,0x00,0x00,0x20,0x20,0x00,0x00,0x10,0x00,0x00,0x0e,0x00,0x40,0x00
  /* 12  24 tokens */ ,0xfe,0x80,0x3a,0x00,0x00,0x00,0x13,0x80,0x01,0xc0,0x01,0xc0,0x20,0x01
  /* 13  17 tokens */ ,0x01,0x20,0x00,0x20,0x3a,0x00,0x80,0x52,0x40,0x00,0x1e,0x00,0x40,0x00
  /* 14   4 tokens */ ,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x10,0x00,0x50,0x00
  /* 15   4 tokens */ ,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x80,0x38,0x00,0x00,0x00,0x00
  /* 16  21 tokens */ ,0x01,0x20,0x00,0x20,0x3a,0x52,0xc0,0x52,0x40,0x00,0x1e,0x00,0x40,0x00
  /* 17   2 tokens */ ,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x10,0x00,0x00,0x00
  /* 18  13 tokens */ ,0x01,0x20,0x00,0x20,0x22,0x00,0x00,0x52,0x00,0x00,0x1e,0x00,0x40,0x00
}; // Size of table:268 bytes.

#define act0001 (void*)0x00000000    /* reduce by 0 on EOI                       */
#define act0002 (void*)0xffff0000    /* reduce by 1 on EOI                       */
#define act0003 (void*)0xfffe0000    /* reduce by 2 on EOI                       */
#define act0004 (void*)0xfffd0000    /* reduce by 3 on EOI                       */
#define act0006 (void*)0xfffb0000    /* reduce by 5 on EOI                       */
#define act0007 (void*)0xfffa0000    /* reduce by 6 on EOI                       */
#define act0008 (void*)0xfff90000    /* reduce by 7 on EOI                       */
#define act0009 (void*)0xfff80000    /* reduce by 8 on EOI                       */
#define act0010 (void*)0xfff70000    /* reduce by 9 on EOI                       */
#define act0011 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0012 (void*)0x001b002a    /* shift to 27 on INTO                      */
#define act0013 (void*)0x001c0022    /* shift to 28 on FROM                      */
#define act0015 (void*)0xffe38000    /* reduce by 29 on tokens in set[0]         */
#define act0017 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0018 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0025 (void*)0x002d003b    /* shift to 45 on SET                       */
#define act0026 (void*)0xff43800e    /* reduce by 189 on tokens in set[1]        */
#define act0027 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0028 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0031 (void*)0xffde801c    /* reduce by 34 on tokens in set[2]         */
#define act0032 (void*)0xffdd801c    /* reduce by 35 on tokens in set[2]         */
#define act0033 (void*)0x00580016    /* shift to 88 on CURSOR                    */
#define act0034 (void*)0x0059002a    /* shift to 89 on INTO                      */
#define act0035 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0036 (void*)0x005b0026    /* shift to 91 on INDEX                     */
#define act0037 (void*)0xff660026    /* reduce by 154 on INDEX                   */
#define act0038 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0039 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0040 (void*)0xff440000    /* reduce by 188 on EOI                     */
#define act0042 (void*)0xffe0802a    /* reduce by 32 on tokens in set[3]         */
#define act0043 (void*)0xffe68000    /* reduce by 26 on tokens in set[0]         */
#define act0045 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0048 (void*)0xffe48000    /* reduce by 28 on tokens in set[0]         */
#define act0050 (void*)0xffdb8038    /* reduce by 37 on tokens in set[4]         */
#define act0051 (void*)0xffda8038    /* reduce by 38 on tokens in set[4]         */
#define act0057 (void*)0xff8a8046    /* reduce by 118 on tokens in set[5]        */
#define act0058 (void*)0xff898046    /* reduce by 119 on tokens in set[5]        */
#define act0059 (void*)0xff888046    /* reduce by 120 on tokens in set[5]        */
#define act0060 (void*)0xff878046    /* reduce by 121 on tokens in set[5]        */
#define act0061 (void*)0xff868046    /* reduce by 122 on tokens in set[5]        */
#define act0062 (void*)0xff858046    /* reduce by 123 on tokens in set[5]        */
#define act0063 (void*)0xff848046    /* reduce by 124 on tokens in set[5]        */
#define act0064 (void*)0xff838046    /* reduce by 125 on tokens in set[5]        */
#define act0065 (void*)0xff828046    /* reduce by 126 on tokens in set[5]        */
#define act0066 (void*)0xff818046    /* reduce by 127 on tokens in set[5]        */
#define act0067 (void*)0xff808046    /* reduce by 128 on tokens in set[5]        */
#define act0068 (void*)0xff7f8046    /* reduce by 129 on tokens in set[5]        */
#define act0069 (void*)0xff7e8046    /* reduce by 130 on tokens in set[5]        */
#define act0071 (void*)0x007b0065    /* shift to 123 on LPAR                     */
#define act0072 (void*)0x007c0065    /* shift to 124 on LPAR                     */
#define act0073 (void*)0x007d0065    /* shift to 125 on LPAR                     */
#define act0074 (void*)0x007e0065    /* shift to 126 on LPAR                     */
#define act0075 (void*)0x007f0065    /* shift to 127 on LPAR                     */
#define act0076 (void*)0x00800065    /* shift to 128 on LPAR                     */
#define act0077 (void*)0x00810065    /* shift to 129 on LPAR                     */
#define act0078 (void*)0xff730065    /* reduce by 141 on LPAR                    */
#define act0079 (void*)0xff720065    /* reduce by 142 on LPAR                    */
#define act0080 (void*)0xff710065    /* reduce by 143 on LPAR                    */
#define act0081 (void*)0xff428054    /* reduce by 190 on tokens in set[6]        */
#define act0082 (void*)0xff418046    /* reduce by 191 on tokens in set[5]        */
#define act0083 (void*)0xff408046    /* reduce by 192 on tokens in set[5]        */
#define act0084 (void*)0xff3f8046    /* reduce by 193 on tokens in set[5]        */
#define act0085 (void*)0xff3e8046    /* reduce by 194 on tokens in set[5]        */
#define act0086 (void*)0xff3d8046    /* reduce by 195 on tokens in set[5]        */
#define act0087 (void*)0xff3c8046    /* reduce by 196 on tokens in set[5]        */
#define act0088 (void*)0x00820021    /* shift to 130 on FOR                      */
#define act0089 (void*)0x00510007    /* shift to 81 on HOSTVAR                   */
#define act0091 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0092 (void*)0xff460000    /* reduce by 186 on EOI                     */
#define act0093 (void*)0xff450000    /* reduce by 187 on EOI                     */
#define act0096 (void*)0xfff48062    /* reduce by 12 on tokens in set[7]         */
#define act0097 (void*)0x008a0056    /* shift to 138 on EQUAL                    */
#define act0099 (void*)0x008e0065    /* shift to 142 on LPAR                     */
#define act0103 (void*)0x009e0022    /* shift to 158 on FROM                     */
#define act0105 (void*)0x00510007    /* shift to 81 on HOSTVAR                   */
#define act0114 (void*)0xffd38046    /* reduce by 45 on tokens in set[5]         */
#define act0115 (void*)0xffd18046    /* reduce by 47 on tokens in set[5]         */
#define act0116 (void*)0x00510007    /* shift to 81 on HOSTVAR                   */
#define act0117 (void*)0xff8c8046    /* reduce by 116 on tokens in set[5]        */
#define act0119 (void*)0xff8b8046    /* reduce by 117 on tokens in set[5]        */
#define act0132 (void*)0xffd48070    /* reduce by 44 on tokens in set[8]         */
#define act0133 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0134 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0135 (void*)0x00be0036    /* shift to 190 on ON                       */
#define act0136 (void*)0xfff60000    /* reduce by 10 on EOI                      */
#define act0137 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0141 (void*)0xffec807e    /* reduce by 20 on tokens in set[9]         */
#define act0143 (void*)0xffe80000    /* reduce by 24 on EOI                      */
#define act0145 (void*)0x00c70008    /* shift to 199 on ACCESSS                  */
#define act0146 (void*)0xffb60008    /* reduce by 74 on ACCESSS                  */
#define act0147 (void*)0xffb50008    /* reduce by 75 on ACCESSS                  */
#define act0148 (void*)0xffb40008    /* reduce by 76 on ACCESSS                  */
#define act0151 (void*)0xffab808c    /* reduce by 85 on tokens in set[10]        */
#define act0152 (void*)0xffaa808c    /* reduce by 86 on tokens in set[10]        */
#define act0155 (void*)0x00da0065    /* shift to 218 on LPAR                     */
#define act0159 (void*)0xffdc8038    /* reduce by 36 on tokens in set[4]         */
#define act0161 (void*)0xffd98038    /* reduce by 39 on tokens in set[4]         */
#define act0162 (void*)0xff6d8046    /* reduce by 147 on tokens in set[5]        */
#define act0165 (void*)0xff918046    /* reduce by 111 on tokens in set[5]        */
#define act0170 (void*)0xffd08046    /* reduce by 48 on tokens in set[5]         */
#define act0171 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0172 (void*)0xff7d8046    /* reduce by 131 on tokens in set[5]        */
#define act0173 (void*)0xff7b8046    /* reduce by 133 on tokens in set[5]        */
#define act0180 (void*)0x00e70066    /* shift to 231 on RPAR                     */
#define act0182 (void*)0xff6f0066    /* reduce by 145 on RPAR                    */
#define act0185 (void*)0x00510007    /* shift to 81 on HOSTVAR                   */
#define act0186 (void*)0xff6a0000    /* reduce by 150 on EOI                     */
#define act0187 (void*)0x00eb0054    /* shift to 235 on COMMA                    */
#define act0188 (void*)0xff610054    /* reduce by 159 on COMMA                   */
#define act0190 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0191 (void*)0xfff58062    /* reduce by 11 on tokens in set[7]         */
#define act0194 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0196 (void*)0x00fc0066    /* shift to 252 on RPAR                     */
#define act0198 (void*)0x00fd0008    /* shift to 253 on ACCESSS                  */
#define act0199 (void*)0xffb7809a    /* reduce by 73 on tokens in set[11]        */
#define act0202 (void*)0xffac808c    /* reduce by 84 on tokens in set[10]        */
#define act0209 (void*)0x01060065    /* shift to 262 on LPAR                     */
#define act0212 (void*)0xff9b80a8    /* reduce by 101 on tokens in set[12]       */
#define act0213 (void*)0xff9a80a8    /* reduce by 102 on tokens in set[12]       */
#define act0214 (void*)0xff9980a8    /* reduce by 103 on tokens in set[12]       */
#define act0215 (void*)0xff9880a8    /* reduce by 104 on tokens in set[12]       */
#define act0216 (void*)0xff9780a8    /* reduce by 105 on tokens in set[12]       */
#define act0217 (void*)0xff9680a8    /* reduce by 106 on tokens in set[12]       */
#define act0221 (void*)0xffce80b6    /* reduce by 50 on tokens in set[13]        */
#define act0231 (void*)0xff758046    /* reduce by 139 on tokens in set[5]        */
#define act0234 (void*)0xffd58070    /* reduce by 43 on tokens in set[8]         */
#define act0238 (void*)0xff5a80c4    /* reduce by 166 on tokens in set[14]       */
#define act0239 (void*)0xff5980c4    /* reduce by 167 on tokens in set[14]       */
#define act0240 (void*)0xff5880c4    /* reduce by 168 on tokens in set[14]       */
#define act0241 (void*)0xff5780c4    /* reduce by 169 on tokens in set[14]       */
#define act0242 (void*)0xff5680c4    /* reduce by 170 on tokens in set[14]       */
#define act0243 (void*)0x011f0065    /* shift to 287 on LPAR                     */
#define act0244 (void*)0xff5380d2    /* reduce by 173 on tokens in set[15]       */
#define act0245 (void*)0xff5280d2    /* reduce by 174 on tokens in set[15]       */
#define act0246 (void*)0x01200065    /* shift to 288 on LPAR                     */
#define act0247 (void*)0x01210065    /* shift to 289 on LPAR                     */
#define act0250 (void*)0xffeb807e    /* reduce by 21 on tokens in set[9]         */
#define act0251 (void*)0xffef0000    /* reduce by 17 on EOI                      */
#define act0253 (void*)0xffb8809a    /* reduce by 72 on tokens in set[11]        */
#define act0255 (void*)0xffad808c    /* reduce by 83 on tokens in set[10]        */
#define act0256 (void*)0xffa9808c    /* reduce by 87 on tokens in set[10]        */
#define act0257 (void*)0xffa8808c    /* reduce by 88 on tokens in set[10]        */
#define act0258 (void*)0x0124005d    /* shift to 292 on AND                      */
#define act0260 (void*)0x01260065    /* shift to 294 on LPAR                     */
#define act0264 (void*)0xffa0808c    /* reduce by 96 on tokens in set[10]        */
#define act0265 (void*)0x012b0034    /* shift to 299 on NULLVAL                  */
#define act0270 (void*)0xffcc80e0    /* reduce by 52 on tokens in set[16]        */
#define act0272 (void*)0x01330066    /* shift to 307 on RPAR                     */
#define act0278 (void*)0xff748046    /* reduce by 140 on tokens in set[5]        */
#define act0279 (void*)0x0139002d    /* shift to 313 on KEY                      */
#define act0280 (void*)0xff620054    /* reduce by 158 on COMMA                   */
#define act0282 (void*)0x013c0034    /* shift to 316 on NULLVAL                  */
#define act0284 (void*)0xff5d80c4    /* reduce by 163 on tokens in set[14]       */
#define act0285 (void*)0xff5c80c4    /* reduce by 164 on tokens in set[14]       */
#define act0286 (void*)0xff5b80c4    /* reduce by 165 on tokens in set[14]       */
#define act0287 (void*)0x00530002    /* shift to 83 on NUMBER                    */
#define act0288 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0291 (void*)0xfff10000    /* reduce by 15 on EOI                      */
#define act0293 (void*)0x0145005d    /* shift to 325 on AND                      */
#define act0296 (void*)0x01470066    /* shift to 327 on RPAR                     */
#define act0299 (void*)0xff9f808c    /* reduce by 97 on tokens in set[10]        */
#define act0300 (void*)0xffa7808c    /* reduce by 89 on tokens in set[10]        */
#define act0302 (void*)0x014a000e    /* shift to 330 on BY                       */
#define act0303 (void*)0xffcf80b6    /* reduce by 49 on tokens in set[13]        */
#define act0304 (void*)0x014b002c    /* shift to 331 on JOIN                     */
#define act0305 (void*)0xffc9002c    /* reduce by 55 on JOIN                     */
#define act0306 (void*)0xffc8002c    /* reduce by 56 on JOIN                     */
#define act0307 (void*)0xff7c8046    /* reduce by 132 on tokens in set[5]        */
#define act0313 (void*)0x01510065    /* shift to 337 on LPAR                     */
#define act0314 (void*)0xff600054    /* reduce by 160 on COMMA                   */
#define act0316 (void*)0xff5080ee    /* reduce by 176 on tokens in set[17]       */
#define act0317 (void*)0x00530002    /* shift to 83 on NUMBER                    */
#define act0318 (void*)0x015b0066    /* shift to 347 on RPAR                     */
#define act0320 (void*)0xff64807e    /* reduce by 156 on tokens in set[9]        */
#define act0322 (void*)0x01610066    /* shift to 353 on RPAR                     */
#define act0324 (void*)0xffa6808c    /* reduce by 90 on tokens in set[10]        */
#define act0326 (void*)0x01640066    /* shift to 356 on RPAR                     */
#define act0327 (void*)0xffa4808c    /* reduce by 92 on tokens in set[10]        */
#define act0337 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0338 (void*)0xff4e0054    /* reduce by 178 on COMMA                   */
#define act0339 (void*)0xff4d0054    /* reduce by 179 on COMMA                   */
#define act0340 (void*)0xff4c0054    /* reduce by 180 on COMMA                   */
#define act0341 (void*)0x00530002    /* shift to 83 on NUMBER                    */
#define act0342 (void*)0x00530002    /* shift to 83 on NUMBER                    */
#define act0343 (void*)0xff490054    /* reduce by 183 on COMMA                   */
#define act0344 (void*)0xff480054    /* reduce by 184 on COMMA                   */
#define act0345 (void*)0xff470054    /* reduce by 185 on COMMA                   */
#define act0346 (void*)0x01720066    /* shift to 370 on RPAR                     */
#define act0347 (void*)0xff5580c4    /* reduce by 171 on tokens in set[14]       */
#define act0348 (void*)0xff680000    /* reduce by 152 on EOI                     */
#define act0349 (void*)0x001a0068    /* shift to 26 on NAME                      */
#define act0350 (void*)0xff63807e    /* reduce by 157 on tokens in set[9]        */
#define act0351 (void*)0xffbb80fc    /* reduce by 69 on tokens in set[18]        */
#define act0352 (void*)0xffba80fc    /* reduce by 70 on tokens in set[18]        */
#define act0354 (void*)0xfff00000    /* reduce by 16 on EOI                      */
#define act0355 (void*)0xffa5808c    /* reduce by 91 on tokens in set[10]        */
#define act0356 (void*)0xffa3808c    /* reduce by 93 on tokens in set[10]        */
#define act0358 (void*)0x0176000e    /* shift to 374 on BY                       */
#define act0361 (void*)0x01770036    /* shift to 375 on ON                       */
#define act0362 (void*)0xff7a8046    /* reduce by 134 on tokens in set[5]        */
#define act0363 (void*)0xff798046    /* reduce by 135 on tokens in set[5]        */
#define act0364 (void*)0xff788046    /* reduce by 136 on tokens in set[5]        */
#define act0365 (void*)0xff778046    /* reduce by 137 on tokens in set[5]        */
#define act0368 (void*)0xff4b0054    /* reduce by 181 on COMMA                   */
#define act0369 (void*)0xff4a0054    /* reduce by 182 on COMMA                   */
#define act0370 (void*)0xff5e80c4    /* reduce by 162 on tokens in set[14]       */
#define act0371 (void*)0xff65807e    /* reduce by 155 on tokens in set[9]        */
#define act0372 (void*)0xfff20000    /* reduce by 14 on EOI                      */
#define act0377 (void*)0x01840066    /* shift to 388 on RPAR                     */
#define act0378 (void*)0xffe28000    /* reduce by 30 on tokens in set[0]         */
#define act0380 (void*)0x01860032    /* shift to 390 on MODE                     */
#define act0381 (void*)0xffb00032    /* reduce by 80 on MODE                     */
#define act0382 (void*)0xffaf0032    /* reduce by 81 on MODE                     */
#define act0384 (void*)0xffbe80fc    /* reduce by 66 on tokens in set[18]        */
#define act0388 (void*)0xff690000    /* reduce by 151 on EOI                     */
#define act0389 (void*)0x018b0032    /* shift to 395 on MODE                     */
#define act0390 (void*)0xffb18000    /* reduce by 79 on tokens in set[0]         */
#define act0392 (void*)0xffbd80fc    /* reduce by 67 on tokens in set[18]        */
#define act0393 (void*)0xffcb80e0    /* reduce by 53 on tokens in set[16]        */
#define act0395 (void*)0xffb28000    /* reduce by 78 on tokens in set[0]         */
#define act0396 (void*)0xffbf80fc    /* reduce by 65 on tokens in set[18]        */
#define act0399 (void*)0xff768046    /* reduce by 138 on tokens in set[5]        */

static const TableType act0000[] = {  10,  18,  19,  23,  17,  25,  13,  28,  20,  31,  21
                                        ,  32,  18,  39,  12,  58,  16,  68,  11, 101,  14};
static const TableType act0005[] = {   4,   0,  -4,  81,  22,  82,  24,  83,  23};
static const TableType act0014[] = {   2,  58,  16, 101,  14};
static const TableType act0016[] = {  27,   1, -33,   2, -33,   3, -33,   4, -33,   5, -33
                                        ,   6, -33,   7, -33,   9,  31,  15, -33,  17, -33
                                        ,  19, -33,  20, -33,  21, -33,  27,  32,  48, -33
                                        ,  49, -33,  52, -33,  63, -33,  64, -33,  78, -33
                                        ,  79, -33,  80, -33,  94, -33,  95, -33,  96, -33
                                        , 101, -33, 104, -33};
static const TableType act0019[] = {   3,  38,-153,  65,  35,  66,  37};
static const TableType act0020[] = {   2,  38,  39,  65,  38};
static const TableType act0022[] = {   3,   9,  42,  58, -31, 101, -31};
static const TableType act0029[] = {   4,  81,  22,  82,  24,  83,  23, 102,  48};
static const TableType act0030[] = {  25,   1,  84,   2,  83,   3,  85,   4,  86,   5,  87
                                        ,   6,  82,   7,  81,  15,  71,  17,  76,  19,  66
                                        ,  20,  67,  21,  68,  48,  79,  49,  78,  52,  69
                                        ,  63,  72,  64,  80,  78,  73,  79,  74,  80,  75
                                        ,  94,  56,  95,  55,  96,  51, 101,  70, 104,  26};
static const TableType act0044[] = {   5,   0, -27,  81, -27,  82, -27,  83,  23, 102, -27};
static const TableType act0046[] = {   3,  58,  16,  69,  99, 101,  98};
static const TableType act0047[] = {   6,   0, -57,  13, -57,  33, -57,  57, -57,  62, -57
                                        ,  70, 102};
static const TableType act0049[] = {   3,  34, -41,  42, 105,  84, 104};
static const TableType act0052[] = {  11,  34,-146,  42,-146,  84,-146,  85, 106,  94,-146
                                        ,  95,-146,  96,-146,  97,-146,  98,-146,  99,-146
                                        , 103,-146};
static const TableType act0053[] = {  10,  34, -40,  42, -40,  84, -40,  94, 107,  95, 108
                                        ,  96, 110,  97, 111,  98, 112,  99, 113, 103, 109};
static const TableType act0054[] = {  43,   0, -46,   7,  81,  10, -46,  11, -46,  12, -46
                                        ,  13, -46,  26, -46,  29, -46,  33, -46,  34, -46
                                        ,  35, -46,  36, -46,  37, -46,  40, 116,  42, -46
                                        ,  43, -46,  47, -46,  55, -46,  57, -46,  60, -46
                                        ,  62, -46,  70, -46,  81, -46,  82, -46,  83, -46
                                        ,  84, -46,  86, -46,  87, -46,  88, -46,  89, -46
                                        ,  90, -46,  91, -46,  92, -46,  93, -46,  94, -46
                                        ,  95, -46,  96, -46,  97, -46,  98, -46,  99, -46
                                        , 100, -46, 102, -46, 103, -46};
static const TableType act0055[] = {  22,   1,  84,   2,  83,   3,  85,   4,  86,   5,  87
                                        ,   6,  82,   7,  81,  15,  71,  17,  76,  19,  66
                                        ,  20,  67,  21,  68,  48,  79,  49,  78,  52,  69
                                        ,  63,  72,  64,  80,  78,  73,  79,  74,  80,  75
                                        , 101,  70, 104,  26};
static const TableType act0070[] = {  25,   1,  84,   2,  83,   3,  85,   4,  86,   5,  87
                                        ,   6,  82,   7,  81,  15,  71,  17,  76,  19,  66
                                        ,  20,  67,  21,  68,  48,  79,  49,  78,  52,  69
                                        ,  58,  16,  63,  72,  64,  80,  78,  73,  79,  74
                                        ,  80,  75,  94,  56,  95,  55, 101, 122, 104,  26};
static const TableType act0090[] = {   2,  47, 133, 101, 134};
static const TableType act0094[] = {   5,   0, -25,  81, -25,  82, -25,  83,  23, 102, -25};
static const TableType act0095[] = {   3,   0, -57,  70, 102,  84, 137};
static const TableType act0098[] = {   3,  58,  16, 101,  14, 104,  26};
static const TableType act0100[] = {   4,   0, -19,  81,  22,  82,  24,  83,  23};
static const TableType act0101[] = {   5,   0, -71,  13, 146,  33, 144,  57, 148,  62, 147};
static const TableType act0102[] = {  26,   1,  84,   2,  83,   3,  85,   4,  86,   5,  87
                                        ,   6,  82,   7,  81,  15,  71,  17,  76,  19,  66
                                        ,  20,  67,  21,  68,  30, 155,  48,  79,  49,  78
                                        ,  52,  69,  63,  72,  64,  80,  78,  73,  79,  74
                                        ,  80,  75,  94,  56,  95,  55, 100, 150, 101, 153
                                        , 104,  26};
static const TableType act0106[] = {   2,  96, 161, 104,  26};
static const TableType act0107[] = {  24,   1,  84,   2,  83,   3,  85,   4,  86,   5,  87
                                        ,   6,  82,   7,  81,  15,  71,  17,  76,  19,  66
                                        ,  20,  67,  21,  68,  48,  79,  49,  78,  52,  69
                                        ,  63,  72,  64,  80,  78,  73,  79,  74,  80,  75
                                        ,  94,  56,  95,  55, 101,  70, 104,  26};
static const TableType act0118[] = {  42,   0,-146,  10,-146,  11,-146,  12,-146,  13,-146
                                        ,  26,-146,  29,-146,  33,-146,  34,-146,  35,-146
                                        ,  36,-146,  37,-146,  42,-146,  43,-146,  47,-146
                                        ,  55,-146,  57,-146,  60,-146,  62,-146,  70,-146
                                        ,  81,-146,  82,-146,  83,-146,  84,-146,  85, 171
                                        ,  86,-146,  87,-146,  88,-146,  89,-146,  90,-146
                                        ,  91,-146,  92,-146,  93,-146,  94,-146,  95,-146
                                        ,  96,-146,  97,-146,  98,-146,  99,-146, 100,-146
                                        , 102,-146, 103,-146};
static const TableType act0120[] = {   8,  94, 107,  95, 108,  96, 110,  97, 111,  98, 112
                                        ,  99, 113, 102, 172, 103, 109};
static const TableType act0121[] = {   4,  81,  22,  82,  24,  83,  23, 102, 173};
static const TableType act0128[] = {  27,   1, -33,   2, -33,   3, -33,   4, -33,   5, -33
                                        ,   6, -33,   7, -33,   9,  31,  15, -33,  17, -33
                                        ,  19, -33,  20, -33,  21, -33,  27,  32,  48, -33
                                        ,  49, -33,  52, -33,  63, -33,  64, -33,  78, -33
                                        ,  79, -33,  80, -33,  94, -33,  95, -33,  96, 182
                                        , 101, -33, 104, -33};
static const TableType act0129[] = {  26,   1, -33,   2, -33,   3, -33,   4, -33,   5, -33
                                        ,   6, -33,   7, -33,   9,  31,  15, -33,  17, -33
                                        ,  19, -33,  20, -33,  21, -33,  27,  32,  48, -33
                                        ,  49, -33,  52, -33,  63, -33,  64, -33,  78, -33
                                        ,  79, -33,  80, -33,  94, -33,  95, -33, 101, -33
                                        , 104, -33};
static const TableType act0131[] = {   2,   0,-149,  84, 185};
static const TableType act0139[] = {   2,  84, 194, 102, 193};
static const TableType act0140[] = {   4,  81,  22,  82,  24,  83,  23, 102, 195};
static const TableType act0142[] = {  25,   1,  84,   2,  83,   3,  85,   4,  86,   5,  87
                                        ,   6,  82,   7,  81,  15,  71,  17,  76,  19,  66
                                        ,  20,  67,  21,  68,  48,  79,  49,  78,  52,  69
                                        ,  63,  72,  64,  80,  78,  73,  79,  74,  80,  75
                                        ,  94,  56,  95,  55, 101,  70, 102, -22, 104,  26};
static const TableType act0144[] = {   3,  13, 146,  57, 148,  62, 147};
static const TableType act0149[] = {  17,   0, -58,  13, -58,  29, -58,  33, -58,  35, -58
                                        ,  36, -58,  37, -58,  55, -58,  57, -58,  60, -58
                                        ,  62, -58,  81, -58,  82, -58,  83, -58,  92, 200
                                        ,  93, 201, 102, -58};
static const TableType act0150[] = {  25,   1,  84,   2,  83,   3,  85,   4,  86,   5,  87
                                        ,   6,  82,   7,  81,  15,  71,  17,  76,  19,  66
                                        ,  20,  67,  21,  68,  30, 155,  48,  79,  49,  78
                                        ,  52,  69,  63,  72,  64,  80,  78,  73,  79,  74
                                        ,  80,  75,  94,  56,  95,  55, 101, 153, 104,  26};
static const TableType act0153[] = {  27,   1,  84,   2,  83,   3,  85,   4,  86,   5,  87
                                        ,   6,  82,   7,  81,  15,  71,  17,  76,  19,  66
                                        ,  20,  67,  21,  68,  30, 155,  48,  79,  49,  78
                                        ,  52,  69,  58,  16,  63,  72,  64,  80,  78,  73
                                        ,  79,  74,  80,  75,  94,  56,  95,  55, 100, 150
                                        , 101, 205, 104,  26};
static const TableType act0154[] = {  11,  12, 207,  37, 209,  43, 211,  47, 210,  86, 216
                                        ,  87, 217,  88, 212,  89, 213,  90, 214,  91, 215
                                        , 100, 208};
static const TableType act0156[] = {  28,   0,-100,  12,-100,  13,-100,  29,-100,  33,-100
                                        ,  35,-100,  36,-100,  37,-100,  43,-100,  47,-100
                                        ,  55,-100,  57,-100,  60,-100,  62,-100,  81,-100
                                        ,  82,-100,  83,-100,  84, 219,  86,-100,  87,-100
                                        ,  88,-100,  89,-100,  90,-100,  91,-100,  92,-100
                                        ,  93,-100, 100,-100, 102,-100};
static const TableType act0157[] = {  35,   0,-108,  12,-108,  13,-108,  29,-108,  33,-108
                                        ,  35,-108,  36,-108,  37,-108,  43,-108,  47,-108
                                        ,  55,-108,  57,-108,  60,-108,  62,-108,  81,-108
                                        ,  82,-108,  83,-108,  84,-108,  86,-108,  87,-108
                                        ,  88,-108,  89,-108,  90,-108,  91,-108,  92,-108
                                        ,  93,-108,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 100,-108, 102,-108, 103, 109};
static const TableType act0158[] = {   2, 101, 223, 104,  26};
static const TableType act0160[] = {   2,  34, -42,  84, 185};
static const TableType act0163[] = {  41,   0,-109,  10,-109,  11,-109,  12,-109,  13,-109
                                        ,  26,-109,  29,-109,  33,-109,  34,-109,  35,-109
                                        ,  36,-109,  37,-109,  42,-109,  43,-109,  47,-109
                                        ,  55,-109,  57,-109,  60,-109,  62,-109,  70,-109
                                        ,  81,-109,  82,-109,  83,-109,  84,-109,  86,-109
                                        ,  87,-109,  88,-109,  89,-109,  90,-109,  91,-109
                                        ,  92,-109,  93,-109,  94,-109,  95,-109,  96, 110
                                        ,  97, 111,  98, 112,  99, 113, 100,-109, 102,-109
                                        , 103, 109};
static const TableType act0164[] = {  41,   0,-110,  10,-110,  11,-110,  12,-110,  13,-110
                                        ,  26,-110,  29,-110,  33,-110,  34,-110,  35,-110
                                        ,  36,-110,  37,-110,  42,-110,  43,-110,  47,-110
                                        ,  55,-110,  57,-110,  60,-110,  62,-110,  70,-110
                                        ,  81,-110,  82,-110,  83,-110,  84,-110,  86,-110
                                        ,  87,-110,  88,-110,  89,-110,  90,-110,  91,-110
                                        ,  92,-110,  93,-110,  94,-110,  95,-110,  96, 110
                                        ,  97, 111,  98, 112,  99, 113, 100,-110, 102,-110
                                        , 103, 109};
static const TableType act0166[] = {  41,   0,-112,  10,-112,  11,-112,  12,-112,  13,-112
                                        ,  26,-112,  29,-112,  33,-112,  34,-112,  35,-112
                                        ,  36,-112,  37,-112,  42,-112,  43,-112,  47,-112
                                        ,  55,-112,  57,-112,  60,-112,  62,-112,  70,-112
                                        ,  81,-112,  82,-112,  83,-112,  84,-112,  86,-112
                                        ,  87,-112,  88,-112,  89,-112,  90,-112,  91,-112
                                        ,  92,-112,  93,-112,  94,-112,  95,-112,  96,-112
                                        ,  97,-112,  98,-112,  99, 113, 100,-112, 102,-112
                                        , 103, 109};
static const TableType act0167[] = {  41,   0,-113,  10,-113,  11,-113,  12,-113,  13,-113
                                        ,  26,-113,  29,-113,  33,-113,  34,-113,  35,-113
                                        ,  36,-113,  37,-113,  42,-113,  43,-113,  47,-113
                                        ,  55,-113,  57,-113,  60,-113,  62,-113,  70,-113
                                        ,  81,-113,  82,-113,  83,-113,  84,-113,  86,-113
                                        ,  87,-113,  88,-113,  89,-113,  90,-113,  91,-113
                                        ,  92,-113,  93,-113,  94,-113,  95,-113,  96,-113
                                        ,  97,-113,  98,-113,  99, 113, 100,-113, 102,-113
                                        , 103, 109};
static const TableType act0168[] = {  41,   0,-114,  10,-114,  11,-114,  12,-114,  13,-114
                                        ,  26,-114,  29,-114,  33,-114,  34,-114,  35,-114
                                        ,  36,-114,  37,-114,  42,-114,  43,-114,  47,-114
                                        ,  55,-114,  57,-114,  60,-114,  62,-114,  70,-114
                                        ,  81,-114,  82,-114,  83,-114,  84,-114,  86,-114
                                        ,  87,-114,  88,-114,  89,-114,  90,-114,  91,-114
                                        ,  92,-114,  93,-114,  94,-114,  95,-114,  96,-114
                                        ,  97,-114,  98,-114,  99, 113, 100,-114, 102,-114
                                        , 103, 109};
static const TableType act0169[] = {  41,   0,-115,  10,-115,  11,-115,  12,-115,  13,-115
                                        ,  26,-115,  29,-115,  33,-115,  34,-115,  35,-115
                                        ,  36,-115,  37,-115,  42,-115,  43,-115,  47,-115
                                        ,  55,-115,  57,-115,  60,-115,  62,-115,  70,-115
                                        ,  81,-115,  82,-115,  83,-115,  84,-115,  86,-115
                                        ,  87,-115,  88,-115,  89,-115,  90,-115,  91,-115
                                        ,  92,-115,  93,-115,  94,-115,  95,-115,  96,-115
                                        ,  97,-115,  98,-115,  99,-115, 100,-115, 102,-115
                                        , 103, 109};
static const TableType act0174[] = {   4,  81,  22,  82,  24,  83,  23, 102, 224};
static const TableType act0175[] = {   8,  10, 225,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0176[] = {   9,  34, 226,  84, 227,  94, 107,  95, 108,  96, 110
                                        ,  97, 111,  98, 112,  99, 113, 103, 109};
static const TableType act0177[] = {   8,  84, 228,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0178[] = {   8,  84, 229,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0179[] = {   8,  84, 230,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0184[] = {   4,   0,-148,  81,  22,  82,  24,  83,  23};
static const TableType act0189[] = {  12,  61, 244,  67, 245,  71,-172,  72, 243,  73, 239
                                        ,  74, 238,  75,-172,  76,-172,  77,-172,  78, 240
                                        ,  79, 241,  80, 242};
static const TableType act0192[] = {  10,   0, -13,  70, -13,  84, -13,  94, 107,  95, 108
                                        ,  96, 110,  97, 111,  98, 112,  99, 113, 103, 109};
static const TableType act0193[] = {   3,  58,  16,  69, 247, 101, 248};
static const TableType act0195[] = {   8,   0, -28,  13, 146,  33, 144,  57, 148,  62, 147
                                        ,  81, -28,  82, -28,  83, -28};
static const TableType act0197[] = {   2,  84, 219, 102, -23};
static const TableType act0203[] = {   3,  92, 200,  93, 201, 102, 256};
static const TableType act0204[] = {  20,  12,-108,  37,-108,  43,-108,  47,-108,  84,-108
                                        ,  86,-108,  87,-108,  88,-108,  89,-108,  90,-108
                                        ,  91,-108,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 100,-108, 102, 172, 103, 109};
static const TableType act0208[] = {   3,  12, 259,  37, 260,  47, 261};
static const TableType act0211[] = {   2,  52, 264, 100, 265};
static const TableType act0220[] = {  17,   0, -57,  13, -57,  29, -57,  33, -57,  35, -57
                                        ,  36, -57,  37, -57,  55, -57,  57, -57,  60, -57
                                        ,  62, -57,  70, 102,  81, -57,  82, -57,  83, -57
                                        ,  84, 269, 102, -57};
static const TableType act0222[] = {  22,   0, -51,  13, -51,  29, -51,  33, -51,  35, -51
                                        ,  36, -51,  37, -51,  41, -51,  44, -51,  46, -51
                                        ,  54, -51,  55, -51,  57, -51,  60, -51,  62, -51
                                        ,  70, -51,  81, -51,  82, -51,  83, -51,  84, -51
                                        , 102, -51, 104,  26};
static const TableType act0224[] = {  23,  12,-133,  37,-133,  43,-133,  47,-133,  81, -28
                                        ,  82, -28,  83, -28,  84,-133,  86,-133,  87,-133
                                        ,  88,-133,  89,-133,  90,-133,  91,-133,  94,-133
                                        ,  95,-133,  96,-133,  97,-133,  98,-133,  99,-133
                                        , 100,-133, 102, -28, 103,-133};
static const TableType act0232[] = {   8,  94, 107,  95, 108,  96, 110,  97, 111,  98, 112
                                        ,  99, 113, 102,-144, 103, 109};
static const TableType act0233[] = {   8,  94, 107,  95, 108,  96, 110,  97, 111,  98, 112
                                        ,  99, 113, 102, 278, 103, 109};
static const TableType act0235[] = {   2,  56, 279, 104,  26};
static const TableType act0236[] = {   3,  24,-175,  84,-175, 100, 282};
static const TableType act0237[] = {   4,  71, 283,  75, 285,  76, 286,  77, 284};
static const TableType act0249[] = {   4,   0, -18,  81,  22,  82,  24,  83,  23};
static const TableType act0254[] = {  17,   0, -82,  13, -82,  29, -82,  33, -82,  35, -82
                                        ,  36, -82,  37, -82,  55, -82,  57, -82,  60, -82
                                        ,  62, -82,  81, -82,  82, -82,  83, -82,  92, -82
                                        ,  93, 201, 102, -82};
static const TableType act0263[] = {  24,   0, -94,  13, -94,  29, -94,  33, -94,  35, -94
                                        ,  36, -94,  37, -94,  55, -94,  57, -94,  60, -94
                                        ,  62, -94,  81, -94,  82, -94,  83, -94,  92, -94
                                        ,  93, -94,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 102, -94, 103, 109};
static const TableType act0266[] = {   4,  81,  22,  82,  24,  83,  23, 102, 300};
static const TableType act0267[] = {  35,   0,-107,  12,-107,  13,-107,  29,-107,  33,-107
                                        ,  35,-107,  36,-107,  37,-107,  43,-107,  47,-107
                                        ,  55,-107,  57,-107,  60,-107,  62,-107,  81,-107
                                        ,  82,-107,  83,-107,  84,-107,  86,-107,  87,-107
                                        ,  88,-107,  89,-107,  90,-107,  91,-107,  92,-107
                                        ,  93,-107,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 100,-107, 102,-107, 103, 109};
static const TableType act0268[] = {  15,   0, -61,  13, -61,  29, -61,  33, -61,  35, 302
                                        ,  36, -61,  37, -61,  55, -61,  57, -61,  60, -61
                                        ,  62, -61,  81, -61,  82, -61,  83, -61, 102, -61};
static const TableType act0271[] = {   3,  41, 305,  44, -54,  46, 306};
static const TableType act0273[] = {   8,  33, 308,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0274[] = {   8,  84, 309,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0275[] = {   8,  84, 310,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0276[] = {   8,  84, 311,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0277[] = {   8,  84, 312,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0281[] = {   2,  24, 315,  84,-177};
static const TableType act0283[] = {   5,  24,-161,  84,-161, 100,-161, 101, 317, 102,-161};
static const TableType act0290[] = {   4,  81,  22,  82,  24,  83,  23, 102, 323};
static const TableType act0295[] = {  24,   0, -95,  13, -95,  29, -95,  33, -95,  35, -95
                                        ,  36, -95,  37, -95,  55, -95,  57, -95,  60, -95
                                        ,  62, -95,  81, -95,  82, -95,  83, -95,  92, -95
                                        ,  93, -95,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 102, -95, 103, 109};
static const TableType act0297[] = {   4,  81,  22,  82,  24,  83,  23, 102, -98};
static const TableType act0298[] = {   2,  84, 219, 102, -99};
static const TableType act0301[] = {  14,   0, -59,  13, -59,  29, -59,  33, -59,  36, 329
                                        ,  37, -59,  55, -59,  57, -59,  60, -59,  62, -59
                                        ,  81, -59,  82, -59,  83, -59, 102, -59};
static const TableType act0315[] = {   7,   1,  84,   2,  83,   3,  85,   4,  86,   5,  87
                                        ,  94, 341,  95, 342};
static const TableType act0319[] = {   2,  84, 349, 102, 348};
static const TableType act0321[] = {   4,  11, 351,  26, 352,  84, -68, 102, -68};
static const TableType act0328[] = {  13,   0, -63,  13, -63,  29, -63,  33, -63,  37, -63
                                        ,  55, 358,  57, -63,  60, -63,  62, -63,  81, -63
                                        ,  82, -63,  83, -63, 102, -63};
static const TableType act0332[] = {   8,  94, 107,  95, 108,  96, 110,  97, 111,  98, 112
                                        ,  99, 113, 102, 362, 103, 109};
static const TableType act0333[] = {   8,  94, 107,  95, 108,  96, 110,  97, 111,  98, 112
                                        ,  99, 113, 102, 363, 103, 109};
static const TableType act0334[] = {   8,  94, 107,  95, 108,  96, 110,  97, 111,  98, 112
                                        ,  99, 113, 102, 364, 103, 109};
static const TableType act0335[] = {   8,  94, 107,  95, 108,  96, 110,  97, 111,  98, 112
                                        ,  99, 113, 102, 365, 103, 109};
static const TableType act0336[] = {   8,  84, 366,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0357[] = {  12,   0, -71,  13, 146,  29, -71,  33, 144,  37, -71
                                        ,  57, 148,  60, -71,  62, 147,  81, -71,  82, -71
                                        ,  83, -71, 102, -71};
static const TableType act0359[] = {  15,   0, -60,  13, -60,  29, -60,  33, -60,  37, -60
                                        ,  55, -60,  57, -60,  60, -60,  62, -60,  81, -60
                                        ,  82, -60,  83, -60,  92, 200,  93, 201, 102, -60};
static const TableType act0360[] = {  15,   0, -62,  13, -62,  29, -62,  33, -62,  36, -62
                                        ,  37, -62,  55, -62,  57, -62,  60, -62,  62, -62
                                        ,  81, -62,  82, -62,  83, -62,  84, 219, 102, -62};
static const TableType act0367[] = {   2,  84, 349, 102, 377};
static const TableType act0373[] = {   8,   0, -77,  29, 382,  37, 379,  60, 381,  81, -77
                                        ,  82, -77,  83, -77, 102, -77};
static const TableType act0376[] = {   8,  84, 387,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0379[] = {   2,  29, 382,  60, 381};
static const TableType act0383[] = {  13,   0, -64,  13, -64,  29, -64,  33, -64,  37, -64
                                        ,  57, -64,  60, -64,  62, -64,  81, -64,  82, -64
                                        ,  83, -64,  84, 391, 102, -64};
static const TableType act0385[] = {  22,   0, -68,  11, 351,  13, -68,  26, 352,  29, -68
                                        ,  33, -68,  37, -68,  57, -68,  60, -68,  62, -68
                                        ,  81, -68,  82, -68,  83, -68,  84, -68,  94, 107
                                        ,  95, 108,  96, 110,  97, 111,  98, 112,  99, 113
                                        , 102, -68, 103, 109};
static const TableType act0386[] = {   3,  92, 200,  93, 201, 102, 393};
static const TableType act0394[] = {   8,  84, 397,  94, 107,  95, 108,  96, 110,  97, 111
                                        ,  98, 112,  99, 113, 103, 109};
static const TableType act0398[] = {   8,  94, 107,  95, 108,  96, 110,  97, 111,  98, 112
                                        ,  99, 113, 102, 399, 103, 109};

// Total size of uncompressed actNNNN tables:6044 bytes.

#define act0021 act0000 /* Saved  44 bytes */
#define act0023 act0014 /* Saved  12 bytes */
#define act0024 act0014 /* Saved  12 bytes */
#define act0041 act0014 /* Saved  12 bytes */
#define act0056 act0055 /* Saved  92 bytes */
#define act0104 act0030 /* Saved 104 bytes */
#define act0108 act0107 /* Saved 100 bytes */
#define act0109 act0107 /* Saved 100 bytes */
#define act0110 act0107 /* Saved 100 bytes */
#define act0111 act0107 /* Saved 100 bytes */
#define act0112 act0107 /* Saved 100 bytes */
#define act0113 act0107 /* Saved 100 bytes */
#define act0122 act0070 /* Saved 104 bytes */
#define act0123 act0107 /* Saved 100 bytes */
#define act0124 act0107 /* Saved 100 bytes */
#define act0125 act0107 /* Saved 100 bytes */
#define act0126 act0107 /* Saved 100 bytes */
#define act0127 act0107 /* Saved 100 bytes */
#define act0130 act0014 /* Saved  12 bytes */
#define act0138 act0107 /* Saved 100 bytes */
#define act0181 act0107 /* Saved 100 bytes */
#define act0183 act0107 /* Saved 100 bytes */
#define act0200 act0102 /* Saved 108 bytes */
#define act0201 act0102 /* Saved 108 bytes */
#define act0205 act0153 /* Saved 112 bytes */
#define act0206 act0107 /* Saved 100 bytes */
#define act0207 act0107 /* Saved 100 bytes */
#define act0210 act0107 /* Saved 100 bytes */
#define act0218 act0014 /* Saved  12 bytes */
#define act0219 act0107 /* Saved 100 bytes */
#define act0223 act0158 /* Saved  12 bytes */
#define act0225 act0189 /* Saved  52 bytes */
#define act0226 act0107 /* Saved 100 bytes */
#define act0227 act0107 /* Saved 100 bytes */
#define act0228 act0107 /* Saved 100 bytes */
#define act0229 act0107 /* Saved 100 bytes */
#define act0230 act0107 /* Saved 100 bytes */
#define act0248 act0014 /* Saved  12 bytes */
#define act0252 act0101 /* Saved  24 bytes */
#define act0259 act0107 /* Saved 100 bytes */
#define act0261 act0107 /* Saved 100 bytes */
#define act0262 act0070 /* Saved 104 bytes */
#define act0269 act0158 /* Saved  12 bytes */
#define act0289 act0142 /* Saved 104 bytes */
#define act0292 act0107 /* Saved 100 bytes */
#define act0294 act0070 /* Saved 104 bytes */
#define act0308 act0107 /* Saved 100 bytes */
#define act0309 act0107 /* Saved 100 bytes */
#define act0310 act0107 /* Saved 100 bytes */
#define act0311 act0107 /* Saved 100 bytes */
#define act0312 act0107 /* Saved 100 bytes */
#define act0323 act0195 /* Saved  36 bytes */
#define act0325 act0107 /* Saved 100 bytes */
#define act0329 act0102 /* Saved 108 bytes */
#define act0330 act0107 /* Saved 100 bytes */
#define act0331 act0158 /* Saved  12 bytes */
#define act0353 act0101 /* Saved  24 bytes */
#define act0366 act0107 /* Saved 100 bytes */
#define act0374 act0107 /* Saved 100 bytes */
#define act0375 act0102 /* Saved 108 bytes */
#define act0387 act0107 /* Saved 100 bytes */
#define act0391 act0107 /* Saved 100 bytes */
#define act0397 act0107 /* Saved 100 bytes */

static const void *action[400] = {
   act0000,act0001,act0002,act0003,act0004,act0005,act0006,act0007,act0008,act0009
  ,act0010,act0011,act0012,act0013,act0014,act0015,act0016,act0017,act0018,act0019
  ,act0020,act0021,act0022,act0023,act0024,act0025,act0026,act0027,act0028,act0029
  ,act0030,act0031,act0032,act0033,act0034,act0035,act0036,act0037,act0038,act0039
  ,act0040,act0041,act0042,act0043,act0044,act0045,act0046,act0047,act0048,act0049
  ,act0050,act0051,act0052,act0053,act0054,act0055,act0056,act0057,act0058,act0059
  ,act0060,act0061,act0062,act0063,act0064,act0065,act0066,act0067,act0068,act0069
  ,act0070,act0071,act0072,act0073,act0074,act0075,act0076,act0077,act0078,act0079
  ,act0080,act0081,act0082,act0083,act0084,act0085,act0086,act0087,act0088,act0089
  ,act0090,act0091,act0092,act0093,act0094,act0095,act0096,act0097,act0098,act0099
  ,act0100,act0101,act0102,act0103,act0104,act0105,act0106,act0107,act0108,act0109
  ,act0110,act0111,act0112,act0113,act0114,act0115,act0116,act0117,act0118,act0119
  ,act0120,act0121,act0122,act0123,act0124,act0125,act0126,act0127,act0128,act0129
  ,act0130,act0131,act0132,act0133,act0134,act0135,act0136,act0137,act0138,act0139
  ,act0140,act0141,act0142,act0143,act0144,act0145,act0146,act0147,act0148,act0149
  ,act0150,act0151,act0152,act0153,act0154,act0155,act0156,act0157,act0158,act0159
  ,act0160,act0161,act0162,act0163,act0164,act0165,act0166,act0167,act0168,act0169
  ,act0170,act0171,act0172,act0173,act0174,act0175,act0176,act0177,act0178,act0179
  ,act0180,act0181,act0182,act0183,act0184,act0185,act0186,act0187,act0188,act0189
  ,act0190,act0191,act0192,act0193,act0194,act0195,act0196,act0197,act0198,act0199
  ,act0200,act0201,act0202,act0203,act0204,act0205,act0206,act0207,act0208,act0209
  ,act0210,act0211,act0212,act0213,act0214,act0215,act0216,act0217,act0218,act0219
  ,act0220,act0221,act0222,act0223,act0224,act0225,act0226,act0227,act0228,act0229
  ,act0230,act0231,act0232,act0233,act0234,act0235,act0236,act0237,act0238,act0239
  ,act0240,act0241,act0242,act0243,act0244,act0245,act0246,act0247,act0248,act0249
  ,act0250,act0251,act0252,act0253,act0254,act0255,act0256,act0257,act0258,act0259
  ,act0260,act0261,act0262,act0263,act0264,act0265,act0266,act0267,act0268,act0269
  ,act0270,act0271,act0272,act0273,act0274,act0275,act0276,act0277,act0278,act0279
  ,act0280,act0281,act0282,act0283,act0284,act0285,act0286,act0287,act0288,act0289
  ,act0290,act0291,act0292,act0293,act0294,act0295,act0296,act0297,act0298,act0299
  ,act0300,act0301,act0302,act0303,act0304,act0305,act0306,act0307,act0308,act0309
  ,act0310,act0311,act0312,act0313,act0314,act0315,act0316,act0317,act0318,act0319
  ,act0320,act0321,act0322,act0323,act0324,act0325,act0326,act0327,act0328,act0329
  ,act0330,act0331,act0332,act0333,act0334,act0335,act0336,act0337,act0338,act0339
  ,act0340,act0341,act0342,act0343,act0344,act0345,act0346,act0347,act0348,act0349
  ,act0350,act0351,act0352,act0353,act0354,act0355,act0356,act0357,act0358,act0359
  ,act0360,act0361,act0362,act0363,act0364,act0365,act0366,act0367,act0368,act0369
  ,act0370,act0371,act0372,act0373,act0374,act0375,act0376,act0377,act0378,act0379
  ,act0380,act0381,act0382,act0383,act0384,act0385,act0386,act0387,act0388,act0389
  ,act0390,act0391,act0392,act0393,act0394,act0395,act0396,act0397,act0398,act0399
}; // Size of table:3200 bytes.

/****************************************************************************\
* The successor matrix is used when the parser has reduced by prod A -> alfa *
* Used by LRParser to find newstate = successor(state,A).                    *
*                                                                            *
*                  succ0007[] = { 3, 5,3 , 6,2, 8,5 };                       *
*   Current state-------+         |  | |                                     *
*   Number of pairs in list ------+  | |                                     *
*   NonTerminal A--------------------+ |                                     *
*   Go to this state-------------------+                                     *
\****************************************************************************/
static const TableType succ0000[] = { 11, 106,   1, 107,   2, 108,   3, 109,   4, 110,   5
                                        , 111,   6, 112,   7, 113,   8, 114,   9, 115,  10
                                        , 126,  15};
static const TableType succ0011[] = {  1, 116,  25};
static const TableType succ0014[] = {  2, 110,  29, 126,  15};
static const TableType succ0016[] = {  1, 127,  30};
static const TableType succ0017[] = {  1, 116,  33};
static const TableType succ0018[] = {  1, 116,  34};
static const TableType succ0019[] = {  1, 166,  36};
static const TableType succ0021[] = { 11, 106,  40, 107,   2, 108,   3, 109,   4, 110,   5
                                        , 111,   6, 112,   7, 113,   8, 114,   9, 115,  10
                                        , 126,  15};
static const TableType succ0022[] = {  1, 125,  41};
static const TableType succ0023[] = {  2, 110,  43, 126,  15};
static const TableType succ0024[] = {  2, 110,  44, 126,  15};
static const TableType succ0027[] = {  1, 116,  46};
static const TableType succ0028[] = {  1, 116,  47};
static const TableType succ0030[] = { 15, 116,  52, 120,  53, 128,  49, 135,  50, 137,  62
                                        , 138,  54, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0035[] = {  1, 116,  90};
static const TableType succ0038[] = {  1, 116,  92};
static const TableType succ0039[] = {  1, 116,  93};
static const TableType succ0041[] = {  2, 110,  94, 126,  15};
static const TableType succ0045[] = {  3, 116,  97, 117,  95, 119,  96};
static const TableType succ0046[] = {  2, 110, 100, 126,  15};
static const TableType succ0047[] = {  1, 118, 101};
static const TableType succ0049[] = {  1, 129, 103};
static const TableType succ0054[] = {  2, 138, 115, 139, 114};
static const TableType succ0055[] = { 12, 116, 118, 137,  62, 138,  54, 153, 117, 154,  58
                                        , 155,  59, 156,  60, 157,  61, 158,  63, 159,  64
                                        , 160,  65, 163,  77};
static const TableType succ0056[] = { 12, 116, 118, 137,  62, 138,  54, 153, 119, 154,  58
                                        , 155,  59, 156,  60, 157,  61, 158,  63, 159,  64
                                        , 160,  65, 163,  77};
static const TableType succ0070[] = { 15, 110, 121, 116, 118, 120, 120, 126,  15, 137,  62
                                        , 138,  54, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0089[] = {  3, 136, 131, 137, 132, 138,  54};
static const TableType succ0091[] = {  1, 116, 135};
static const TableType succ0095[] = {  1, 118, 136};
static const TableType succ0098[] = {  4, 110, 140, 116, 141, 121, 139, 126,  15};
static const TableType succ0101[] = {  2, 123, 143, 146, 145};
static const TableType succ0102[] = { 18, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 142, 149, 148, 151, 149, 152, 150, 154, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0104[] = { 14, 116,  52, 120,  53, 135, 159, 137,  62, 138,  54
                                        , 153,  57, 154,  58, 155,  59, 156,  60, 157,  61
                                        , 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0105[] = {  3, 136, 160, 137, 132, 138,  54};
static const TableType succ0106[] = {  1, 116, 162};
static const TableType succ0107[] = { 13, 116, 118, 120, 163, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0108[] = { 13, 116, 118, 120, 164, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0109[] = { 13, 116, 118, 120, 165, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0110[] = { 13, 116, 118, 120, 166, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0111[] = { 13, 116, 118, 120, 167, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0112[] = { 13, 116, 118, 120, 168, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0113[] = { 13, 116, 118, 120, 169, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0116[] = {  1, 138, 170};
static const TableType succ0122[] = { 15, 110, 174, 116, 118, 120, 120, 126,  15, 137,  62
                                        , 138,  54, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0123[] = { 13, 116, 118, 120, 175, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0124[] = { 13, 116, 118, 120, 176, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0125[] = { 13, 116, 118, 120, 177, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0126[] = { 13, 116, 118, 120, 178, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0127[] = { 13, 116, 118, 120, 179, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0128[] = {  2, 127, 181, 162, 180};
static const TableType succ0129[] = {  1, 127, 183};
static const TableType succ0130[] = {  2, 110, 184, 126,  15};
static const TableType succ0133[] = {  1, 116, 186};
static const TableType succ0134[] = {  3, 116, 189, 164, 187, 168, 188};
static const TableType succ0137[] = {  2, 116,  97, 119, 191};
static const TableType succ0138[] = { 13, 116, 118, 120, 192, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0142[] = { 15, 116, 118, 120, 157, 122, 196, 124, 197, 137,  62
                                        , 138,  54, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0144[] = {  1, 146, 198};
static const TableType succ0150[] = { 17, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 148, 202, 149, 152, 150, 154, 153,  57, 154,  58
                                        , 155,  59, 156,  60, 157,  61, 158,  63, 159,  64
                                        , 160,  65, 163,  77};
static const TableType succ0153[] = { 20, 110, 121, 116, 118, 120, 204, 124, 156, 126,  15
                                        , 137,  62, 138,  54, 142, 203, 148, 151, 149, 152
                                        , 150, 154, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0154[] = {  1, 151, 206};
static const TableType succ0158[] = {  3, 116, 222, 130, 220, 140, 221};
static const TableType succ0181[] = { 13, 116, 118, 120, 232, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0183[] = { 13, 116, 118, 120, 233, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0185[] = {  2, 137, 234, 138,  54};
static const TableType succ0189[] = {  2, 161, 236, 171, 237};
static const TableType succ0190[] = {  1, 116, 246};
static const TableType succ0193[] = {  2, 110, 249, 126,  15};
static const TableType succ0194[] = {  1, 116, 250};
static const TableType succ0195[] = {  2, 123, 251, 146, 145};
static const TableType succ0200[] = { 18, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 142, 254, 148, 151, 149, 152, 150, 154, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0201[] = { 18, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 142, 255, 148, 151, 149, 152, 150, 154, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0205[] = { 20, 110, 174, 116, 118, 120, 204, 124, 156, 126,  15
                                        , 137,  62, 138,  54, 142, 203, 148, 151, 149, 152
                                        , 150, 154, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0206[] = { 15, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 150, 257, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0207[] = { 15, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 150, 258, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0210[] = { 13, 116, 118, 120, 263, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0218[] = {  2, 110, 266, 126,  15};
static const TableType succ0219[] = { 13, 116, 118, 120, 267, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0220[] = {  1, 118, 268};
static const TableType succ0222[] = {  1, 116, 270};
static const TableType succ0223[] = {  2, 116, 222, 140, 271};
static const TableType succ0225[] = {  2, 161, 272, 171, 237};
static const TableType succ0226[] = { 13, 116, 118, 120, 273, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0227[] = { 13, 116, 118, 120, 274, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0228[] = { 13, 116, 118, 120, 275, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0229[] = { 13, 116, 118, 120, 276, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0230[] = { 13, 116, 118, 120, 277, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0235[] = {  2, 116, 189, 168, 280};
static const TableType succ0236[] = {  1, 169, 281};
static const TableType succ0248[] = {  2, 110, 290, 126,  15};
static const TableType succ0252[] = {  2, 123, 291, 146, 145};
static const TableType succ0259[] = { 15, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 150, 293, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0261[] = { 13, 116, 118, 120, 295, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0262[] = { 17, 110, 297, 116, 118, 120, 157, 124, 298, 126,  15
                                        , 137,  62, 138,  54, 152, 296, 153,  57, 154,  58
                                        , 155,  59, 156,  60, 157,  61, 158,  63, 159,  64
                                        , 160,  65, 163,  77};
static const TableType succ0268[] = {  1, 131, 301};
static const TableType succ0269[] = {  2, 116, 222, 140, 303};
static const TableType succ0271[] = {  1, 141, 304};
static const TableType succ0281[] = {  1, 170, 314};
static const TableType succ0287[] = {  1, 154, 318};
static const TableType succ0288[] = {  3, 116, 321, 165, 319, 167, 320};
static const TableType succ0289[] = { 15, 116, 118, 120, 157, 122, 322, 124, 197, 137,  62
                                        , 138,  54, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0292[] = { 15, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 150, 324, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0294[] = { 17, 110, 297, 116, 118, 120, 157, 124, 298, 126,  15
                                        , 137,  62, 138,  54, 152, 326, 153,  57, 154,  58
                                        , 155,  59, 156,  60, 157,  61, 158,  63, 159,  64
                                        , 160,  65, 163,  77};
static const TableType succ0301[] = {  1, 132, 328};
static const TableType succ0308[] = { 13, 116, 118, 120, 332, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0309[] = { 13, 116, 118, 120, 333, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0310[] = { 13, 116, 118, 120, 334, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0311[] = { 13, 116, 118, 120, 335, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0312[] = { 13, 116, 118, 120, 336, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0315[] = {  6, 154, 340, 155, 343, 156, 344, 157, 345, 160, 339
                                        , 172, 338};
static const TableType succ0317[] = {  1, 154, 346};
static const TableType succ0321[] = {  1, 145, 350};
static const TableType succ0323[] = {  2, 123, 354, 146, 145};
static const TableType succ0325[] = { 15, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 150, 355, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0328[] = {  1, 133, 357};
static const TableType succ0329[] = { 18, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 142, 359, 148, 151, 149, 152, 150, 154, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0330[] = { 14, 116, 118, 120, 157, 124, 360, 137,  62, 138,  54
                                        , 153,  57, 154,  58, 155,  59, 156,  60, 157,  61
                                        , 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0331[] = {  2, 116, 222, 140, 361};
static const TableType succ0337[] = {  3, 116, 321, 165, 367, 167, 320};
static const TableType succ0341[] = {  1, 154, 368};
static const TableType succ0342[] = {  1, 154, 369};
static const TableType succ0349[] = {  2, 116, 321, 167, 371};
static const TableType succ0353[] = {  2, 123, 372, 146, 145};
static const TableType succ0357[] = {  2, 123, 373, 146, 145};
static const TableType succ0366[] = { 13, 116, 118, 120, 376, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0373[] = {  2, 134, 378, 147, 380};
static const TableType succ0374[] = { 15, 116, 118, 120, 385, 137,  62, 138,  54, 143, 383
                                        , 144, 384, 153,  57, 154,  58, 155,  59, 156,  60
                                        , 157,  61, 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0375[] = { 18, 116, 118, 120, 157, 124, 156, 137,  62, 138,  54
                                        , 142, 386, 148, 151, 149, 152, 150, 154, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0379[] = {  1, 147, 389};
static const TableType succ0385[] = {  1, 145, 392};
static const TableType succ0387[] = { 13, 116, 118, 120, 394, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};
static const TableType succ0391[] = { 14, 116, 118, 120, 385, 137,  62, 138,  54, 144, 396
                                        , 153,  57, 154,  58, 155,  59, 156,  60, 157,  61
                                        , 158,  63, 159,  64, 160,  65, 163,  77};
static const TableType succ0397[] = { 13, 116, 118, 120, 398, 137,  62, 138,  54, 153,  57
                                        , 154,  58, 155,  59, 156,  60, 157,  61, 158,  63
                                        , 159,  64, 160,  65, 163,  77};

// Total size of all succNNNN tables:4372 bytes.

#define succ0171 succ0106  /* Saved   8 bytes */

static const TableType *successor[400] = {
   succ0000,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    
  ,NULL    ,succ0011,NULL    ,NULL    ,succ0014,NULL    ,succ0016,succ0017,succ0018,succ0019
  ,NULL    ,succ0021,succ0022,succ0023,succ0024,NULL    ,NULL    ,succ0027,succ0028,NULL    
  ,succ0030,NULL    ,NULL    ,NULL    ,NULL    ,succ0035,NULL    ,NULL    ,succ0038,succ0039
  ,NULL    ,succ0041,NULL    ,NULL    ,NULL    ,succ0045,succ0046,succ0047,NULL    ,succ0049
  ,NULL    ,NULL    ,NULL    ,NULL    ,succ0054,succ0055,succ0056,NULL    ,NULL    ,NULL    
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    
  ,succ0070,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0089
  ,NULL    ,succ0091,NULL    ,NULL    ,NULL    ,succ0095,NULL    ,NULL    ,succ0098,NULL    
  ,NULL    ,succ0101,succ0102,NULL    ,succ0104,succ0105,succ0106,succ0107,succ0108,succ0109
  ,succ0110,succ0111,succ0112,succ0113,NULL    ,NULL    ,succ0116,NULL    ,NULL    ,NULL    
  ,NULL    ,NULL    ,succ0122,succ0123,succ0124,succ0125,succ0126,succ0127,succ0128,succ0129
  ,succ0130,NULL    ,NULL    ,succ0133,succ0134,NULL    ,NULL    ,succ0137,succ0138,NULL    
  ,NULL    ,NULL    ,succ0142,NULL    ,succ0144,NULL    ,NULL    ,NULL    ,NULL    ,NULL    
  ,succ0150,NULL    ,NULL    ,succ0153,succ0154,NULL    ,NULL    ,NULL    ,succ0158,NULL    
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    
  ,NULL    ,succ0171,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    
  ,NULL    ,succ0181,NULL    ,succ0183,NULL    ,succ0185,NULL    ,NULL    ,NULL    ,succ0189
  ,succ0190,NULL    ,NULL    ,succ0193,succ0194,succ0195,NULL    ,NULL    ,NULL    ,NULL    
  ,succ0200,succ0201,NULL    ,NULL    ,NULL    ,succ0205,succ0206,succ0207,NULL    ,NULL    
  ,succ0210,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0218,succ0219
  ,succ0220,NULL    ,succ0222,succ0223,NULL    ,succ0225,succ0226,succ0227,succ0228,succ0229
  ,succ0230,NULL    ,NULL    ,NULL    ,NULL    ,succ0235,succ0236,NULL    ,NULL    ,NULL    
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0248,NULL    
  ,NULL    ,NULL    ,succ0252,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0259
  ,NULL    ,succ0261,succ0262,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0268,succ0269
  ,NULL    ,succ0271,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    
  ,NULL    ,succ0281,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0287,succ0288,succ0289
  ,NULL    ,NULL    ,succ0292,NULL    ,succ0294,NULL    ,NULL    ,NULL    ,NULL    ,NULL    
  ,NULL    ,succ0301,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0308,succ0309
  ,succ0310,succ0311,succ0312,NULL    ,NULL    ,succ0315,NULL    ,succ0317,NULL    ,NULL    
  ,NULL    ,succ0321,NULL    ,succ0323,NULL    ,succ0325,NULL    ,NULL    ,succ0328,succ0329
  ,succ0330,succ0331,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0337,NULL    ,NULL    
  ,NULL    ,succ0341,succ0342,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0349
  ,NULL    ,NULL    ,NULL    ,succ0353,NULL    ,NULL    ,NULL    ,succ0357,NULL    ,NULL    
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0366,NULL    ,NULL    ,NULL    
  ,NULL    ,NULL    ,NULL    ,succ0373,succ0374,succ0375,NULL    ,NULL    ,NULL    ,succ0379
  ,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0385,NULL    ,succ0387,NULL    ,NULL    
  ,NULL    ,succ0391,NULL    ,NULL    ,NULL    ,NULL    ,NULL    ,succ0397,NULL    ,NULL    
}; // Size of pointertable:3200 bytes.

/****************************************************************************\
* The productionLength[] array is indexed by production number and holds     *
* the number of symbols on the right side of each production.                *
\****************************************************************************/
static const unsigned char productionLength[197] = {
  /*   0 */    1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
  /*  10 */    5,   3,   1,   3,  11,   8,  10,   7,   7,   4,
  /*  20 */    1,   3,   0,   1,   5,   4,   3,   3,   3,   1,
  /*  30 */   12,   0,   1,   0,   1,   1,   3,   1,   1,   3,
  /*  40 */    1,   0,   2,   3,   1,   2,   0,   1,   2,   3,
  /*  50 */    1,   1,   2,   8,   0,   1,   1,   0,   2,   0,
  /*  60 */    2,   0,   3,   0,   3,   3,   1,   2,   0,   1,
  /*  70 */    1,   0,   3,   2,   1,   1,   1,   0,   3,   2,
  /*  80 */    1,   1,   3,   3,   2,   1,   1,   3,   3,   4,
  /*  90 */    5,   6,   5,   6,   3,   4,   3,   4,   1,   1,
  /* 100 */    1,   1,   1,   1,   1,   1,   1,   3,   1,   3,
  /* 110 */    3,   3,   3,   3,   3,   3,   2,   2,   1,   1,
  /* 120 */    1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
  /* 130 */    1,   3,   6,   3,   8,   8,   8,   8,  14,   4,
  /* 140 */    5,   1,   1,   1,   2,   1,   1,   3,   5,   4,
  /* 150 */    5,  12,   9,   0,   1,   3,   1,   2,   3,   1,
  /* 160 */    4,   2,   5,   2,   2,   2,   1,   1,   1,   1,
  /* 170 */    1,   4,   0,   1,   1,   0,   2,   0,   2,   1,
  /* 180 */    1,   2,   2,   1,   1,   1,   3,   3,   2,   1,
  /* 190 */    1,   1,   1,   1,   1,   1,   1
}; // Size of table:200 bytes.

/****************************************************************************\
* The leftSide[] array is indexed by production number, and holds the        *
* nonTerminal symbol on the left side of each production.                    *
\****************************************************************************/
static const TableType leftSide[197] = {
  /*   0 */  105, 106, 106, 106, 106, 106, 106, 106, 106, 106,
  /*  10 */  107, 117, 117, 119, 108, 108, 108, 108, 108, 108,
  /*  20 */  121, 121, 122, 122, 109, 110, 110, 110, 110, 110,
  /*  30 */  126, 125, 125, 127, 127, 127, 128, 128, 135, 135,
  /*  40 */  135, 129, 129, 136, 136, 137, 139, 139, 139, 130,
  /*  50 */  130, 140, 140, 140, 141, 141, 141, 118, 118, 132,
  /*  60 */  132, 131, 131, 133, 133, 143, 143, 144, 145, 145,
  /*  70 */  145, 123, 123, 123, 146, 146, 146, 134, 134, 134,
  /*  80 */  147, 147, 142, 142, 142, 142, 148, 148, 149, 149,
  /*  90 */  149, 149, 149, 149, 149, 149, 149, 149, 152, 152,
  /* 100 */  150, 151, 151, 151, 151, 151, 151, 124, 124, 120,
  /* 110 */  120, 120, 120, 120, 120, 120, 120, 120, 120, 153,
  /* 120 */  153, 153, 153, 153, 153, 153, 153, 153, 153, 153,
  /* 130 */  153, 153, 153, 153, 153, 153, 153, 153, 153, 153,
  /* 140 */  153, 163, 163, 163, 162, 162, 158, 158, 111, 112,
  /* 150 */  113, 113, 113, 166, 166, 165, 165, 167, 164, 164,
  /* 160 */  168, 161, 161, 161, 161, 161, 161, 161, 161, 161,
  /* 170 */  161, 161, 171, 171, 171, 169, 169, 170, 170, 172,
  /* 180 */  172, 172, 172, 172, 172, 172, 114, 114, 115, 116,
  /* 190 */  138, 159, 154, 160, 155, 156, 157
}; // Size of table:396 bytes.

/****************************************************************************\
* The rightSide[] matrix is indexed by production number and holds           *
* the right side symbols of each production.                                 *
* Compressed and only used for debugging.                                    *
\****************************************************************************/
static const TableType rightSideTable[465] = {
  /*   0 */  106
  /*   1 */ ,107
  /*   2 */ ,108
  /*   3 */ ,109
  /*   4 */ ,110
  /*   5 */ ,111
  /*   6 */ ,112
  /*   7 */ ,113
  /*   8 */ ,114
  /*   9 */ ,115
  /*  10 */ , 68,116, 59,117,118
  /*  11 */ ,117, 84,119
  /*  12 */ ,119
  /*  13 */ ,116, 86,120
  /*  14 */ , 39, 42,116,101,121,102, 69,101,122,102,123
  /*  15 */ , 39, 42,116, 69,101,122,102,123
  /*  16 */ , 39, 42,116,101,121,102,101,110,102,123
  /*  17 */ , 39, 42,116,101,110,102,123
  /*  18 */ , 39, 42,116,101,121,102,110
  /*  19 */ , 39, 42,116,110
  /*  20 */ ,116
  /*  21 */ ,121, 84,116
  /*  23 */ ,124
  /*  24 */ , 25, 34,116,118,123
  /*  25 */ ,110, 81,125,110
  /*  26 */ ,110, 83,110
  /*  27 */ ,110, 82,110
  /*  28 */ ,101,110,102
  /*  29 */ ,126
  /*  30 */ , 58,127,128,129, 34,130,118,131,132,133,123,134
  /*  32 */ ,  9
  /*  34 */ ,  9
  /*  35 */ , 27
  /*  36 */ ,128, 84,135
  /*  37 */ ,135
  /*  38 */ , 96
  /*  39 */ ,116, 85, 96
  /*  40 */ ,120
  /*  42 */ , 42,136
  /*  43 */ ,136, 84,137
  /*  44 */ ,137
  /*  45 */ ,138,139
  /*  47 */ ,138
  /*  48 */ , 40,138
  /*  49 */ ,130, 84,140
  /*  50 */ ,140
  /*  51 */ ,116
  /*  52 */ ,116,116
  /*  53 */ ,101,140,141, 44,140, 54,142,102
  /*  55 */ , 41
  /*  56 */ , 46
  /*  58 */ , 70,142
  /*  60 */ , 36,142
  /*  62 */ , 35, 14,124
  /*  64 */ , 55, 14,143
  /*  65 */ ,143, 84,144
  /*  66 */ ,144
  /*  67 */ ,120,145
  /*  69 */ , 11
  /*  70 */ , 26
  /*  72 */ , 33,146,  8
  /*  73 */ ,146,  8
  /*  74 */ , 13
  /*  75 */ , 62
  /*  76 */ , 57
  /*  78 */ , 37,147, 50
  /*  79 */ ,147, 50
  /*  80 */ , 60
  /*  81 */ , 29
  /*  82 */ ,142, 92,142
  /*  83 */ ,142, 93,142
  /*  84 */ ,100,148
  /*  85 */ ,148
  /*  86 */ ,149
  /*  87 */ ,101,142,102
  /*  88 */ ,150,151,150
  /*  89 */ , 30,101,110,102
  /*  90 */ ,150, 12,150, 93,150
  /*  91 */ ,150,100, 12,150, 93,150
  /*  92 */ ,150, 37,101,152,102
  /*  93 */ ,150,100, 37,101,152,102
  /*  94 */ ,150, 47,120
  /*  95 */ ,150,100, 47,120
  /*  96 */ ,150, 43, 52
  /*  97 */ ,150, 43,100, 52
  /*  98 */ ,110
  /*  99 */ ,124
  /* 100 */ ,124
  /* 101 */ , 88
  /* 102 */ , 89
  /* 103 */ , 90
  /* 104 */ , 91
  /* 105 */ , 86
  /* 106 */ , 87
  /* 107 */ ,124, 84,120
  /* 108 */ ,120
  /* 109 */ ,120, 94,120
  /* 110 */ ,120, 95,120
  /* 111 */ ,120,103,120
  /* 112 */ ,120, 96,120
  /* 113 */ ,120, 97,120
  /* 114 */ ,120, 98,120
  /* 115 */ ,120, 99,120
  /* 116 */ , 95,153
  /* 117 */ , 94,153
  /* 118 */ ,153
  /* 119 */ ,154
  /* 120 */ ,155
  /* 121 */ ,156
  /* 122 */ ,157
  /* 123 */ ,137
  /* 124 */ ,158
  /* 125 */ ,159
  /* 126 */ ,160
  /* 127 */ , 19
  /* 128 */ , 20
  /* 129 */ , 21
  /* 130 */ , 52
  /* 131 */ ,101,120,102
  /* 132 */ , 15,101,120, 10,161,102
  /* 133 */ ,101,110,102
  /* 134 */ , 63,101,120, 34,120, 33,120,102
  /* 135 */ , 63,101,120, 84,120, 84,120,102
  /* 136 */ , 78,101,120, 84,120, 84,120,102
  /* 137 */ , 79,101,120, 84,120, 84,120,102
  /* 138 */ , 80,101,120, 84,120, 84,120, 84,120, 84,120, 84,120,102
  /* 139 */ , 17,101,162,102
  /* 140 */ ,163,101,127,120,102
  /* 141 */ , 49
  /* 142 */ , 48
  /* 143 */ , 64
  /* 144 */ ,127,120
  /* 145 */ , 96
  /* 146 */ ,116
  /* 147 */ ,116, 85,116
  /* 148 */ , 23,116, 22, 33,110
  /* 149 */ , 32,116, 42,136
  /* 150 */ , 18, 65,116, 47,116
  /* 151 */ , 18, 65,116,101,164, 84, 56, 45,101,165,102,102
  /* 152 */ , 18,166, 38,116, 54,116,101,165,102
  /* 154 */ , 66
  /* 155 */ ,165, 84,167
  /* 156 */ ,167
  /* 157 */ ,116,145
  /* 158 */ ,164, 84,168
  /* 159 */ ,168
  /* 160 */ ,116,161,169,170
  /* 161 */ ,171, 71
  /* 162 */ ,171, 71,101,154,102
  /* 163 */ ,171, 77
  /* 164 */ ,171, 75
  /* 165 */ ,171, 76
  /* 166 */ , 74
  /* 167 */ , 73
  /* 168 */ , 78
  /* 169 */ , 79
  /* 170 */ , 80
  /* 171 */ , 72,101,154,102
  /* 173 */ , 61
  /* 174 */ , 67
  /* 176 */ ,100, 52
  /* 178 */ , 24,172
  /* 179 */ ,160
  /* 180 */ ,154
  /* 181 */ , 94,154
  /* 182 */ , 95,154
  /* 183 */ ,155
  /* 184 */ ,156
  /* 185 */ ,157
  /* 186 */ , 28, 65,116
  /* 187 */ , 28, 38,116
  /* 188 */ , 31,106
  /* 189 */ ,104
  /* 190 */ ,  7
  /* 191 */ ,  6
  /* 192 */ ,  2
  /* 193 */ ,  1
  /* 194 */ ,  3
  /* 195 */ ,  4
  /* 196 */ ,  5
}; // Size of table:932 bytes.

/****************************************************************************\
* The symbolName[] array is indexed by symbol and holds                      *
* the name of each symbol (terminal or nonTerminal).                         *
* Used for debugging.                                                        *
\****************************************************************************/
static const TCHAR *symbolName[173] = {
  /*   0 */ _T("EOI"),
  /*   1 */ _T("STRING"),
  /*   2 */ _T("NUMBER"),
  /*   3 */ _T("DATECONST"),
  /*   4 */ _T("TIMECONST"),
  /*   5 */ _T("TIMESTAMPCONST"),
  /*   6 */ _T("PARAM"),
  /*   7 */ _T("HOSTVAR"),
  /*   8 */ _T("ACCESSS"),
  /*   9 */ _T("ALL"),
  /*  10 */ _T("AS"),
  /*  11 */ _T("ASCENDING"),
  /*  12 */ _T("BETWEEN"),
  /*  13 */ _T("BROWSE"),
  /*  14 */ _T("BY"),
  /*  15 */ _T("CAST"),
  /*  16 */ _T("COLUMN"),
  /*  17 */ _T("COUNT"),
  /*  18 */ _T("CREATE"),
  /*  19 */ _T("CURRENTDATE"),
  /*  20 */ _T("CURRENTTIME"),
  /*  21 */ _T("CURRENTTIMESTAMP"),
  /*  22 */ _T("CURSOR"),
  /*  23 */ _T("DECLARE"),
  /*  24 */ _T("DEFAULT"),
  /*  25 */ _T("DELETESYM"),
  /*  26 */ _T("DESCENDING"),
  /*  27 */ _T("DISTINCT"),
  /*  28 */ _T("DROP"),
  /*  29 */ _T("EXCLUSIVE"),
  /*  30 */ _T("EXISTS"),
  /*  31 */ _T("EXPLAIN"),
  /*  32 */ _T("FETCH"),
  /*  33 */ _T("FOR"),
  /*  34 */ _T("FROM"),
  /*  35 */ _T("GROUP"),
  /*  36 */ _T("HAVING"),
  /*  37 */ _T("INSYM"),
  /*  38 */ _T("INDEX"),
  /*  39 */ _T("INSERT"),
  /*  40 */ _T("INDICATOR"),
  /*  41 */ _T("INNER"),
  /*  42 */ _T("INTO"),
  /*  43 */ _T("IS"),
  /*  44 */ _T("JOIN"),
  /*  45 */ _T("KEY"),
  /*  46 */ _T("LEFT"),
  /*  47 */ _T("LIKE"),
  /*  48 */ _T("MAX"),
  /*  49 */ _T("MIN"),
  /*  50 */ _T("MODE"),
  /*  51 */ _T("MULT"),
  /*  52 */ _T("NULLVAL"),
  /*  53 */ _T("ISNULL"),
  /*  54 */ _T("ON"),
  /*  55 */ _T("ORDER"),
  /*  56 */ _T("PRIMARY"),
  /*  57 */ _T("REPEATABLE"),
  /*  58 */ _T("SELECT"),
  /*  59 */ _T("SET"),
  /*  60 */ _T("SHARE"),
  /*  61 */ _T("SIGNED"),
  /*  62 */ _T("STABLE"),
  /*  63 */ _T("SUBSTRING"),
  /*  64 */ _T("SUM"),
  /*  65 */ _T("TABLE"),
  /*  66 */ _T("UNIQUE"),
  /*  67 */ _T("UNSIGNED"),
  /*  68 */ _T("UPDATE"),
  /*  69 */ _T("VALUES"),
  /*  70 */ _T("WHERE"),
  /*  71 */ _T("TYPECHAR"),
  /*  72 */ _T("TYPEVARCHAR"),
  /*  73 */ _T("TYPEDOUBLE"),
  /*  74 */ _T("TYPEFLOAT"),
  /*  75 */ _T("TYPEINT"),
  /*  76 */ _T("TYPELONG"),
  /*  77 */ _T("TYPESHORT"),
  /*  78 */ _T("TYPEDATE"),
  /*  79 */ _T("TYPETIME"),
  /*  80 */ _T("TYPETIMESTAMP"),
  /*  81 */ _T("UNION"),
  /*  82 */ _T("SETDIFFERENCE"),
  /*  83 */ _T("INTERSECT"),
  /*  84 */ _T("COMMA"),
  /*  85 */ _T("DOT"),
  /*  86 */ _T("EQUAL"),
  /*  87 */ _T("NOTEQ"),
  /*  88 */ _T("RELOPLE"),
  /*  89 */ _T("RELOPLT"),
  /*  90 */ _T("RELOPGE"),
  /*  91 */ _T("RELOPGT"),
  /*  92 */ _T("OR"),
  /*  93 */ _T("AND"),
  /*  94 */ _T("PLUS"),
  /*  95 */ _T("MINUS"),
  /*  96 */ _T("STAR"),
  /*  97 */ _T("DIVOP"),
  /*  98 */ _T("MODOP"),
  /*  99 */ _T("EXPO"),
  /* 100 */ _T("NOT"),
  /* 101 */ _T("LPAR"),
  /* 102 */ _T("RPAR"),
  /* 103 */ _T("CONCAT"),
  /* 104 */ _T("NAME"),
  /* 105 */ _T("start"),
  /* 106 */ _T("stmt"),
  /* 107 */ _T("update_stmt"),
  /* 108 */ _T("insert_stmt"),
  /* 109 */ _T("delete_stmt"),
  /* 110 */ _T("select_stmt"),
  /* 111 */ _T("declare_stmt"),
  /* 112 */ _T("fetch_stmt"),
  /* 113 */ _T("create_stmt"),
  /* 114 */ _T("drop_stmt"),
  /* 115 */ _T("explain_stmt"),
  /* 116 */ _T("name"),
  /* 117 */ _T("assign_list"),
  /* 118 */ _T("opt_where"),
  /* 119 */ _T("assign"),
  /* 120 */ _T("expr"),
  /* 121 */ _T("name_list"),
  /* 122 */ _T("opt_expr_list"),
  /* 123 */ _T("opt_access"),
  /* 124 */ _T("expr_list"),
  /* 125 */ _T("opt_all"),
  /* 126 */ _T("simple_select"),
  /* 127 */ _T("opt_alldistinct"),
  /* 128 */ _T("select_list"),
  /* 129 */ _T("opt_into"),
  /* 130 */ _T("from_table_list"),
  /* 131 */ _T("opt_groupby"),
  /* 132 */ _T("opt_having"),
  /* 133 */ _T("opt_orderby"),
  /* 134 */ _T("opt_lockmode"),
  /* 135 */ _T("select_elem"),
  /* 136 */ _T("hostvar_list"),
  /* 137 */ _T("hostindi_var"),
  /* 138 */ _T("hostvar"),
  /* 139 */ _T("opt_indicator"),
  /* 140 */ _T("from_table"),
  /* 141 */ _T("opt_join_type"),
  /* 142 */ _T("search_condition"),
  /* 143 */ _T("order_elem_list"),
  /* 144 */ _T("order_elem"),
  /* 145 */ _T("opt_ascdesc"),
  /* 146 */ _T("access_mode"),
  /* 147 */ _T("lockmode"),
  /* 148 */ _T("boolean_primary"),
  /* 149 */ _T("predicate"),
  /* 150 */ _T("par_expr_list"),
  /* 151 */ _T("rel_op"),
  /* 152 */ _T("set_expr"),
  /* 153 */ _T("unary"),
  /* 154 */ _T("number_const"),
  /* 155 */ _T("date_const"),
  /* 156 */ _T("time_const"),
  /* 157 */ _T("timestamp_const"),
  /* 158 */ _T("tab_col"),
  /* 159 */ _T("param"),
  /* 160 */ _T("string_const"),
  /* 161 */ _T("type_def"),
  /* 162 */ _T("count_arg"),
  /* 163 */ _T("min_max_sum"),
  /* 164 */ _T("col_def_list"),
  /* 165 */ _T("keyfield_list"),
  /* 166 */ _T("opt_unique"),
  /* 167 */ _T("keyfield"),
  /* 168 */ _T("col_def"),
  /* 169 */ _T("opt_not_null"),
  /* 170 */ _T("opt_defaultvalue"),
  /* 171 */ _T("opt_sign"),
  /* 172 */ _T("constant")
}; // Total size of strings:1764 bytes, size of pointertable:1384 bytes.

static const ParserShortTables SqlTables_s(compressedSet, compressedLasets
                                          ,action, successor, productionLength, leftSide
                                          ,rightSideTable, symbolName
                                          ,105, 173, 197, 400);

const ParserTables *SqlTables = &SqlTables_s;
// Size of SqlTables_s: 88 bytes. Size of SqlTables:8 bytes


// Total size of table data:21.908 bytes.

