//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestBin.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDD_TESTFLOAT_DIALOG            129
#define IDD_TIMER_DIALOG                130
#define IDD_TESTINT_DIALOG              131
#define IDC_STATIC_TEXT                 1000
#define IDC_BUTTON_START                1001
#define IDC_BUTTON_STOP                 1002
#define IDC_BUTTON_STEP                 1003
#define IDC_BUTTON_RESET                1004
#define IDC_BUTTON_EDIT                 1005
#define IDC_EDIT_HEX                    1006
#define IDC_EDIT_TIMERINTERVAL          1010
#define IDC_RADIO_TYPEI32               1020
#define IDC_RADIO_TYPEU32               1021
#define IDC_RADIO_TYPEI64               1022
#define IDC_RADIO_TYPEU64               1023
#define IDC_RADIO_TYPEI128              1024
#define IDC_RADIO_TYPEU128              1025
#define IDC_STATIC_EINTLABEL            1030
#define IDC_EDIT_INTVALUE               1031
#define IDC_SPIN_INTVALUE               1032
#define IDC_STATIC_RADIXLABEL           1033
#define IDC_EDIT_RADIXVALUE             1034
#define IDC_SPIN_RADIXVALUE             1035
#define IDC_RADIO_TYPEFLOAT             1050
#define IDC_RADIO_TYPEDOUBLE64          1051
#define IDC_RADIO_TYPEDOUBLE80          1052
#define IDC_CHECK_SIGNBIT               1053
#define IDC_STATIC_EXPOLABEL            1054
#define IDC_EDIT_EXPOVALUE              1055
#define IDC_SPIN_EXPOVALUE              1056
#define IDC_STATIC_SIGLABEL             1057
#define IDC_EDIT_SIGVALUE               1058
#define IDC_SPIN_SIGVALUE               1059
#define IDC_STATIC_EXPO2LABEL           1060
#define IDC_STATIC_EXPO2VALUE           1061
#define IDC_STATIC_ACCBIN               1070
#define IDC_STATIC_ACCLABEL             1071
#define IDC_STATIC_ACCVALUE             1072
#define IDC_STATIC_ACCCLASSLABEL        1073
#define IDC_STATIC_ACCCLASSVALUE        1074
#define IDC_STATIC_MEMLABEL             1075
#define IDC_STATIC_MEMVALUE             1076
#define IDC_STATIC_MEMCLASSLABEL        1077
#define IDC_STATIC_MEMCLASSVALUE        1078
#define IDC_BUTTON_SAVE                 1100
#define IDC_BUTTON_LOAD                 1101
#define IDC_BUTTON_RESETMEM             1102
#define IDC_BUTTON_SWAPACCMEM           1103
#define IDC_BUTTON_ADD                  1110
#define IDC_BUTTON_SUB                  1111
#define IDC_BUTTON_MULT                 1112
#define IDC_BUTTON_DIV                  1113
#define IDC_BUTTON_FMOD                 1114
#define IDC_BUTTON_SQR                  1115
#define IDC_BUTTON_AND                  1120
#define IDC_BUTTON_OR                   1121
#define IDC_BUTTON_XOR                  1122
#define IDC_BUTTON_NOT                  1123
#define IDC_BUTTON_NEG                  1124
#define IDC_BUTTON_RECIPROC             1130
#define IDC_BUTTON_SQRT                 1131
#define IDC_BUTTON_SETZERO              1140
#define IDC_BUTTON_SETONE               1141
#define IDC_BUTTON_SETMIN               1142
#define IDC_BUTTON_SETMAX               1143
#define IDC_BUTTON_SETRND               1144
#define IDC_BUTTON_SETTRUEMIN           1150
#define IDC_BUTTON_SETEPS               1151
#define IDC_BUTTON_SETINF               1152
#define IDC_BUTTON_SETQNAN              1153
#define IDC_BUTTON_SETSNAN              1154
#define IDC_STATIC_OPERANDFRAME         1160
#define IDC_STATIC_STREAMFRAME          1161
#define IDC_STATIC_WIDTHLABEL           1162
#define IDC_EDIT_WIDTHVALUE             1163
#define IDC_SPIN_WIDTHVALUE             1164
#define IDC_STATIC_PRECLABEL            1165
#define IDC_EDIT_PRECVALUE              1166
#define IDC_SPIN_PRECVALUE              1167
#define IDC_CHECK_MAXPREC               1168
#define IDC_STATIC_FILLLABEL            1170
#define IDC_EDIT_FILLVALUE              1171
#define IDC_CHECK_IOS_SKIPWS            1200
#define IDC_CHECK_IOS_UNITBUF           1201
#define IDC_CHECK_IOS_UPPERCASE         1202
#define IDC_CHECK_IOS_SHOWBASE          1203
#define IDC_CHECK_IOS_SHOWPOINT         1204
#define IDC_CHECK_IOS_SHOWPOS           1205
#define IDC_CHECK_IOS_LEFT              1206
#define IDC_CHECK_IOS_RIGHT             1207
#define IDC_CHECK_IOS_INTERNAL          1208
#define IDC_CHECK_IOS_DEC               1209
#define IDC_CHECK_IOS_OCT               1210
#define IDC_CHECK_IOS_HEX               1211
#define IDC_CHECK_IOS_SCIENTIFIC        1212
#define IDC_CHECK_IOS_FIXED             1213
#define IDC_CHECK_IOS_HEXFLOAT          1214
#define IDC_CHECK_IOS_BOOLALPHA         1215
#define IDC_CHECK_IOS_STDIO             1216
#define IDC_CHECK_MANIPSTREAMIN         1230
#define IDC_CHECK_WIDECHARSTREAM        1231
#define IDC_CHECK_AUTOUPDATESTREAMOUT   1232
#define IDC_BUTTON_STREAMIN             1233
#define IDC_BUTTON_STREAMOUT            1234
#define IDC_BUTTON_COPYOUTTOIN          1235
#define IDC_RADIO_OPACC                 1240
#define IDC_RADIO_OPMEM                 1241
#define IDC_COMBO_STREAMINVALUE         1250
#define IDC_EDIT_STREAMINVALUE          1251
#define IDC_EDIT_STREAMOUTVALUE         1252
#define IDC_STATIC_STREAMFLAGSLABEL     1260
#define IDC_STATIC_STREAMFLAGSVALUE     1261
#define IDC_STATIC_STREAMSTATELABEL     1262
#define IDC_STATIC_STREAMSTATEVALUE     1263
#define ID_FILE_EXIT                    32771
#define ID_FILE_TESTFLOATS              32772
#define ID_FILE_TESTINT                 32773
#define ID_VIEW_TIMER                   32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1170
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
