//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestBin.rc
//
#define IDM_ABOUTBOX                     0x0010
#define IDD_ABOUTBOX                     100
#define IDS_ABOUTBOX                     101
#define IDR_MAINFRAME                    128
#define IDD_TESTFLOAT_DIALOG             129
#define IDD_TIMER_DIALOG                 130
#define IDD_TESTINT_DIALOG               131
#define IDC_STATIC_TEXT                  1000
#define IDC_STARTBUTTON                  1001
#define IDC_STOPBUTTON                   1002
#define IDC_STEPBUTTON                   1003
#define IDC_RESETBUTTON                  1004
#define IDC_EDIT_BUTTON                  1005
#define IDC_EDIT_HEX                     1006
#define IDC_EDIT_TIMERINTERVAL           1010
#define IDC_RADIO_TYPEFLOAT              1020
#define IDC_RADIO_TYPEI32                1020
#define IDC_RADIO_TYPEDOUBLE64           1021
#define IDC_RADIO_TYPEU32                1021
#define IDC_RADIO_TYPEDOUBLE80           1022
#define IDC_RADIO_TYPEI64                1022
#define IDC_RADIO_TYPEU64                1023
#define IDC_RADIO_TYPEI128               1024
#define IDC_RADIO_TYPEU128               1025
#define IDC_CHECK_SIGNBIT                1030
#define IDC_STATIC_EXPOLABEL             1031
#define IDC_STATIC_EINTLABEL             1031
#define IDC_EDIT_EXPOVALUE               1032
#define IDC_EDIT_INTVALUE                1032
#define IDC_SPIN_EXPOVALUE               1033
#define IDC_SPIN_INTVALUE                1033
#define IDC_STATIC_SIGLABEL              1034
#define IDC_STATIC_RADIXLABEL            1034
#define IDC_EDIT_SIGVALUE                1035
#define IDC_EDIT_RADIXVALUE              1035
#define IDC_SPIN_SIGVALUE                1036
#define IDC_SPIN_RADIXVALUE              1036
#define IDC_STATIC_EXPO2LABEL            1037
#define IDC_STATIC_EXPO2VALUE            1038
#define IDC_STATIC_ACCBIN                1050
#define IDC_STATIC_ACCLABEL              1051
#define IDC_STATIC_ACCVALUE              1052
#define IDC_STATIC_ACCCLASSLABEL         1053
#define IDC_STATIC_ACCCLASSVALUE         1054
#define IDC_STATIC_MEMLABEL              1055
#define IDC_STATIC_MEMVALUE              1056
#define IDC_STATIC_MEMCLASSLABEL         1057
#define IDC_STATIC_MEMCLASSVALUE         1058
#define IDC_BUTTON_SAVE                  1060
#define IDC_BUTTON_LOAD                  1061
#define IDC_BUTTON_RESETMEM              1062
#define IDC_BUTTON_SWAPACCMEM            1063
#define IDC_BUTTON_ADD                   1070
#define IDC_BUTTON_SUB                   1071
#define IDC_BUTTON_MULT                  1072
#define IDC_BUTTON_DIV                   1073
#define IDC_BUTTON_FMOD                  1074
#define IDC_BUTTON_RECIPROC              1075
#define IDC_BUTTON_AND                   1075
#define IDC_BUTTON_SQR                   1076
#define IDC_BUTTON_SQRT                  1077
#define IDC_BUTTON_OR                    1077
#define IDC_BUTTON_XOR                   1078
#define IDC_BUTTON_NEG                   1079
#define IDC_BUTTON_SETZERO               1080
#define IDC_BUTTON_SETTRUEMIN            1081
#define IDC_BUTTON_NOT                   1081
#define IDC_BUTTON_SETMIN                1082
#define IDC_BUTTON_SETEPS                1083
#define IDC_BUTTON_SETRND                1084
#define IDC_BUTTON_SETONE                1085
#define IDC_BUTTON_SETMAX                1086
#define IDC_BUTTON_SETINF                1087
#define IDC_BUTTON_SETQNAN               1088
#define IDC_BUTTON_SETSNAN               1089
#define IDC_STATIC_STREAMFRAME           1100
#define IDC_STATIC_WIDTHLABEL            1101
#define IDC_EDIT_WIDTHVALUE              1102
#define IDC_SPIN_WIDTHVALUE              1103
#define IDC_STATIC_OPERANDFRAME          1104
#define IDC_STATIC_PRECLABEL             1110
#define IDC_EDIT_PRECVALUE               1111
#define IDC_SPIN_PRECVALUE               1112
#define IDC_CHECK_MAXPREC                1113
#define IDC_CHECK_IOS_SKIPWS             1120
#define IDC_STATIC_FILLLABEL             1121
#define IDC_EDIT_FILLVALUE               1122
#define IDC_CHECK_IOS_UNITBUF            1130
#define IDC_CHECK_IOS_UPPERCASE          1131
#define IDC_CHECK_IOS_SHOWBASE           1132
#define IDC_CHECK_IOS_SHOWPOINT          1133
#define IDC_CHECK_IOS_SHOWPOS            1134
#define IDC_CHECK_IOS_LEFT               1135
#define IDC_CHECK_IOS_RIGHT              1136
#define IDC_CHECK_IOS_INTERNAL           1137
#define IDC_CHECK_IOS_DEC                1138
#define IDC_CHECK_IOS_OCT                1139
#define IDC_CHECK_IOS_HEX                1140
#define IDC_CHECK_IOS_SCIENTIFIC         1141
#define IDC_CHECK_IOS_FIXED              1142
#define IDC_CHECK_IOS_HEXFLOAT           1143
#define IDC_CHECK_IOS_BOOLALPHA          1144
#define IDC_CHECK_IOS_STDIO              1145
#define IDC_CHECK_MANIPSTREAMIN          1150
#define IDC_CHECK_WIDECHARSTREAM         1151
#define IDC_CHECK_AUTOUPDATESTREAMOUT    1152
#define IDC_BUTTON_STREAMIN              1153
#define IDC_BUTTON_STREAMOUT             1154
#define IDC_BUTTON_COPYOUTTOIN           1155
#define IDC_RADIO_OPACC                  1156
#define IDC_RADIO_OPMEM                  1157
#define IDC_COMBO_STREAMINVALUE          1160
#define IDC_EDIT_STREAMINVALUE           1161
#define IDC_EDIT_STREAMOUTVALUE          1162
#define IDC_STATIC_STREAMFLAGSLABEL      1163
#define IDC_STATIC_STREAMFLAGSVALUE      1164
#define IDC_STATIC_STREAMSTATELABEL      1165
#define IDC_STATIC_STREAMSTATEVALUE      1166
#define ID_FILE_EXIT                    32771
#define ID_FILE_TESTFLOATS              32772
#define ID_FILE_TESTINT                 32773
#define ID_VIEW_TIMER                   32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1170
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
