//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Chess.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_MAINFRAME                   101
#define IDD_HISTORY_DIALOG              102
#define IDD_TRACE_DIALOG                103
#define IDD_MESSAGE_DIALOG              104
#define IDD_ENTERTEXT_DIALOG            105
#define IDD_OPENINGLIB_DIALOG           106
#define IDD_SELECTOPENING_DIALOG        107
#define IDD_SELECTDIR_DIALOG            108
#define IDD_TIMESETTINGS_DIALOG         109
#define IDD_CONNECT_DIALOG              111
#define IDD_PIECEVALUE_DIALOG           112
#define IDD_TABLEBASE_DIALOG            113
#define IDD_VIEW_DIALOG                 114
#define IDD_ENGINES_DIALOG              115
#define IDD_ENGINEOPTIONS_DIALOG        116
#define IDD_SELECTINFOFIELDS_DIALOG     117
#define IDR_MAINFRAME                   128
#define IDR_HISTORY_MENU                131
#define IDR_HISTORY_CONTEXTMENU         132
#define IDR_OPENINGLIB_MENU             133
#define IDR_TRACE_MENU                  134
#define IDR_TEST_MENU                   135
#define IDR_HISTORY_ACCELERATOR         140
#define IDR_SELECTDIR_ACCELERATOR       141
#define IDR_OPENING_ACCELERATOR         142
#define IDR_TIMESETTINGS_ACCELERATOR    144
#define IDR_MESSAGE_ACCELERATOR         145
#define IDR_CONNECT_ACCELERATOR         146
#define IDR_TABLEBASE_ACCELERATOR       147
#define IDR_OPENINGLIBRARY              148
#define IDR_BOARD                       150
#define IDB_SELECTIONFRAME              151
#define IDB_BITMAPNOPIECE               152
#define IDB_BITMAPWHITEKING             161
#define IDB_BITMAPWHITEQUEEN            162
#define IDB_BITMAPWHITEROOK             163
#define IDB_BITMAPWHITEBISHOP           164
#define IDB_BITMAPWHITEKNIGHT           165
#define IDB_BITMAPWHITEPAWN             166
#define IDB_BITMAPBLACKKING             171
#define IDB_BITMAPBLACKQUEEN            172
#define IDB_BITMAPBLACKROOK             173
#define IDB_BITMAPBLACKBISHOP           174
#define IDB_BITMAPBLACKKNIGHT           175
#define IDB_BITMAPBLACKPAWN             176
#define IDB_YELLOWFIELD                 180
#define IDB_BLUEFIELD                   181
#define IDB_PURPLEFIELD                 182
#define IDB_PINKFIELD                   183
#define IDB_GREENFIELD                  184
#define IDB_CHECKEDKING                 185
#define IDB_SRCMARK                     186
#define IDB_DSTMARK                     187
#define IDB_HOURGLASS                   188
#define IDB_PLAYERINDICATOR             189
#define IDB_BITMAPWHITEBLACK            210
#define IDR_FOLDERIMAGES                211
#define IDB_BITMAPWHITEMARK             212
#define IDB_BITMAPBLACKMARK             213
#define IDB_BITMAPDELETEMARK            214
#define IDS_KINGNAME                    220
#define IDS_QUEENNAME                   221
#define IDS_ROOKNAME                    222
#define IDS_BISHOPNAME                  223
#define IDS_KNIGHTNAME                  224
#define IDS_PAWNNAME                    225
#define IDS_KINGNAME_PLUR               226
#define IDS_QUEENNAME_PLUR              227
#define IDS_ROOKNAME_PLUR               228
#define IDS_BISHOPNAME_PLUR             229
#define IDS_KNIGHTNAME_PLUR             230
#define IDS_PAWNNAME_PLUR               231
#define IDS_KINGSHORTNAME               232
#define IDS_QUEENSHORTNAME              233
#define IDS_ROOKSHORTNAME               234
#define IDS_BISHOPSHORTNAME             235
#define IDS_KNIGHTSHORTNAME             236
#define IDS_PROMOTED_PAWN               237
#define IDS_PROMOTED_PAWN_PLUR          238
#define IDS_WHITEPLAYERNAME             240
#define IDS_BLACKPLAYERNAME             241
#define IDS_WHITEPLAYERSHORTNAME        242
#define IDS_BLACKPLAYERSHORTNAME        243
#define IDS_BOTH_LABEL                  244
#define IDS_MSG_s_CANNOT_HAVE_TWO_KINGS 260
#define IDS_MSG_CANNOT_ADD_ANOTHER_s_s  261
#define IDS_MSG_s_HAS_NO_KING           262
#define IDS_MSG_KINGS_ATTACK_EACHOTHER  263
#define IDS_MSG_s_KING_IS_IN_CHECK      264
#define IDS_MSG_s_CAN_ONLY_HAVE_8_PAWNS 265
#define IDS_MSG_s_KING_ATTACKED_LEFT_RIGHT_s 266
#define IDS_MSG_s_KING_ATTACKED_LOWER_UPPER_s 267
#define IDS_MSG_s_KING_ATTACKED_LOWER_UPPER_DIAGONAL_s 268
#define IDS_MSG_s_KING_ATTACKED_VERTICAL_HORIZONTAL 269
#define IDS_MSG_s_KING_ATTACKED_BOTH_DIAGONALS_s 270
#define IDS_MSG_s_KING_ATTACKED_BY_d_s_s 271
#define IDS_MSG_s_KING_ATTACKED_BY_d_s_AND_FROM_SIDE_s 272
#define IDS_MSG_s_KING_ATTACKED_BY_d_s_AND_d_s_s 273
#define IDS_MSG_s_KING_ATTACKED_BY_d_s_AND_FROM_ABOVE_s 274
#define IDS_MSG_s_KING_ATTACKED_BY_d_s_UNMOVED_PAWN_s 275
#define IDS_MSG_s_HAVE_d_s_AND_d_s_ON_THE_BOARD_s 276
#define IDS_MSG_0_SECONDS_NOT_ALLOWED   277
#define IDS_MSG_0_MOVES_NOT_ALLOWED     278
#define IDS_MSG_CANNOT_PLACE_A_PAWN_ON_s 279
#define IDS_MSG_COMPUTER_WIN            280
#define IDS_MSG_HUMAN_WIN               281
#define IDS_MSG_s_STALEMATE             282
#define IDS_MSG_INSUFFICIENT_MATERIAL   283
#define IDS_MSG_POSITION_REPEATED_3_TIMES 284
#define IDS_MSG_d_MOVES_RULE            285
#define IDS_MSG_CONFIRM_RESIGN          286
#define IDS_MSG_ASK_PLAYAGAIN           287
#define IDS_MSG_ASK_RESTART_ENGINE      288
#define IDS_IMPOSSIBLE                  289
#define IDS_MSG_WHITE_WIN               290
#define IDS_MSG_BLACK_WIN               291
#define IDS_MSG_EMPTYCOMPUTERNAME       292
#define IDS_MSG_WAIT_FOR_CONNECTION     293
#define IDS_MSG_UNDOREFUSED             294
#define IDS_MSG_COMPUTER_WINONTIME      295
#define IDS_MSG_ONLY_1_MOVE             296
#define IDS_MSG_DEFENDSTRENGTH_0_100    297
#define IDS_MSG_d_ILLEGALINTVALUE_d_d   298
#define IDS_MSG_s_NOTNUMERIC            299
#define IDS_DELETED                     300
#define IDS_TIMEDGAME                   310
#define IDS_LEVELS                      311
#define IDS_SPEEDCHESS                  312
#define IDS_ABOUTBOX                    313
#define IDS_GAMENAME                    314
#define IDS_UNNAMED                     315
#define IDS_AFTERMOVE                   316
#define IDS_EDITMODETEXT                317
#define IDS_DEBUGMODETEXT               318
#define IDS_AUTOPLAYMODETEXT            319
#define IDS_ANALYZEMODETEXT             320
#define IDS_ERRORLABEL                  330
#define IDS_WARNING                     331
#define IDS_CANCELLABEL                 332
#define IDS_CANCELQUESTION              333
#define IDS_DRAW                        340
#define IDS_TERMINALDRAW                341
#define IDS_STALEMATE                   342
#define IDS_CHECKMATE                   343
#define IDS_BLACKCHECKMATE              344
#define IDS_WHITECHECKMATE              345
#define IDS_RESIGN                      346
#define IDS_WININPLIES                  347
#define IDS_LOOSEINPLIES                348
#define IDS_SELECTEXEFILETITLE          350
#define IDS_LOADGAMETITLE               351
#define IDS_EXEFILEEXTENSION            352
#define IDS_ALLFILESEXTENSION           353
#define IDS_CHESSFILEEXTENSION          354
#define IDS_TEXTFILEEXTENSION           355
#define IDS_ENDSEARCH                   360
#define IDS_ENDDEBUG                    361
#define IDS_ENDAUTOPLAY                 362
#define IDS_STARTCLOCK                  363
#define IDS_STOPCLOCK                   364
#define IDS_STOPWHITEEXTERNENGINE       370
#define IDS_STARTWHITEEXTERNENGINE      371
#define IDS_STOPBLACKEXTERNENGINE       372
#define IDS_STARTBLACKEXTERNENGINE      373
#define IDS_MOVEBACKWARD                380
#define IDS_MOVEFORWARD                 381
#define IDS_MOVETOSTART                 382
#define IDS_OPENINGS                    390
#define IDS_RESTART                     391
#define IDS_RESTARTQUESTION             392
#define IDS_DECOMPRESSALLTITLE          393
#define IDS_ALLTABLEBASESDECOMPRESSED   395
#define IDS_METRIC                      396
#define IDS_TIMEPARAMETERSDIFFER        400
#define IDS_NOHINT                      401
#define IDS_TIME                        404
#define IDS_PATH                        411
#define IDS_AUTHOR                      412
#define IDS_NAME                        413
#define IDS_PLY                         414
#define IDS_PLIES                       415
#define IDS_MOVE                        416
#define IDS_MOVES                       417
#define IDC_ICON_CHESS                  1001
#define IDC_DUMMYBUTTON                 1002
#define IDC_STATIC_TEXT                 1003
#define IDC_BUTTON_HIDE                 1010
#define IDC_BUTTON_CLEAR                1011
#define IDC_CHECK_KEEPTEXT              1012
#define IDC_STATIC_PV                   1013
#define IDC_EDIT_HISTORY                1020
#define IDC_SCROLLBAR_HISTORY           1021
#define IDC_TREE_OPENING                1030
#define IDC_LIST_NAMES                  1031
#define IDC_BUTTON_EXPAND               1032
#define IDC_BUTTON_EXPANDALL            1033
#define IDC_EDIT_TEXTBOX                1040
#define IDC_TAB_CLOCKTYPE               1050
#define IDC_STATIC_LEVEL1LABEL          1051
#define IDC_STATIC_LEVEL2LABEL          1052
#define IDC_STATIC_LEVEL3LABEL          1053
#define IDC_STATIC_LEVEL4LABEL          1054
#define IDC_STATIC_LEVEL5LABEL          1055
#define IDC_STATIC_LEVEL6LABEL          1056
#define IDC_STATIC_LEVEL1COLON          1057
#define IDC_STATIC_LEVEL2COLON          1058
#define IDC_STATIC_LEVEL3COLON          1059
#define IDC_STATIC_LEVEL4COLON          1060
#define IDC_STATIC_LEVEL5COLON          1061
#define IDC_STATIC_LEVEL6COLON          1062
#define IDC_EDIT_TIMEOUTMINUTES1        1063
#define IDC_EDIT_TIMEOUTSECONDS1        1064
#define IDC_EDIT_TIMEOUTMINUTES2        1065
#define IDC_EDIT_TIMEOUTSECONDS2        1066
#define IDC_EDIT_TIMEOUTMINUTES3        1067
#define IDC_EDIT_TIMEOUTSECONDS3        1068
#define IDC_EDIT_TIMEOUTMINUTES4        1069
#define IDC_EDIT_TIMEOUTSECONDS4        1070
#define IDC_EDIT_TIMEOUTMINUTES5        1071
#define IDC_EDIT_TIMEOUTSECONDS5        1072
#define IDC_EDIT_TIMEOUTMINUTES6        1073
#define IDC_EDIT_TIMEOUTSECONDS6        1074
#define IDC_STATIC_MINUTES              1080
#define IDC_STATIC_SECONDS              1081
#define IDC_STATIC_TIMEPERMOVE          1082
#define IDC_STATIC_PLAYER               1083
#define IDC_STATIC_LEVEL                1084
#define IDC_STATIC_MOVECOUNT            1085
#define IDC_STATIC_TIME                 1086
#define IDC_STATIC_TIMEINCR             1087
#define IDC_STATIC_SECONDS_LC           1088
#define IDC_STATIC_COLON1               1089
#define IDC_STATIC_COLON2               1090
#define IDC_COMBO_PLAYER                1091
#define IDC_COMBO_SPEEDPLAYER           1092
#define IDC_EDIT_MOVECOUNT              1093
#define IDC_EDIT_HOURSLEFT              1094
#define IDC_EDIT_MINUTESLEFT            1095
#define IDC_EDIT_SECONDSLEFT            1096
#define IDC_EDIT_SECONDSINCR            1097
#define IDC_EDIT_SPEEDCHESSHOURSLEFT    1098
#define IDC_EDIT_SPEEDCHESSMINUTESLEFT  1099
#define IDC_EDIT_SPEEDCHESSSECONDSINCR  1101
#define IDC_CHECK_RESETCLOCKS           1102
#define IDC_EDIT_SPEEDCHESSSECONDSLEFT  1110
#define IDC_TREE_DIR                    1110
#define IDC_COMBO_DRIVE                 1111
#define IDC_EDIT_DIR                    1112
#define IDC_STATIC_DRIVE                1113
#define IDC_STATIC_FOLDER               1114
#define IDC_STATIC_COPYRIGHT            1120
#define IDC_STATIC_INFO                 1121
#define IDC_RADIO_CREATEGAME            1130
#define IDC_RADIO_CONNECTTOGAME         1131
#define IDC_EDIT_COMPUTERNAME           1132
#define IDC_STATIC_COMPUTERNAME         1133
#define IDC_GROUP_CONNECTMETHOD         1134
#define IDC_STATIC_WAITING              1135
#define IDC_RADIO_KING                  1141
#define IDC_RADIO_QUEEN                 1142
#define IDC_RADIO_ROOK                  1143
#define IDC_RADIO_BISHOP                1144
#define IDC_RADIO_KNIGHT                1145
#define IDC_RADIO_PAWN                  1146
#define IDC_EDIT_FROM                   1147
#define IDC_EDIT_TO                     1148
#define IDC_EDIT_STEP                   1149
#define IDC_STATIC_MAXMOVES             1151
#define IDC_EDIT_DEFENDSTRENGTH         1152
#define IDC_RADIO_METRIC_DTC            1153
#define IDC_RADIO_METRIC_DTM            1154
#define IDC_RADIO_DEPTHINMOVES          1155
#define IDC_RADIO_DEPTHINPLIES          1156
#define IDC_GROUP_DEPTHFORMAT           1157
#define IDC_GROUP_METRIC                1158
#define IDC_EDIT_TABLEBASEPATH          1159
#define IDC_STATIC_TABLEBASEPATH        1160
#define IDC_BUTTON_PATH                 1161
#define IDC_STATIC_DEFENDSTRENGTH       1162
#define IDC_BUTTON_DECOMPRESSALL        1163
#define IDC_CHECK_SHOWFIELDNAMES        1170
#define IDC_CHECK_SHOWLEGALMOVES        1171
#define IDC_CHECK_SHOWCOMPUTERTIME      1172
#define IDC_CHECK_INDICATEPLAYERINTURN  1173
#define IDC_CHECK_ANIMATEMOVES          1174
#define IDC_CHECK_ANIMATECHECKMATE      1175
#define IDC_CHECK_ASKFORNEWGAME         1176
#define IDC_LIST_ENGINES                1180
#define IDC_BUTTON_ADD                  1181
#define IDC_BUTTON_DELETE               1182
#define IDC_BUTTON_CHECK                1183
#define IDC_SPIN_MOVECOUNT              1190
#define IDC_SPIN_DEFENDSTRENGTH         1191
#define IDC_BUTTON_SAVE                 1192
#define IDC_BUTTON_SETDEFAULT           1193
#define IDC_BUTTON_SENDTOENGINE         1194
#define IDC_BUTTON_MOVEUP               1201
#define IDC_BUTTON_MOVEDOWN             1202
#define IDC_CHECK_DEPTH                 1203
#define IDC_CHECK_SELDEPTH              1204
#define IDC_CHECK_SCORE                 1205
#define IDC_CHECK_TIME                  1206
#define IDC_CHECK_NODES                 1207
#define IDC_CHECK_NODESPS               1208
#define IDC_CHECK_PV                    1209
#define IDC_CHECK_STRING                1210
#define IDC_CHECK_HASHFULL              1211
#define IDC_CHECK_MULTIPV               1212
#define IDC_CHECK_CPULOAD               1213
#define ID_FILE_NEWGAME_YOUPLAYWHITE    32771
#define ID_FILE_NEWGAME_YOUPLAYBLACK    32772
#define ID_FILE_LOADGAME                32773
#define ID_FILE_PLAY_REMOTE             32774
#define ID_FILE_DISCONNECT_REMOTEGAME   32775
#define ID_FILE_SAVEAS                  32776
#define ID_FILE_SHOWHISTORY             32777
#define ID_FILE_OFFERDRAW               32778
#define ID_FILE_RESIGN                  32779
#define ID_FILE_EXIT                    32780
#define ID_EDIT_UNDOALL                 32790
#define ID_EDIT_UNDOPLY                 32791
#define ID_EDIT_COPY_FEN                32792
#define ID_EDIT_PASTE_FEN               32793
#define ID_EDIT_STARTSETUP              32794
#define ID_EDIT_TURNBOARD               32795
#define ID_EDIT_CLEARBOARD              32796
#define ID_EDIT_SETUPSTARTPOSITION      32797
#define ID_EDIT_SWAPCOLORS              32800
#define ID_EDIT_MIRRORCOLUMN            32801
#define ID_EDIT_MIRRORROW               32802
#define ID_EDIT_MIRRORDIAG1             32803
#define ID_EDIT_MIRRORDIAG2             32804
#define ID_EDIT_ROTATERIGHT             32805
#define ID_EDIT_ROTATELEFT              32806
#define ID_EDIT_ROTATE180               32807
#define ID_EDIT_SWITCHPLAYERINTURN      32810
#define ID_EDIT_ENDSETUP                32812
#define ID_ESCAPE                       32813
#define ID_EDIT_VALIDATE_BOARD          32814
#define ID_EDIT_ADD_WHITE_KING          32821
#define ID_EDIT_ADD_WHITE_QUEEN         32822
#define ID_EDIT_ADD_WHITE_ROOK          32823
#define ID_EDIT_ADD_WHITE_KNIGHT        32824
#define ID_EDIT_ADD_WHITE_BISHOP        32825
#define ID_EDIT_ADD_WHITE_PAWN          32826
#define ID_EDIT_ADD_BLACK_KING          32831
#define ID_EDIT_ADD_BLACK_QUEEN         32832
#define ID_EDIT_ADD_BLACK_ROOK          32833
#define ID_EDIT_ADD_BLACK_BISHOP        32834
#define ID_EDIT_ADD_BLACK_KNIGHT        32835
#define ID_EDIT_ADD_BLACK_PAWN          32836
#define ID_EDIT_REMOVE                  32837
#define ID_SETTINGS_START_THINKING      32840
#define ID_MOVENOW                      32841
#define ID_AUTOPLAY_RESTART_AT_END      32842
#define ID_AUTOPLAY_NO_RESTART          32843
#define ID_AUTOPLAY_BOTH_LEVEL_1        32851
#define ID_AUTOPLAY_BOTH_LEVEL_2        32852
#define ID_AUTOPLAY_BOTH_LEVEL_3        32853
#define ID_AUTOPLAY_BOTH_LEVEL_4        32854
#define ID_AUTOPLAY_BOTH_LEVEL_5        32855
#define ID_AUTOPLAY_BOTH_LEVEL_6        32856
#define ID_AUTOPLAY_WHITE_LEVEL_1       32861
#define ID_AUTOPLAY_WHITE_LEVEL_2       32862
#define ID_AUTOPLAY_WHITE_LEVEL_3       32863
#define ID_AUTOPLAY_WHITE_LEVEL_4       32864
#define ID_AUTOPLAY_WHITE_LEVEL_5       32865
#define ID_AUTOPLAY_WHITE_LEVEL_6       32866
#define ID_AUTOPLAY_BLACK_LEVEL_1       32871
#define ID_AUTOPLAY_BLACK_LEVEL_2       32872
#define ID_AUTOPLAY_BLACK_LEVEL_3       32873
#define ID_AUTOPLAY_BLACK_LEVEL_4       32874
#define ID_AUTOPLAY_BLACK_LEVEL_5       32875
#define ID_AUTOPLAY_BLACK_LEVEL_6       32876
#define ID_VIEW                         32880
#define ID_LEVEL_TIMED_GAME             32890
#define ID_LEVEL_1                      32891
#define ID_LEVEL_2                      32892
#define ID_LEVEL_3                      32893
#define ID_LEVEL_4                      32894
#define ID_LEVEL_5                      32895
#define ID_LEVEL_6                      32896
#define ID_LEVEL_SPEEDCHESS             32897
#define ID_LEVEL_EDIT_TIMESETTINGS      32900
#define ID_SETTINGS_TOGGLECLOCK         32901
#define ID_SETTINGS_RESETCLOCK          32902
#define ID_WHITE_ENGINE_SETTINGS        32910
#define ID_WHITE_ENGINE_GETSTATE        32911
#define ID_BLACK_ENGINE_SETTINGS        32912
#define ID_BLACK_ENGINE_GETSTATE        32913
#define ID_EXTERNENGINE_SWAP            32914
#define ID_EXTERNENGINE_REGISTER        32915
#define ID_OPENINGLIBRARY_ENABLED       32930
#define ID_ENDGAMETABLEBASE_ENABLED     32931
#define ID_TABLEBASE_SETTINGS           32932
#define ID_VIEW_TRACEOPENING            32940
#define ID_VIEW_TRACEWINDOW             32941
#define ID_LANGUAGE_DUMMY               32950
#define ID_SETTINGS_LANGUAGE0           32950
#define ID_SETTINGS_LANGUAGE1           32951
#define ID_SETTINGS_LANGUAGE2           32952
#define ID_SETTINGS_LANGUAGE3           32953
#define ID_SETTINGS_LANGUAGE4           32954
#define ID_SETTINGS_LANGUAGE5           32955
#define ID_SETTINGS_LANGUAGE6           32956
#define ID_SETTINGS_LANGUAGE7           32957
#define ID_SETTINGS_LANGUAGE8           32958
#define ID_SETTINGS_LANGUAGE9           32959
#define ID_WHITE_EXTERNENGINE0          33000
#define ID_WHITE_EXTERNENGINE1          33001
#define ID_WHITE_EXTERNENGINE2          33002
#define ID_WHITE_EXTERNENGINE3          33003
#define ID_WHITE_EXTERNENGINE4          33004
#define ID_WHITE_EXTERNENGINE5          33005
#define ID_WHITE_EXTERNENGINE6          33006
#define ID_WHITE_EXTERNENGINE7          33007
#define ID_WHITE_EXTERNENGINE8          33008
#define ID_WHITE_EXTERNENGINE9          33009
#define ID_WHITE_EXTERNENGINE10         33010
#define ID_WHITE_EXTERNENGINE11         33011
#define ID_WHITE_EXTERNENGINE12         33012
#define ID_WHITE_EXTERNENGINE13         33013
#define ID_WHITE_EXTERNENGINE14         33014
#define ID_WHITE_EXTERNENGINE15         33015
#define ID_WHITE_EXTERNENGINE16         33016
#define ID_WHITE_EXTERNENGINE17         33017
#define ID_WHITE_EXTERNENGINE18         33018
#define ID_WHITE_EXTERNENGINE19         33019
#define ID_WHITE_EXTERNENGINE20         33020
#define ID_BLACK_EXTERNENGINE0          33040
#define ID_BLACK_EXTERNENGINE1          33041
#define ID_BLACK_EXTERNENGINE2          33042
#define ID_BLACK_EXTERNENGINE3          33043
#define ID_BLACK_EXTERNENGINE4          33044
#define ID_BLACK_EXTERNENGINE5          33045
#define ID_BLACK_EXTERNENGINE6          33046
#define ID_BLACK_EXTERNENGINE7          33047
#define ID_BLACK_EXTERNENGINE8          33048
#define ID_BLACK_EXTERNENGINE9          33049
#define ID_BLACK_EXTERNENGINE10         33050
#define ID_BLACK_EXTERNENGINE11         33051
#define ID_BLACK_EXTERNENGINE12         33052
#define ID_BLACK_EXTERNENGINE13         33053
#define ID_BLACK_EXTERNENGINE14         33054
#define ID_BLACK_EXTERNENGINE15         33055
#define ID_BLACK_EXTERNENGINE16         33056
#define ID_BLACK_EXTERNENGINE17         33057
#define ID_BLACK_EXTERNENGINE18         33058
#define ID_BLACK_EXTERNENGINE19         33059
#define ID_BLACK_EXTERNENGINE20         33060
#define ID_HELP_HINT                    33100
#define ID_HELP_INFINITEHINT            33101
#define ID_HELP_SHOWOPENINGLIBRARY      33102
#define ID_HELP_ABOUTCHESS              33103
#define ID_OPTIONS_FORMAT_SHORTNOTATION 33110
#define ID_OPTIONS_FORMAT_LONGNOTATION  33111
#define ID_PROMOTE_TO_QUEEN             33120
#define ID_PROMOTE_TO_ROOK              33121
#define ID_PROMOTE_TO_BISHOP            33122
#define ID_PROMOTE_TO_KNIGHT            33123
#define ID_TEST_DEBUG                   33141
#define ID_TEST_SHOWFIELDATTACKS        33142
#define ID_TEST_SHOWMATERIAL            33143
#define ID_TEST_SHOWBISHOPFLAGS         33144
#define ID_TEST_SHOWPAWNCOUNT           33145
#define ID_TEST_SHOWLASTCAPTURE         33146
#define ID_TEST_SHOWPOSITIONREPEATS     33147
#define ID_TEST_SHOWLASTMOVEINFO        33148
#define ID_TEST_SHOWCHECKINGSDAPOS      33149
#define ID_TEST_SHOWSETUPMODE           33150
#define ID_TEST_MOVEBACKWARDS           33151
#define ID_TEST_FICTIVEPAWNCAPTURES     33152
#define ID_TEST_TRANSFORMPOSITION       33153
#define ID_TEST_NORMALIZEPOSITION       33154
#define ID_TEST_SHOWMESSAGE             33155
#define ID_TEST_SAVETOEXTERNENGINE      33156
#define ID_TEST_PLOTWINSPVALUES         33157
#define ID_TEST_SHOWENGINECONSOLE       33158
#define ID_TEST_SHOWFEN                 33159
#define ID_TEST_FINDKNIGHTROUTE         33160
#define ID_GOTO_DIR                     33190
#define ID_GOTO_DRIVE                   33191
#define ID_GOTO_MOVECOUNT               33192
#define ID_GOTO_TIME                    33193
#define ID_GOTO_TIMEINCREMENT           33194
#define ID_GOTO_MINUTES1                33195
#define ID_GOTO_MINUTES2                33196
#define ID_GOTO_MINUTES3                33197
#define ID_GOTO_MINUTES4                33198
#define ID_GOTO_MINUTES5                33199
#define ID_GOTO_MINUTES6                33200
#define ID_GOTO_COMPUTERNAME            33201
#define ID_GOTO_PLAYER                  33202
#define ID_GOTO_DEFENDSTRENGTH          33203
#define ID_SELECT_TIMEDGAMETAB          33204
#define ID_SELECT_SPEEDCHESSTAB         33205
#define ID_SELECT_LEVELTSTAB            33206
#define ID_CLOSE_WINDOW                 33207
#define ID_FILE_ANALYZEPOSITION         33210
#define ID_BUTTONCLOSEFOLDER            33211
#define ID_BUTTONOPENEDFOLDER           33212
#define ID_OPENING_EXPAND               33220
#define ID_MSG_CHESSPLAYERSTATE_CHANGED 33250
#define ID_MSG_CHESSPLAYERMSG_CHANGED   33251
#define ID_MSG_ENGINE_CHANGED           33252
#define ID_MSG_TRACEWINDOW_CHANGED      33254
#define ID_MSG_SHOW_SELECTED_MOVE       33255
#define ID_MSG_REMOTESTATE_CHANGED      33256
#define ID_MSG_SHOW_DROPDOWN            33257
#define ID_MSG_PRINTTEXT                33258
#define ID_MSG_UPDATEMESSAGEFIELD       33259
#define ID_MSG_CLEARTRACE               33260
#define ID_MSG_REPOSITIONTRACEWINDOW    33261
#define ID_FONTSIZE_75                  33262
#define ID_FONTSIZE_100                 33263
#define ID_FONTSIZE_125                 33264
#define ID_FONTSIZE_150                 33265
#define ID_FONTSIZE_175                 33266
#define ID_FONTSIZE_200                 33267
#define ID_VIEW_INFOFIELDS              33268
#define ID_GOOD_MOVE                    33280
#define ID_EXCELLENT_MOVE               33281
#define ID_BAD_MOVE                     33282
#define ID_VERYBAD_MOVE                 33283
#define ID_INTERESTING_MOVE             33284
#define ID_DOUBIOUS_MOVE                33285
#define ID_REMOVE_ANNOTATION            33286
#define ID_REDIGER_SKIFTSPILLERITR33307 33307
#define ID_EDIT_SWITCHPLAYERTOMOVE      33308

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        426
#define _APS_NEXT_COMMAND_VALUE         33309
#define _APS_NEXT_CONTROL_VALUE         1204
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
