//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D3Function.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDR_INFOVIEW                    130
#define IDR_FUNCTIONR2R1SURFACE         140
#define IDR_PARAMETRICR1R3SURFACE       141
#define IDR_PARAMETRICR2R3SURFACE       142
#define IDR_ISOSURFACE                  143
#define IDR_PROFILE                     144
#define IDR_SELECTGLYPH                 145
#define IDD_DIALOGENTEROPTIONSNAME      150
#define IDD_DIALOGORGANIZEOPTIONS       151
#define IDB_TESTBITMAP                  200
#define IDB_CIRCLEARROWBITMAP           201
#define IDB_LEFTRIGHTARROWBITMAP        202
#define IDB_BLACKSQUAREBITMAP           203
#define IDB_ROTATECORNERBITMAP          204
#define IDC_STATIC_FUNCTION             1070
#define IDC_EDIT_EXPR                   1071
#define IDC_STATIC_XINTERVAL            1072
#define IDC_EDIT_XFROM                  1073
#define IDC_STATIC_DASH1                1074
#define IDC_EDIT_XTO                    1075
#define IDC_STATIC_YINTERVAL            1076
#define IDC_EDIT_YFROM                  1077
#define IDC_STATIC_DASH2                1078
#define IDC_EDIT_YTO                    1079
#define IDC_STATIC_ZINTERVAL            1080
#define IDC_EDIT_ZFROM                  1081
#define IDC_STATIC_DASH3                1082
#define IDC_EDIT_ZTO                    1083
#define IDC_STATIC_POINTCOUNT           1090
#define IDC_EDIT_POINTS                 1091
#define IDC_STATIC_EQUAL_ZERO           1092
#define IDC_STATIC_TEXTUREFILENAME      1093
#define IDC_EDIT_TEXTUREFILENAME        1094
#define IDC_BUTTON_BROWSETEXTURE        1095
#define IDC_STATIC_CELLSIZE             1096
#define IDC_EDIT_CELLSIZE               1097
#define IDC_STATIC_LAMBDA               1098
#define IDC_EDIT_LAMBDA                 1099
#define IDC_CHECK_TETRAHEDRAL           1100
#define IDC_CHECK_TETRAOPTIMIZE4        1101
#define IDC_CHECK_ORIGINOUTSIDE         1102
#define IDC_CHECK_SHOWSTATISTICS        1103
#define IDC_CHECK_DEBUGPOLYGONIZER      1104
#define IDC_CHECK_DOUBLESIDED           1110
#define IDC_CHECK_MACHINECODE           1111
#define IDC_CHECK_CREATELISTFILE        1112
#define IDC_CHECK_CALCULATENORMALS      1113
#define IDC_CHECK_CALCULATETEXTURE      1114
#define IDC_CHECK_INCLUDETIME           1120
#define IDC_STATIC_TIMEINTERVAL         1121
#define IDC_EDIT_TIMEFROM               1122
#define IDC_STATIC_DASH4                1123
#define IDC_EDIT_TIMETO                 1124
#define IDC_STATIC_FRAMECOUNT           1125
#define IDC_EDIT_FRAMECOUNT             1126
#define IDC_BUTTON_HELP                 1131
#define IDC_STATIC_BOUNDINGBOX          1132
#define IDC_STATIC_FUNCTIONX            1170
#define IDC_BUTTON_HELPX                1171
#define IDC_EDIT_EXPRX                  1172
#define IDC_EDITCOMMON                  1173
#define IDC_STATICCOMMON                1174
#define IDC_STATIC_FUNCTIONY            1180
#define IDC_BUTTON_HELPY                1181
#define IDC_EDIT_EXPRY                  1182
#define IDC_STATIC_FUNCTIONZ            1190
#define IDC_BUTTON_HELPZ                1191
#define IDC_EDIT_EXPRZ                  1192
#define IDC_STATIC_TINTERVAL            1200
#define IDC_EDIT_TFROM                  1201
#define IDC_EDIT_TTO                    1202
#define IDC_STATIC_SINTERVAL            1210
#define IDC_EDIT_SFROM                  1211
#define IDC_EDIT_STO                    1212
#define IDC_STATIC_TSTEPCOUNT           1213
#define IDC_EDIT_TSTEPCOUNT             1214
#define IDC_STATIC_SSTEPCOUNT           1215
#define IDC_EDIT_SSTEPCOUNT             1216
#define IDC_STATIC_DEBUG3DFRAME         1220
#define IDC_STATIC_INFO                 1221
#define IDC_EDIT_EDGECOUNT              1222
#define IDC_SPIN_EDGECOUNT              1223
#define IDC_EDIT_DEGREES                1224
#define IDC_SLIDER_DEGREE               1225
#define IDC_STATIC_DEGREE               1226
#define IDC_RADIO_ROTATE                1227
#define IDC_RADIO_STRETCH               1228
#define IDC_CHECK_ROTATESMOOTH          1229
#define IDC_CHECK_NORMALSMOOTH          1230
#define IDC_BUTTON_REFRESH              1231
#define IDC_STATIC_PROFILEIMAGE2D       1233
#define IDC_STATIC_PROFILEIMAGE3D       1234
#define IDC_CHECKDOUBLESIDED            1235
#define IDC_COMBOROTATEAXIS             1236
#define IDC_COMBOROTATEAXISALIGNSTO     1237
#define IDC_CHECK_USECOLOR              1238
#define IDC_MFCCOLORBUTTON              1239
#define IDC_STATICGLYPHFRAME            1240
#define IDC_COMBOOPTIONSNAME            1400
#define IDC_LISTOPTIONNAMES             1401
#define IDC_BUTTONRENAME                1402
#define IDC_BUTTONDELETE                1403
#define IDC_BUTTONMOVEUP                1404
#define IDC_BUTTONMOVEDOWN              1405
#define IDC_EDIT_INFOBOX                1406
#define IDC_STATIC_ICON                 1410
#define ID_INDICATOR_POSITION           32771
#define ID_INDICATOR_DEBUG              32772
#define ID_FILE_FUNCTIONSURFACE         32801
#define ID_FILE_PARAMETRICCURVE         32802
#define ID_FILE_PARAMETRICSURFACE       32803
#define ID_FILE_ISOSURFACE              32804
#define ID_FILE_PROFILESURFACE          32805
#define ID_FILE_READ3DPOINTSFROMFILE    32806
#define ID_FILE_READOBJFILE             32807
#define ID_FILE_CONVERTALL              32808
#define ID_FILE_EXIT                    32820
#define ID_VIEW_SHOW3DINFO              32900
#define ID_EDIT_FINDMATCHINGPARENTESIS  32900
#define ID_RESETPOSITIONS               32910
#define ID_OBJECT_EDITFUNCTION          32920
#define ID_DEBUG_STEPCUBE               33000
#define ID_DEBUG_STEPTETRA              33001
#define ID_DEBUG_STEPFACE               33002
#define ID_DEBUG_STEPVERTEX             33003
#define ID_DEBUG_GO                     33004
#define ID_DEBUG_STOPDEBUGGING          33005
#define ID_DEBUG_TOGGLEBREAKONPREVCUBE  33006
#define ID_DEBUG_CLEARALLBREAKPOINTS    33007
#define ID_DEBUG_DISABLEALLBREAKPOINTS  33008
#define ID_DEBUG_SLIDINGCAMERA          33009
#define ID_OPTIONS_SAVEOPTIONS          33100
#define ID_OPTIONS_LOADOPTIONS          33110
#define ID_OPTIONS_LOADOPTIONS1         33111
#define ID_OPTIONS_LOADOPTIONS2         33112
#define ID_OPTIONS_LOADOPTIONS3         33113
#define ID_OPTIONS_LOADOPTIONS4         33114
#define ID_OPTIONS_LOADOPTIONS5         33115
#define ID_OPTIONS_LOADOPTIONS6         33116
#define ID_OPTIONS_LOADOPTIONS7         33117
#define ID_OPTIONS_LOADOPTIONS8         33118
#define ID_OPTIONS_LOADOPTIONS9         33119
#define ID_OPTIONS_ORGANIZEOPTIONS      33120
#define ID_MSG_RENDER                   33202
#define ID_MSG_KILLDEBUGGER             33204
#define ID_GOTO_EXPR                    33500
#define ID_GOTO_EXPRX                   33501
#define ID_GOTO_EXPRY                   33502
#define ID_GOTO_EXPRZ                   33503
#define ID_GOTO_CELLSIZE                33504
#define ID_GOTO_XINTERVAL               33505
#define ID_GOTO_YINTERVAL               33506
#define ID_GOTO_ZINTERVAL               33507
#define ID_GOTO_TINTERVAL               33508
#define ID_GOTO_SINTERVAL               33509
#define ID_GOTO_TIMEINTERVAL            33510
#define ID_GOTO_POINTCOUNT              33511
#define ID_GOTO_TSTEPCOUNT              33512
#define ID_GOTO_SSTEPCOUNT              33513
#define ID_GOTO_FRAMECOUNT              33514
#define ID_GOTO_COMMON                  33515
#define ID_FILE_SELECTFROMFONT          33530
#define ID_EDIT_DELETE                  33531
#define ID_EDIT_CONNECT                 33532
#define ID_EDIT_INVERTNORMALS           33533
#define ID_EDIT_MIRROR_HORIZONTAL       33534
#define ID_EDIT_MIRROR_VERTICAL         33535
#define ID_VIEW_SHOWPOINTS              33536
#define ID_VIEW_SHOWNORMALS             33537
#define ID_VIEW_AUTO_UPDATE_3D          33538
#define ID_TOOLS_LINE                   33539
#define ID_TOOLS_BEZIERCURVE            33540
#define ID_TOOLS_RECTANGLE              33541
#define ID_TOOLS_POLYGON                33542
#define ID_TOOLS_ELLIPSE                33543
#define ID_TOOLS_SELECT                 33544
#define ID_GODOWN                       33560
#define ID_GOLEFT                       33561
#define ID_GORIGHT                      33562
#define ID_GOUP                         33563

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         33570
#define _APS_NEXT_CONTROL_VALUE         1451
#define _APS_NEXT_SYMED_VALUE           169
#endif
#endif
