//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D3Function.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDR_INFOVIEW                    130
#define IDR_FUNCTIONR2R1SURFACE         140
#define IDR_PARAMETRICR1R3SURFACE       141
#define IDR_PARAMETRICR2R3SURFACE       142
#define IDR_ISOSURFACE                  143
#define IDR_PROFILE                     144
#define IDR_SELECTGLYPH                 145
#define IDD_DIALOGENTEROPTIONSNAME      150
#define IDD_DIALOGORGANIZEOPTIONS       151
#define IDB_TESTBITMAP                  200
#define IDB_CIRCLEARROWBITMAP           201
#define IDB_LEFTRIGHTARROWBITMAP        202
#define IDB_BLACKSQUAREBITMAP           203
#define IDB_ROTATECORNERBITMAP          204
#define IDC_EDIT_INFOBOX                1071
#define IDC_STATIC_FUNCTION             1072
#define IDC_EDIT_EXPR                   1073
#define IDC_STATIC_EQUAL_ZERO           1074
#define IDC_STATIC_XINTERVAL            1080
#define IDC_EDIT_XFROM                  1081
#define IDC_STATIC_DASH1                1082
#define IDC_EDIT_XTO                    1083
#define IDC_STATIC_YINTERVAL            1090
#define IDC_EDIT_YFROM                  1091
#define IDC_STATIC_DASH2                1092
#define IDC_EDIT_YTO                    1093
#define IDC_STATIC_ZINTERVAL            1100
#define IDC_EDIT_ZFROM                  1101
#define IDC_STATIC_DASH3                1102
#define IDC_EDIT_ZTO                    1103
#define IDC_STATIC_POINTCOUNT           1110
#define IDC_EDIT_POINTCOUNT             1111
#define IDC_STATIC_TINTERVAL            1120
#define IDC_EDIT_TFROM                  1121
#define IDC_EDIT_TTO                    1122
#define IDC_STATIC_TSTEPCOUNT           1123
#define IDC_EDIT_TSTEPCOUNT             1124
#define IDC_STATIC_SINTERVAL            1130
#define IDC_EDIT_SFROM                  1131
#define IDC_EDIT_STO                    1132
#define IDC_STATIC_SSTEPCOUNT           1133
#define IDC_EDIT_SSTEPCOUNT             1134
#define IDC_STATIC_TIMEINTERVAL         1141
#define IDC_EDIT_TIMEFROM               1142
#define IDC_STATIC_DASH4                1143
#define IDC_EDIT_TIMETO                 1144
#define IDC_STATIC_FRAMECOUNT           1145
#define IDC_EDIT_FRAMECOUNT             1146
#define IDC_STATIC_TEXTUREFILENAME      1220
#define IDC_EDIT_TEXTUREFILENAME        1221
#define IDC_BUTTON_BROWSETEXTURE        1222
#define IDC_CHECK_DOUBLESIDED           1230
#define IDC_CHECK_MACHINECODE           1231
#define IDC_CHECK_CREATELISTFILE        1232
#define IDC_CHECK_CALCULATENORMALS      1233
#define IDC_CHECK_CALCULATETEXTURE      1234
#define IDC_CHECK_INCLUDETIME           1240
#define IDC_STATIC_PROFILEFILENAME      1250
#define IDC_EDIT_PROFILEFILENAME        1251
#define IDC_BUTTON_BROWSEPROFILE        1252
#define IDC_STATIC_CELLSIZE             1300
#define IDC_EDIT_CELLSIZE               1301
#define IDC_STATIC_LAMBDA               1302
#define IDC_EDIT_LAMBDA                 1303
#define IDC_CHECK_TETRAHEDRAL           1304
#define IDC_CHECK_TETRAOPTIMIZE4        1305
#define IDC_CHECK_ORIGINOUTSIDE         1306
#define IDC_CHECK_SHOWSTATISTICS        1307
#define IDC_CHECK_DEBUGPOLYGONIZER      1308
#define IDC_STATIC_BOUNDINGBOX          1309
#define IDC_BUTTON_HELP                 1400
#define IDC_STATIC_COMMON               1401
#define IDC_EDIT_COMMON                 1402
#define IDC_STATIC_FUNCTIONX            1410
#define IDC_BUTTON_HELPX                1411
#define IDC_EDIT_EXPRX                  1412
#define IDC_STATIC_FUNCTIONY            1420
#define IDC_BUTTON_HELPY                1421
#define IDC_EDIT_EXPRY                  1422
#define IDC_STATIC_FUNCTIONZ            1430
#define IDC_BUTTON_HELPZ                1431
#define IDC_EDIT_EXPRZ                  1432
#define IDC_BUTTON_REFRESH              1500
#define IDC_STATIC_PROFILEIMAGE2D       1501
#define IDC_STATIC_PROFILEIMAGE3D       1502
#define IDC_STATIC_DEBUG3DFRAME         1503
#define IDC_STATIC_INFO                 1504
#define IDC_STATIC_EDGECOUNT            1510
#define IDC_EDIT_EDGECOUNT              1511
#define IDC_SPIN_EDGECOUNT              1512
#define IDC_STATIC_DEGREES              1520
#define IDC_EDIT_DEGREES                1521
#define IDC_RADIO_ROTATE                1530
#define IDC_RADIO_STRETCH               1531
#define IDC_CHECK_ROTATESMOOTH          1540
#define IDC_CHECK_NORMALSMOOTH          1541
#define IDC_STATIC_ROTATEAXIS           1542
#define IDC_COMBO_ROTATEAXIS            1543
#define IDC_STATIC_ROTATEAXISALIGNSTO   1544
#define IDC_COMBO_ROTATEAXISALIGNSTO    1545
#define IDC_CHECK_USECOLOR              1550
#define IDC_MFCCOLORBUTTON              1551
#define IDC_STATIC_DEGREE               1561
#define IDC_SLIDER_DEGREE               1562
#define IDC_STATIC_GLYPHFRAME           1600
#define IDC_COMBO_OPTIONSNAME           1700
#define IDC_LIST_OPTIONNAMES            1701
#define IDC_BUTTON_RENAME               1702
#define IDC_BUTTON_DELETE               1703
#define IDC_BUTTON_MOVEUP               1704
#define IDC_BUTTON_MOVEDOWN             1705
#define IDC_STATIC_ICON                 1800
#define ID_INDICATOR_POSITION           32771
#define ID_INDICATOR_DEBUG              32772
#define ID_FILE_FUNCTIONSURFACE         32801
#define ID_FILE_PARAMETRICCURVE         32802
#define ID_FILE_PARAMETRICSURFACE       32803
#define ID_FILE_ISOSURFACE              32804
#define ID_FILE_PROFILESURFACE          32805
#define ID_FILE_READ3DPOINTSFROMFILE    32806
#define ID_FILE_READOBJFILE             32807
#define ID_FILE_CONVERTALL              32808
#define ID_FILE_EXIT                    32820
#define ID_VIEW_SHOW3DINFO              32900
#define ID_EDIT_FINDMATCHINGPARENTESIS  32901
#define ID_RESETPOSITIONS               32910
#define ID_OBJECT_EDITFUNCTION          32920
#define ID_DEBUG_STEPCUBE               33000
#define ID_DEBUG_STEPTETRA              33001
#define ID_DEBUG_STEPFACE               33002
#define ID_DEBUG_STEPVERTEX             33003
#define ID_DEBUG_GO                     33004
#define ID_DEBUG_STOPDEBUGGING          33005
#define ID_DEBUG_TOGGLEBREAKONPREVCUBE  33006
#define ID_DEBUG_CLEARALLBREAKPOINTS    33007
#define ID_DEBUG_DISABLEALLBREAKPOINTS  33008
#define ID_DEBUG_SLIDINGCAMERA          33009
#define ID_OPTIONS_SAVEOPTIONS          33100
#define ID_OPTIONS_LOADOPTIONS          33110
#define ID_OPTIONS_LOADOPTIONS1         33111
#define ID_OPTIONS_LOADOPTIONS2         33112
#define ID_OPTIONS_LOADOPTIONS3         33113
#define ID_OPTIONS_LOADOPTIONS4         33114
#define ID_OPTIONS_LOADOPTIONS5         33115
#define ID_OPTIONS_LOADOPTIONS6         33116
#define ID_OPTIONS_LOADOPTIONS7         33117
#define ID_OPTIONS_LOADOPTIONS8         33118
#define ID_OPTIONS_LOADOPTIONS9         33119
#define ID_OPTIONS_ORGANIZEOPTIONS      33120
#define ID_MSG_RENDER                   33200
#define ID_MSG_KILLDEBUGGER             33201
#define ID_FILE_SELECTFROMFONT          33230
#define ID_EDIT_DELETE                  33240
#define ID_EDIT_CONNECT                 33241
#define ID_EDIT_INVERTNORMALS           33242
#define ID_EDIT_MIRROR_HORIZONTAL       33243
#define ID_EDIT_MIRROR_VERTICAL         33244
#define ID_VIEW_SHOWPOINTS              33250
#define ID_VIEW_SHOWNORMALS             33251
#define ID_VIEW_AUTO_UPDATE_3D          33252
#define ID_TOOLS_LINE                   33260
#define ID_TOOLS_BEZIERCURVE            33261
#define ID_TOOLS_RECTANGLE              33262
#define ID_TOOLS_POLYGON                33263
#define ID_TOOLS_ELLIPSE                33264
#define ID_TOOLS_SELECT                 33265
#define ID_GODOWN                       33270
#define ID_GOLEFT                       33271
#define ID_GORIGHT                      33272
#define ID_GOUP                         33273

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         33570
#define _APS_NEXT_CONTROL_VALUE         1455
#define _APS_NEXT_SYMED_VALUE           169
#endif
#endif
