// Microsoft Developer Studio generated include file.
// Used by ParserDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DIALOGPARSERDEMO            102
#define IDD_DIALOGERRORS                103
#define IDD_DIALOGPRODUCTIONS           104
#define IDD_DIALOGTREE                  105
#define IDB_BITMAPTERMINAL              106
#define IDD_DIALOGSTATES                107
#define IDD_DIALOGFIND                  108
#define IDD_DIALOGSTACKSIZE             109
#define IDD_DIALOGSHOWSTATE             110
#define IDD_DIALOGBREAKSYMBOLS          111
#define IDR_MAINFRAME                   112
#define IDR_MAINMENU                    113
#define IDR_MENUREGSYMBOLS              114
#define IDR_ACCELERATORMAIN             115
#define IDR_ACCELERATORSHOWSTATE        116
#define IDR_ACCELERATORFIND             117
#define IDR_ACCELERATORTREE             118
#define IDR_ACCELERATORERRORS           119
#define IDD_DIALOGGOTO                  120
#define IDC_LOOKAHEAD                   1000
#define IDC_EDITINPUTSTRING             1001
#define IDC_BREAKPRODTEXT               1002
#define IDC_STATICSTACK                 1003
#define IDC_ACTION                      1004
#define IDC_STATE                       1005
#define IDC_EDITCASCADECOUNT            1006
#define IDC_BREAKSTATETEXT              1007
#define IDC_BREAKSYMBOLTEXT             1008
#define IDC_PRODUCTIONLIST              1009
#define IDC_BUTTONSELECTALL             1010
#define IDC_BUTTONCLEAR                 1011
#define IDC_CHECKBREAKONPRODUCTION      1012
#define IDC_CHECKBREAKONPOS             1013
#define IDC_CHECKBREAKONERROR           1014
#define IDC_EDITMAXERRORCOUNT           1015
#define IDC_LISTERRORS                  1016
#define IDC_DERIVATIONTREE              1017
#define IDC_CHECKBREAKONSTATE           1018
#define IDC_BUTTONEXPAND                1019
#define IDC_CHECKBREAKONSYMBOL          1020
#define IDC_BUTTONEXPANDALL             1021
#define IDC_EDITSTATES                  1022
#define IDC_LISTDEBUG                   1023
#define IDC_DEBUGLABEL                  1024
#define IDC_ERRORSLABEL                 1025
#define IDC_SOURCEPOSITION              1026
#define IDC_COMBOFINDWHAT               1027
#define IDC_BUTTONREGSYMBOLSMENU        1028
#define IDC_CHECKMATCHWHOLEWORD         1029
#define IDC_CHECKMATCHCASE              1030
#define IDC_CHECKUSEREGEXP              1031
#define IDC_RADIOUP                     1032
#define IDC_RADIODOWN                   1033
#define IDC_FINDNEXT                    1034
#define IDC_EDITSTACKSIZE               1035
#define IDC_EDITSTATE                   1036
#define IDC_LISTSYMBOLS                 1037
#define IDC_EDITLINENUMBER              1038
#define IDC_LOOKAHEADLABEL              1039
#define IDC_STATELABEL                  1040
#define IDC_ACTIONLABEL                 1041
#define ID_FILE_EXIT                    32771
#define ID_HELP_ABOUTPARSERDEMO         32772
#define ID_EDIT_BREAKONTEXTPOSITION     32773
#define ID_EDIT_NEXTERROR               32774
#define ID_EDIT_PREVERROR               32775
#define ID_EDIT_FINDNEXT                32776
#define ID_EDIT_FINDPREV                32777
#define ID_EDIT_SELECTPRODUCTIONSTOBREAKON 32778
#define ID_EDIT_SELECTSTATESTOBREAKON   32779
#define ID_EDIT_LISTDEBUG               32780
#define ID_EDIT_SELECTSYMBOLSTOBREAKON  32781
#define ID_EDIT_FINDMATCHINGPARANTHES   32782
#define ID_EDIT_DERIVATIONTREE          32783
#define ID_EDIT_GOTO                    32784
#define ID_RUN_PARSEINPUT               32785
#define ID_RUN_STARTDEBUG_RESETPARSER   32786
#define ID_RUN_STARTDEBUG_RUN           32787
#define ID_RUN_STARTDEBUG_STEP          32788
#define ID_RUN_STARTDEBUG_STEPOVER      32789
#define ID_RUN_STARTDEBUG_GO            32790
#define ID_OPTIONS_SHOWLEGALINPUT       32791
#define ID_OPTIONS_ERRORS               32792
#define ID_OPTIONS_LISTDEBUGFROMPARSER  32793
#define ID_OPTIONS_LISTDEBUGFROMSCANNER 32794
#define ID_OPTIONS_ANIMATE              32795
#define ID_OPTIONS_STACKSIZE            32796
#define ID_OPTIONS_SHOWSTATE            32797
#define ID_PAGEUP                       32798
#define ID_PAGEDOWN                     32799
#define ID_LINEUP                       32800
#define ID_LINEDOWN                     32801
#define ID_HOME                         32802
#define ID_END                          32803
#define ID_EXPAND                       32804
#define ID_COLLAPSE                     32805
#define ID_EXPANDORCOLLAPSE             32806
#define ID_CHECKBREAKONPRODUCTION       32807
#define ID_CHECKBREAKONPOS              32808
#define ID_CHECKBREAKONERROR            32809
#define ID_GOTOMAXERRORCOUNT            32810
#define ID_GOTOERRORCASCADECOUNT        32811
#define ID_GOTONEXTERROR                32812
#define ID_GOTOPREVERROR                32813
#define ID_GOTOERRORSCONTROL            32814
#define ID_GOTOINPUTCONTROL             32815
#define ID_GOTODEBUGCONTROL             32816
#define ID_GOTOFINDWHAT                 32817
#define ID_REGSYMBOLS_ANYCHARACTER      32818
#define ID_REGSYMBOLS_CHARACTERINRANGE  32819
#define ID_REGSYMBOLS_BEGINNINGOFLINE   32820
#define ID_REGSYMBOLS_CHARACTERNOTINRANGE 32821
#define ID_REGSYMBOLS_ENDOFLINE         32822
#define ID_REGSYMBOLS_0ORMOREOCCURRENCES 32823
#define ID_REGSYMBOLS_1ORMOREOCCURRENCES 32824
#define ID_REGSYMBOLS_0OR1OCCURENCE     32825
#define ID_REGSYMBOLS_OR                32826
#define ID_REGSYMBOLS_GROUP             32827
#define ID_SHOWSTATE_UPDATE             32828

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
