//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ParserDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDD_DIALOGERRORS                129
#define IDD_DIALOGPRODUCTIONS           130
#define IDD_DIALOGTREE                  131
#define IDD_DIALOGSTATES                132
#define IDD_DIALOGFIND                  133
#define IDD_DIALOGSTACKSIZE             134
#define IDD_DIALOGSHOWSTATE             135
#define IDD_DIALOGBREAKSYMBOLS          136
#define IDD_DIALOGGOTO                  137
#define IDR_MENUREGSYMBOLS              140
#define IDR_ACCELERATORSHOWSTATE        141
#define IDR_ACCELERATORTREE             142
#define IDB_BITMAPTERMINAL              143
#define IDC_STATIC_INPUT                1001
#define IDC_EDITINPUTSTRING             1002
#define IDC_STATICSTACKLABEL            1003
#define IDC_STATICSTACK                 1004
#define IDC_ACTIONLABEL                 1005
#define IDC_ACTION                      1006
#define IDC_STATELABEL                  1007
#define IDC_STATE                       1008
#define IDC_LOOKAHEADLABEL              1009
#define IDC_LOOKAHEAD                   1010
#define IDC_CYCLECOUNTLABEL             1011
#define IDC_CYCLECOUNT                  1012
#define IDC_SOURCEPOSITION              1013
#define IDC_CHECKBREAKONPRODUCTION      1020
#define IDC_BREAKPRODTEXT               1021
#define IDC_CHECKBREAKONPOS             1022
#define IDC_CHECKBREAKONERROR           1023
#define IDC_BREAKSYMBOLTEXT             1024
#define IDC_CHECKBREAKONSYMBOL          1025
#define IDC_BREAKSTATETEXT              1026
#define IDC_CHECKBREAKONSTATE           1027
#define IDC_ERRORSLABEL                 1030
#define IDC_LISTERRORS                  1031
#define IDC_DEBUGLABEL                  1032
#define IDC_LISTDEBUG                   1033
#define IDC_DERIVATIONTREE              1050
#define IDC_BUTTONEXPAND                1051
#define IDC_BUTTONEXPANDALL             1052
#define IDC_BUTTONCLEAR                 1053
#define IDC_EDITCASCADECOUNT            1060
#define IDC_EDITMAXERRORCOUNT           1061
#define IDC_EDITSTATES                  1070
#define IDC_BUTTONSELECTALL             1071
#define IDC_PRODUCTIONLIST              1072
#define IDC_RADIO_SORTBYPROD            1073
#define IDC_RADIO_GROUPBYLEFTSIDE       1074
#define IDC_COMBOFINDWHAT               1080
#define IDC_BUTTONREGSYMBOLSMENU        1081
#define IDC_CHECKMATCHWHOLEWORD         1082
#define IDC_CHECKMATCHCASE              1083
#define IDC_CHECKUSEREGEXP              1084
#define IDC_RADIOUP                     1085
#define IDC_RADIODOWN                   1086
#define IDC_FINDNEXT                    1087
#define IDC_EDITSTACKSIZE               1090
#define IDC_EDITSTATE                   1100
#define IDC_LISTSYMBOLS                 1110
#define IDC_EDITLINENUMBER              1120
#define ID_FILE_DUMPACTIONMATRIX        32771
#define ID_FILE_EXIT                    32772
#define ID_EDIT_NEXTERROR               32780
#define ID_EDIT_PREVERROR               32781
#define ID_EDIT_FINDNEXT                32783
#define ID_EDIT_FINDPREV                32784
#define ID_EDIT_FINDMATCHINGPARANTHES   32785
#define ID_EDIT_GOTO                    32785
#define ID_EDIT_BREAKONTEXTPOSITION     32786
#define ID_EDIT_SELECTPRODTOBREAKON     32787
#define ID_EDIT_SELECTSTATESTOBREAKON   32788
#define ID_EDIT_SELECTSYMBOLSTOBREAKON  32789
#define ID_EDIT_DERIVATIONTREE          32790
#define ID_RUN_PARSEINPUT               32810
#define ID_RUN_STARTDEBUG_RESETPARSER   32811
#define ID_RUN_STARTDEBUG_RUN           32812
#define ID_RUN_STARTDEBUG_STEP          32813
#define ID_RUN_STARTDEBUG_STEPOVER      32814
#define ID_RUN_STARTDEBUG_GO            32815
#define ID_OPTIONS_SHOWLEGALINPUT       32830
#define ID_OPTIONS_ERRORS               32831
#define ID_OPTIONS_LISTDEBUGFROMPARSER  32832
#define ID_OPTIONS_LISTDEBUGFROMSCANNER 32833
#define ID_OPTIONS_ANIMATE              32834
#define ID_OPTIONS_STACKSIZE            32835
#define ID_OPTIONS_SHOWSTATE            32836
#define ID_HELP_ABOUTPARSERDEMO         32850
#define ID_CHECKBREAKONPRODUCTION       32900
#define ID_CHECKBREAKONPOS              32901
#define ID_CHECKBREAKONERROR            32902
#define ID_GOTONEXTERROR                32903
#define ID_GOTOPREVERROR                32904
#define ID_PAGEUP                       32920
#define ID_PAGEDOWN                     32921
#define ID_LINEUP                       32922
#define ID_LINEDOWN                     32923
#define ID_HOME                         32924
#define ID_END                          32925
#define ID_EXPAND                       33800
#define ID_COLLAPSE                     33801
#define ID_EXPANDORCOLLAPSE             33802
#define ID_REGSYMBOLS_ANYCHAR           33820
#define ID_REGSYMBOLS_CHARINRANGE       33821
#define ID_REGSYMBOLS_CHARNOTINRANGE    33822
#define ID_REGSYMBOLS_BEGINOFLINE       33823
#define ID_REGSYMBOLS_ENDOFLINE         33824
#define ID_REGSYMBOLS_0ORMORE           33825
#define ID_REGSYMBOLS_1ORMORE           33826
#define ID_REGSYMBOLS_0OR1              33827
#define ID_REGSYMBOLS_OR                33828
#define ID_REGSYMBOLS_GROUP             33829
#define ID_MSG_SHOWSTATE_UPDATE         33900

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         33901
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
