white:Kg1,Qa6,Rb1,Rb8,a2,g2,h2,e4,g6;
black:Kh8,Qf8,Rc2,Re8,d6,f6,h6,c7,g7;
PlayerInTurn:white;
History

EndHistory
Settings
ShowFieldNames:1
ShowLegalMoves:1
ShowPlayerToMoMove:1
AnimateMoves:1
AnimateCheckmate:1
ComputerIsWhite:0
Validate:1
Level:6
WhiteLevel:4
BlackLevel:4
HistoryFormat:0
EndSettings
