white:Kh5,Re2,Rb5,Na1,Nh3,b2,c2,g3;
black:Kh1,Rc8,Bd8,Na8,a3,e3,b6,b7,f7,h7;
PlayerInTurn:white;
History

EndHistory
Settings
ShowFieldNames:1
ShowLegalMoves:1
ShowPlayerToMoMove:1
AnimateMoves:0
AnimateCheckmate:1
ComputerIsWhite:0
Validate:0
Level:6
WhiteLevel:4
BlackLevel:4
HistoryFormat:0
EndSettings
