white:Kg1,Rb7,Nc3,a2,b2,g2,h2;
black:Kh7,Rd8,Bb6,c4,c5,a7,g7;
PlayerInTurn:black;
History

EndHistory
Settings
ShowFieldNames:1
ShowLegalMoves:1
ShowPlayerToMoMove:1
AnimateMoves:1
AnimateCheckmate:1
ComputerIsWhite:0
Validate:1
Level:5
WhiteLevel:4
BlackLevel:4
HistoryFormat:0
EndSettings
