white:Ka5,Qd4,a4,h4,b5,f5;
black:Kb8,Qe7,h5,f6,f7;
PlayerInTurn:black;
History

EndHistory
Settings
ShowFieldNames:1
ShowLegalMoves:1
ShowPlayerToMoMove:1
AnimateMoves:1
AnimateCheckmate:1
ComputerIsWhite:0
Validate:1
Level:5
WhiteLevel:4
BlackLevel:4
HistoryFormat:0
EndSettings
